require 'cocos'




require_relative 'parser/version'


require_relative 'parser/debuggable'    ## generic debug/logger helper



##
## add shared/most basic regexes here
## todo - use ANY_RE  to token_commons or such - for shared by many?
module Fbtxt
class Lexer

## general catch-all  (RECOMMENDED (ALWAYS) use as last entry in union)
##   to avoid advance of pos match!!!
ANY_RE = %r{
               (?<any> .)
          }ix

SPACES_RE = %r{
                  (?<spaces> [ ]{2,})
                | (?<space>  [ ])
             }ix


end # class Lexer
end # module Fbtxt


require_relative 'lexer/token-score'
require_relative 'lexer/token-score_full'
require_relative 'lexer/token-score_fuller'
require_relative 'lexer/token-score_legs'
require_relative 'lexer/token-score--helpers'

require_relative 'lexer/token-time'
require_relative 'lexer/token-date--names'
require_relative 'lexer/token-date'
require_relative 'lexer/token-date_duration'
require_relative 'lexer/token-date--helpers'

require_relative 'lexer/token-text'
require_relative 'lexer/token-prop'    ## team prop(erty) mode (note - must be before token)
require_relative 'lexer/token-prop_name'    ## a.k.a token-text_ii
require_relative 'lexer/token-status'
require_relative 'lexer/token-status_inline'
require_relative 'lexer/token-note'
require_relative 'lexer/token-goals'
require_relative 'lexer/token-goals--helpers'
require_relative 'lexer/token-geo'
require_relative 'lexer/token-group'
require_relative 'lexer/token-round'
require_relative 'lexer/token'





require_relative 'lexer/lexer_buffer'   ## incl. Tokens (aka TokenBuffer)
require_relative 'lexer/lexer_token'
require_relative 'lexer/lexer_context'

require_relative 'lexer/lexer-prep_doc'
require_relative 'lexer/lexer-prep_line'

require_relative 'lexer/lexer-logger'   ## e.g. _trace, _warn, _info, etc.
require_relative 'lexer/lexer-on_round_def'
require_relative 'lexer/lexer-on_group_def'
require_relative 'lexer/lexer-on_prop_misc'
require_relative 'lexer/lexer-on_prop_lineup'
require_relative 'lexer/lexer-on_prop_penalties'
require_relative 'lexer/lexer-on_goal'
require_relative 'lexer/lexer-on_top'
require_relative 'lexer/lexer-props'

require_relative 'lexer/lexer-tokenize-i'
require_relative 'lexer/lexer-tokenize-ii'     ## that is, normalize (transform) tokens
require_relative 'lexer/lexer'


## note - use "embeded" racc parser runtime
##    MUST uncomment  require 'racc/parser'  in generated parser!!!
require_relative 'parser/parser-runtime'

require_relative 'parser/parser'   ## auto-generated by racc (from parser.y)
require_relative 'parser/parser-top'

require_relative 'parser/parse_tree--core'    ## incl. core extensions eg. as_json on Object/Array/Hash
require_relative 'parser/parse_tree'
require_relative 'parser/parse_tree-match'
require_relative 'parser/parse_tree-props'


## deprecated - remove old RaccMatchParser name sooner than later!!
##    use Fbtxt.parse for "public" api
##
RaccMatchParser = Fbtxt::Parser



###
#  make parser api (easily) available - why? why not?
#
#  use Fbtxt.parse( txt ) &&
#      Fbtxt.lex( txt)            -- or Fbtxt.tokenize?
#
#   Fbtxt.lex( txt,
#                 flatten: true|false,        ## keep nested [] for lines (no NEWLINE tokens)
#                 transform: true|false )     ## builtin transforms eg. merge DATE & TIME => DATETIME, etc.
#
#   how to deal with errors?
##    always return   [tokens, errors] or such?
##           or return a Result struct - why? why not?



module Fbtxt

def self.lex( txt, flatten: true )      ## returns Fbtxt::LexerResult (ok?/tokens/errors)
  lexer = Lexer.new( txt )
  ## move "wrapping" into result obj inside lexer - why? why not?
  tokens, errors = lexer.tokenize_with_errors( flatten: flatten )
  LexerResult.new( tokens, errors )
end

def self.parse( txt )   ## returns Fbtxt::ParserResult (ok?/tree/errors)
  parser = Parser.new( txt )
  ## move "wrapping" into result obj inside parser - why? why not?
  tree, errors = parser.parse_with_errors
  ParserResult.new( tree, errors )
end
end #  module Fbtxt






puts Fbtxt::Module::Parser.banner    # say hello
