
####
#  quick hack - always auto-add latest lexer if present for now
$LOAD_PATH.unshift( '../lexer/lib' )
require 'fbtxt/lexer'


require_relative 'parser/version'



## note - use "embeded" racc parser runtime
##    MUST uncomment  require 'racc/parser'  in generated parser!!!
require_relative 'parser/parser-runtime'

require_relative 'parser/parser'   ## auto-generated by racc (from parser.y)
require_relative 'parser/parser-top'

require_relative 'parser/parse_tree--core'    ## incl. core extensions eg. as_json on Object/Array/Hash
require_relative 'parser/parse_tree'
require_relative 'parser/parse_tree-match'
require_relative 'parser/parse_tree-props'


## deprecated - remove old RaccMatchParser name sooner than later!!
##    use Fbtxt.parse for "public" api
##
RaccMatchParser = Fbtxt::Parser



###
#  make parser api (easily) available - why? why not?
#
#  use Fbtxt.parse( txt ) &&
#      Fbtxt.lex( txt)            -- or Fbtxt.tokenize?
#
#   Fbtxt.lex( txt,
#                 flatten: true|false,        ## keep nested [] for lines (no NEWLINE tokens)
#                 transform: true|false )     ## builtin transforms eg. merge DATE & TIME => DATETIME, etc.
#
#   how to deal with errors?
##    always return   [tokens, errors] or such?
##           or return a Result struct - why? why not?


module Fbtxt

class ParserResult
   attr_reader :tree, :errors
   def initialize( tree, errors=[] )
       @tree, @errors = tree, errors
   end

   def ok?()  @errors.size == 0; end
   def nok?() !ok?; end
end  # class ParserResult


def self.parse( txt )   ## returns Fbtxt::ParserResult (ok?/tree/errors)
  parser = Parser.new( txt )
  ## move "wrapping" into result obj inside parser - why? why not?
  tree, errors = parser.parse_with_errors
  ParserResult.new( tree, errors )
end
end #  module Fbtxt





puts Fbtxt::Module::Parser.banner    # say hello
