require 'hoe'


Hoe.spec 'fbtok' do
  self.version = '0.9.2'

  self.summary = "fbtok - football.txt lint tools incl. tokenizer, parser & more"
  self.description = summary

  self.urls = { home: 'https://github.com/sportdb/footty' }

  self.author = 'Gerald Bauer'
  self.email  = 'gerald.bauer@gmail.com'

  # switch extension to .markdown for gihub formatting
  self.readme_file  = 'README.md'
  self.history_file = 'CHANGELOG.md'

  self.licenses = ['Public Domain']

  self.extra_deps = [
     ['fbtxt-parser',    '>= 0.9.0'],
     ['fbtxt-document',  '>= 0.9.0'],
  ]

  self.spec_extras = {
    required_ruby_version: '>= 3.1.0'
  }
end
