require 'hoe'
require './lib/fbtxt/lexer/version.rb'


Hoe.spec 'fbtxt-lexer' do

  self.version = Fbtxt::Module::Lexer::VERSION

  self.summary = "fbtxt-lexer - football.txt match lexer (& tokenizer)"
  self.description = summary

  self.urls = { home: 'https://github.com/sportdb/sport.db' }

  self.author = 'Gerald Bauer'
  self.email  = 'gerald.bauer@gmail.com'

  # switch extension to .markdown for gihub formatting
  self.readme_file  = 'README.md'
  self.history_file = 'CHANGELOG.md'

  self.licenses = ['Public Domain']

  self.extra_deps = [
       ['cocos', '>= 0.4.2'],
  ]

  self.spec_extras = {
    required_ruby_version: '>= 3.1.0'
  }
end
