#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.8.1
# from Racc grammar file "parser.y".
#

require 'racc/parser.rb'
class RaccMatchParser < Racc::Parser
##### State transition tables begin ###

racc_action_table = [
    25,    24,    26,   240,    27,    28,    29,    30,   164,   240,
    31,    42,   305,    32,    33,    34,   245,    35,    36,    37,
    40,    41,   216,   235,   216,   307,   124,   259,   334,   322,
   287,   215,   321,   215,   216,   260,   261,    71,    44,    45,
    46,    48,   256,   215,   312,   241,   165,   216,    73,   169,
   216,   241,    62,    44,    45,    46,   215,   238,   246,   215,
    63,   288,    64,   243,    65,   236,   223,    66,   229,   320,
   244,    67,    68,    69,    70,    25,    24,    26,   226,    27,
    28,    29,    30,   164,   304,    31,    42,  -139,    32,    33,
    34,   253,    35,    36,    37,    40,    41,   306,   213,   214,
  -139,   129,   252,  -139,   132,   203,   149,   227,   132,   228,
   232,    74,   149,    44,    45,    46,    48,   144,    75,    41,
   146,   165,   144,    41,   124,   146,    34,    62,    35,    36,
    37,    76,   150,   251,    77,    63,   231,    64,   150,    65,
    81,   130,    66,    78,    79,   130,    67,    68,    69,    70,
    41,    44,    45,    46,    89,    90,    92,    93,    94,    98,
    85,    95,    96,    97,    86,    99,   100,   101,   102,   105,
   106,   107,    88,   120,   121,   110,   220,   122,   222,   111,
   103,   104,    89,    90,    92,    93,    94,    98,   112,    95,
    96,    97,   109,    99,   100,   101,   102,   105,   106,   113,
   105,   106,   107,   281,   116,   282,   315,   317,   316,    83,
    82,   174,   175,    48,   195,   120,   121,   120,   121,   120,
   121,   277,  -148,   337,   338,   133,   133,   136,   122,   153,
   154,   157,   160,   160,   169,   170,   172,   176,   177,   178,
   179,   180,   181,   182,   183,   184,   185,   186,   187,   188,
   189,   190,   191,   198,   199,    41,   204,    41,   207,   208,
   122,   211,   146,   225,   233,   237,   242,   248,   249,   256,
   258,   262,   263,   264,   266,   267,   133,   270,   271,   146,
   273,   274,   275,   146,   279,   283,   284,   285,   153,   289,
   290,   291,   157,   293,   294,   160,   296,   297,   298,   299,
   300,   302,   303,   308,   169,   318,   323,   222,   325,   326,
   327,   328,   329,   330,   331,   332,   333,   335,   169,   339,
   340,   341,   342,   256,   344,   345 ]

racc_action_check = [
     0,     0,     0,   158,     0,     0,     0,     0,    69,   161,
     0,     0,   251,     0,     0,     0,   162,     0,     0,     0,
     0,     0,   147,   155,   151,   252,    51,   171,   310,   265,
   231,   147,   265,   151,   218,   171,   171,     1,     0,     0,
     0,     0,   310,   218,   256,   158,    69,   143,    26,   256,
   272,   161,     0,    51,    51,    51,   143,   158,   162,   272,
     0,   231,     0,   161,     0,   155,   147,     0,   151,   265,
   162,     0,     0,     0,     0,     2,     2,     2,   150,     2,
     2,     2,     2,   247,   251,     2,     2,   218,     2,     2,
     2,   166,     2,     2,     2,     2,     2,   252,   143,   143,
   143,    52,   166,   272,    52,   126,    63,   150,   126,   150,
   153,    27,   224,     2,     2,     2,     2,    62,    28,    52,
    62,   247,   136,   126,   194,   136,    56,     2,    56,    56,
    56,    29,    63,   166,    30,     2,   153,     2,   224,     2,
    32,    52,     2,    31,    31,   126,     2,     2,     2,     2,
    50,   194,   194,   194,    42,    42,    42,    42,    42,    42,
    38,    42,    42,    42,    40,    42,    42,    42,    42,    43,
    43,    43,    41,    50,    50,    44,   146,    50,   146,    45,
    42,    42,   124,   124,   124,   124,   124,   124,    46,   124,
   124,   124,    43,   124,   124,   124,   124,    47,    47,    47,
   125,   125,   125,   225,    49,   225,   257,   257,   257,    33,
    33,    84,    84,   117,   117,   118,   118,   131,   131,   205,
   205,   219,   219,   315,   315,    53,    54,    55,    57,    64,
    65,    66,    67,    68,    70,    71,    80,    87,    91,    92,
    93,    94,    95,    96,    97,    98,    99,   100,   101,   102,
   104,   109,   115,   119,   121,   122,   128,   130,   134,   135,
   140,   142,   144,   149,   154,   157,   160,   164,   165,   168,
   169,   173,   176,   181,   196,   202,   206,   209,   211,   212,
   213,   214,   215,   217,   223,   227,   228,   229,   230,   232,
   233,   234,   235,   236,   238,   239,   241,   243,   244,   245,
   246,   248,   250,   253,   254,   261,   270,   278,   288,   289,
   291,   293,   303,   304,   305,   306,   307,   311,   312,   320,
   321,   331,   333,   334,   336,   343 ]

racc_action_pointer = [
    -1,    37,    74,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,    44,   107,   114,   127,
   130,   134,   136,   200,   nil,   nil,   nil,   nil,   156,   nil,
   160,   149,   130,   140,   163,   167,   176,   168,   nil,   202,
   128,    14,    97,   218,   219,   180,   110,   179,   nil,   nil,
   nil,   nil,    63,    75,   165,   164,   162,   163,   164,   -23,
   165,   235,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   224,   nil,   nil,   nil,   195,   nil,   nil,   224,   nil,   nil,
   nil,   226,   227,   228,   229,   230,   231,   232,   233,   234,
   235,   236,   237,   nil,   238,   nil,   nil,   nil,   nil,   247,
   nil,   nil,   nil,   nil,   nil,   250,   nil,   171,   170,   249,
   nil,   209,   233,   nil,   158,   171,   101,   nil,   252,   nil,
   235,   172,   nil,   nil,   254,   255,    68,   nil,   nil,   nil,
   211,   nil,   213,    43,   205,   nil,   118,    18,   nil,   206,
    47,    20,   nil,    79,   197,    10,   nil,   195,   -10,   nil,
   202,    -4,     3,   nil,   198,   198,    78,   nil,   191,   193,
   nil,    23,   nil,   267,   nil,   nil,   249,   nil,   nil,   nil,
   nil,   239,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   112,   nil,   270,   nil,   nil,   nil,
   nil,   nil,   271,   nil,   nil,   174,   269,   nil,   nil,   229,
   nil,   274,   222,   276,   277,   278,   nil,   226,    30,   162,
   nil,   nil,   nil,   280,    81,   143,   nil,   254,   255,   283,
   224,    -1,   232,   286,   224,   223,   222,   nil,   290,   226,
   nil,   292,   nil,   293,   294,   295,   296,    52,   231,   nil,
   235,     8,    21,   299,   235,   nil,   -20,   126,   nil,   nil,
   nil,   293,   nil,   nil,   nil,    25,   nil,   nil,   nil,   nil,
   302,   nil,    46,   nil,   nil,   nil,   nil,   nil,   247,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   277,   247,
   nil,   306,   nil,   245,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   308,   244,   238,   246,   240,   nil,   nil,
   -36,   238,   249,   nil,   nil,   142,   nil,   nil,   nil,   nil,
   315,   316,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   252,   nil,   253,   245,   nil,   245,   nil,   nil,   nil,
   nil,   nil,   nil,   246,   nil,   nil ]

racc_action_default = [
    -1,  -224,    -2,    -3,    -5,    -6,    -7,    -8,    -9,   -10,
   -11,   -12,   -13,   -14,   -15,   -16,   -17,   -18,   -19,   -20,
   -21,   -22,   -23,   -24,   -25,   -26,  -224,  -224,  -224,  -224,
  -224,  -224,  -224,  -224,   -48,   -49,   -50,   -51,   -52,   -53,
  -224,  -224,  -224,  -123,  -224,  -224,  -224,  -126,   -88,   -32,
  -112,  -224,  -224,  -103,  -103,  -122,   -54,  -112,  -117,  -124,
  -125,  -127,  -224,  -224,  -224,  -224,  -224,  -224,  -224,  -224,
  -224,  -224,    -4,   -27,   -28,   -29,   -30,   -31,   -36,   -37,
  -224,   -42,   -43,   -44,  -224,   -57,   -58,   -59,   -60,   -64,
   -65,  -224,  -224,  -224,  -224,  -224,  -224,  -224,  -224,  -224,
  -224,  -224,  -224,  -128,  -224,   -70,   -71,   -77,   -78,  -224,
   -83,   -84,   -85,   -86,   -87,   -33,   -34,   -89,  -101,  -224,
   -99,  -224,   -62,  -115,  -224,  -123,  -224,  -122,  -224,  -108,
  -118,  -101,  -121,  -104,  -224,  -224,  -224,   -52,   -55,   -56,
  -112,  -116,  -224,  -132,  -224,  -143,  -147,  -139,  -154,  -224,
  -224,  -139,  -163,  -224,  -224,  -175,  -171,  -173,  -224,  -179,
  -184,  -224,  -224,  -191,  -224,  -195,  -198,  -207,  -215,  -211,
   346,  -224,   -39,  -224,   -46,   -47,  -224,   -66,   -67,   -68,
   -69,   -72,   -73,   -74,   -76,   -79,   -80,   -81,   -82,  -129,
  -130,   -35,   -90,   -91,  -224,   -93,  -224,  -102,   -98,  -100,
   -63,  -113,  -224,  -106,  -107,  -101,  -103,  -109,  -110,  -224,
  -114,  -224,  -224,  -135,  -137,  -140,  -142,  -224,  -133,  -145,
  -146,  -150,  -152,  -224,  -224,  -156,  -159,  -224,  -224,  -224,
  -224,  -224,  -224,  -224,  -224,  -224,  -224,  -174,  -224,  -224,
  -181,  -182,  -185,  -224,  -224,  -187,  -189,  -224,  -193,  -196,
  -224,  -224,  -205,  -203,  -224,  -209,  -224,  -213,  -212,   -38,
   -40,  -224,   -45,   -61,   -75,  -224,   -97,  -105,  -119,  -120,
  -224,  -131,  -134,  -136,  -138,  -141,  -144,  -149,  -224,  -153,
  -155,  -157,  -158,  -160,  -161,  -162,  -164,  -165,  -224,  -167,
  -169,  -224,  -172,  -224,  -177,  -180,  -183,  -178,  -186,  -188,
  -190,  -192,  -194,  -224,  -224,  -224,  -224,  -206,  -204,  -208,
  -215,  -224,  -224,  -210,  -214,  -219,  -222,  -223,   -41,   -92,
  -224,  -224,   -96,  -111,  -151,  -166,  -168,  -170,  -176,  -197,
  -199,  -224,  -201,  -224,  -215,  -217,  -224,  -220,  -221,   -94,
   -95,  -200,  -202,  -224,  -218,  -216 ]

racc_goto_table = [
   167,   163,   156,   152,   148,   134,   135,   125,   127,   126,
   221,   123,   196,   118,   128,   131,   142,   224,   141,   218,
     3,   230,    72,   158,   161,   206,     1,     2,   117,   115,
    80,   171,    84,   173,   137,   139,   138,   140,    87,   201,
   114,   192,   194,   193,   319,   119,   212,   276,   219,   278,
   147,   151,   155,   234,   295,   162,   247,   166,   250,   254,
   310,   343,   257,   313,   314,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   200,   nil,   272,   202,   131,
   209,   nil,   nil,   205,   nil,   nil,   nil,   nil,   nil,   268,
   nil,   210,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   324,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   125,   127,   265,   nil,   nil,   nil,   nil,   nil,   269,   nil,
   nil,   nil,   nil,   nil,   nil,   280,   nil,   nil,   nil,   286,
   nil,   292,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   301,
   nil,   nil,   nil,   nil,   309,   nil,   311,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   336 ]

racc_goto_check = [
    84,    80,    74,    71,    69,    54,    54,    39,    43,    50,
    67,    60,    52,    35,    56,    35,    59,    63,    60,    61,
     3,    63,     3,    75,    75,    52,     1,     2,    24,    25,
    26,    27,    28,    29,    30,    32,    33,    34,    36,    37,
    42,    46,    47,    49,    51,    53,    62,    64,    65,    66,
    68,    70,    72,    73,    76,    78,    79,    81,    82,    83,
    85,    86,    87,    88,    89,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    35,   nil,    61,    56,    35,
    59,   nil,   nil,    35,   nil,   nil,   nil,   nil,   nil,    52,
   nil,    60,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    67,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
    39,    43,    50,   nil,   nil,   nil,   nil,   nil,    54,   nil,
   nil,   nil,   nil,   nil,   nil,    69,   nil,   nil,   nil,    71,
   nil,    74,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    80,
   nil,   nil,   nil,   nil,    84,   nil,    84,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    84 ]

racc_goto_pointer = [
   nil,    26,    27,    20,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   -21,   -20,    -1,   -49,    -1,   -51,
   -22,   nil,   -21,   -20,   -19,   -37,    -3,   -83,   nil,   -44,
   nil,   nil,    -7,   -43,   nil,   nil,   -76,   -75,   nil,   -74,
   -42,  -221,  -106,    -5,   -48,   nil,   -38,   nil,   nil,   -46,
   -39,  -125,   -97,  -130,  -170,   -98,  -170,  -136,   -13,   -59,
   -13,   -61,   -14,  -102,   -64,   -44,  -185,   nil,   -14,  -106,
   -68,   -13,  -108,  -107,   -70,  -196,  -273,  -107,  -194,  -193 ]

racc_goto_default = [
   nil,   nil,   nil,   nil,     4,     5,     6,     7,     8,     9,
    10,    11,    12,    13,    14,    15,    16,    17,    18,    19,
    20,    21,    22,    23,   nil,   nil,   nil,   nil,   nil,   nil,
    38,    39,    57,    50,   nil,    58,   nil,   nil,    91,    43,
    59,    60,   108,    55,    47,    61,    56,   nil,    49,   nil,
    52,   nil,   nil,   197,   nil,    51,   nil,    53,    54,   nil,
   nil,   143,   nil,   217,   145,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   159,   239,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   168,   255,   nil,   nil,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  0, 84, :_reduce_1,
  1, 84, :_reduce_none,
  1, 85, :_reduce_none,
  2, 85, :_reduce_none,
  1, 86, :_reduce_none,
  1, 86, :_reduce_none,
  1, 86, :_reduce_none,
  1, 86, :_reduce_none,
  1, 86, :_reduce_none,
  1, 86, :_reduce_none,
  1, 86, :_reduce_none,
  1, 86, :_reduce_none,
  1, 86, :_reduce_none,
  1, 86, :_reduce_none,
  1, 86, :_reduce_none,
  1, 86, :_reduce_none,
  1, 86, :_reduce_none,
  1, 86, :_reduce_none,
  1, 86, :_reduce_none,
  1, 86, :_reduce_none,
  1, 86, :_reduce_none,
  1, 86, :_reduce_none,
  1, 86, :_reduce_none,
  1, 86, :_reduce_none,
  1, 86, :_reduce_25,
  1, 86, :_reduce_26,
  2, 87, :_reduce_27,
  2, 87, :_reduce_28,
  2, 87, :_reduce_29,
  2, 96, :_reduce_30,
  2, 97, :_reduce_31,
  0, 107, :_reduce_32,
  1, 107, :_reduce_none,
  1, 108, :_reduce_none,
  2, 108, :_reduce_none,
  1, 109, :_reduce_none,
  1, 109, :_reduce_none,
  4, 88, :_reduce_38,
  1, 110, :_reduce_39,
  2, 110, :_reduce_40,
  3, 110, :_reduce_41,
  2, 90, :_reduce_42,
  1, 111, :_reduce_none,
  1, 111, :_reduce_none,
  4, 89, :_reduce_45,
  1, 112, :_reduce_46,
  1, 112, :_reduce_47,
  1, 113, :_reduce_48,
  1, 113, :_reduce_49,
  1, 114, :_reduce_50,
  1, 115, :_reduce_51,
  1, 116, :_reduce_none,
  1, 116, :_reduce_none,
  0, 117, :_reduce_54,
  1, 117, :_reduce_none,
  1, 117, :_reduce_none,
  2, 91, :_reduce_57,
  2, 94, :_reduce_58,
  2, 118, :_reduce_59,
  1, 119, :_reduce_60,
  3, 119, :_reduce_61,
  0, 120, :_reduce_62,
  1, 120, :_reduce_none,
  1, 121, :_reduce_none,
  1, 121, :_reduce_none,
  3, 122, :_reduce_66,
  3, 123, :_reduce_67,
  3, 123, :_reduce_68,
  3, 124, :_reduce_69,
  1, 125, :_reduce_none,
  1, 125, :_reduce_none,
  3, 126, :_reduce_72,
  3, 126, :_reduce_73,
  3, 126, :_reduce_74,
  4, 126, :_reduce_75,
  3, 126, :_reduce_76,
  2, 126, :_reduce_77,
  2, 126, :_reduce_78,
  3, 126, :_reduce_79,
  3, 126, :_reduce_80,
  3, 126, :_reduce_81,
  3, 126, :_reduce_82,
  2, 127, :_reduce_83,
  2, 127, :_reduce_84,
  2, 127, :_reduce_85,
  2, 128, :_reduce_86,
  2, 128, :_reduce_87,
  1, 129, :_reduce_88,
  0, 130, :_reduce_89,
  1, 130, :_reduce_none,
  3, 92, :_reduce_91,
  3, 132, :_reduce_92,
  1, 132, :_reduce_none,
  2, 134, :_reduce_94,
  2, 134, :_reduce_95,
  1, 134, :_reduce_96,
  4, 131, :_reduce_97,
  3, 131, :_reduce_98,
  1, 136, :_reduce_99,
  2, 136, :_reduce_100,
  0, 135, :_reduce_101,
  1, 135, :_reduce_none,
  0, 137, :_reduce_103,
  1, 137, :_reduce_104,
  4, 93, :_reduce_105,
  3, 93, :_reduce_106,
  3, 93, :_reduce_107,
  2, 93, :_reduce_108,
  3, 93, :_reduce_109,
  3, 93, :_reduce_110,
  5, 93, :_reduce_111,
  0, 143, :_reduce_112,
  2, 143, :_reduce_113,
  3, 138, :_reduce_114,
  2, 138, :_reduce_115,
  2, 138, :_reduce_116,
  1, 138, :_reduce_none,
  1, 139, :_reduce_118,
  3, 139, :_reduce_119,
  3, 139, :_reduce_120,
  1, 139, :_reduce_121,
  1, 133, :_reduce_none,
  1, 133, :_reduce_none,
  1, 133, :_reduce_none,
  1, 133, :_reduce_none,
  1, 133, :_reduce_none,
  1, 133, :_reduce_none,
  2, 140, :_reduce_128,
  3, 141, :_reduce_129,
  3, 95, :_reduce_130,
  4, 98, :_reduce_131,
  1, 142, :_reduce_132,
  2, 142, :_reduce_133,
  3, 142, :_reduce_134,
  1, 145, :_reduce_none,
  2, 145, :_reduce_none,
  1, 145, :_reduce_none,
  2, 145, :_reduce_none,
  0, 146, :_reduce_139,
  1, 146, :_reduce_none,
  2, 146, :_reduce_none,
  1, 146, :_reduce_none,
  1, 144, :_reduce_143,
  3, 144, :_reduce_144,
  2, 147, :_reduce_145,
  2, 147, :_reduce_146,
  1, 147, :_reduce_147,
  0, 149, :_reduce_148,
  1, 149, :_reduce_none,
  1, 148, :_reduce_150,
  3, 148, :_reduce_151,
  1, 150, :_reduce_152,
  4, 99, :_reduce_153,
  1, 151, :_reduce_154,
  3, 151, :_reduce_155,
  2, 152, :_reduce_156,
  3, 152, :_reduce_157,
  3, 152, :_reduce_158,
  2, 152, :_reduce_159,
  3, 152, :_reduce_160,
  3, 152, :_reduce_161,
  4, 100, :_reduce_162,
  1, 153, :_reduce_163,
  3, 153, :_reduce_164,
  3, 154, :_reduce_165,
  4, 154, :_reduce_166,
  3, 154, :_reduce_167,
  4, 154, :_reduce_168,
  4, 106, :_reduce_169,
  5, 105, :_reduce_170,
  1, 155, :_reduce_171,
  3, 155, :_reduce_172,
  1, 157, :_reduce_173,
  2, 157, :_reduce_174,
  0, 156, :_reduce_none,
  3, 156, :_reduce_176,
  4, 102, :_reduce_177,
  4, 103, :_reduce_178,
  1, 158, :_reduce_179,
  3, 158, :_reduce_180,
  1, 160, :_reduce_none,
  1, 160, :_reduce_none,
  2, 160, :_reduce_none,
  1, 159, :_reduce_184,
  2, 159, :_reduce_185,
  4, 104, :_reduce_186,
  1, 162, :_reduce_none,
  2, 162, :_reduce_none,
  1, 162, :_reduce_none,
  2, 162, :_reduce_none,
  1, 161, :_reduce_191,
  3, 161, :_reduce_192,
  2, 163, :_reduce_193,
  3, 163, :_reduce_194,
  1, 163, :_reduce_195,
  2, 163, :_reduce_196,
  5, 101, :_reduce_197,
  0, 165, :_reduce_198,
  3, 165, :_reduce_199,
  4, 165, :_reduce_200,
  3, 165, :_reduce_201,
  4, 165, :_reduce_202,
  1, 166, :_reduce_203,
  2, 166, :_reduce_204,
  1, 166, :_reduce_205,
  2, 166, :_reduce_206,
  1, 164, :_reduce_207,
  3, 164, :_reduce_208,
  2, 167, :_reduce_209,
  3, 168, :_reduce_210,
  0, 170, :_reduce_211,
  1, 170, :_reduce_212,
  0, 171, :_reduce_213,
  1, 171, :_reduce_214,
  0, 169, :_reduce_215,
  5, 169, :_reduce_216,
  3, 169, :_reduce_217,
  4, 169, :_reduce_218,
  1, 172, :_reduce_219,
  2, 172, :_reduce_220,
  2, 172, :_reduce_221,
  1, 172, :_reduce_222,
  1, 172, :_reduce_223 ]

racc_reduce_n = 224

racc_shift_n = 346

racc_token_table = {
  false => 0,
  :error => 1,
  :BLANK => 2,
  :H1 => 3,
  :NEWLINE => 4,
  :H2 => 5,
  :H3 => 6,
  :NOTE => 7,
  :NOTA_BENE => 8,
  "|" => 9,
  ":" => 10,
  :GROUP_DEF => 11,
  :TEAM => 12,
  "," => 13,
  :ROUND_OUTLINE => 14,
  :ROUND_DEF => 15,
  :DATE => 16,
  :DURATION => 17,
  :YEAR => 18,
  :DATETIME => 19,
  :TIME => 20,
  :DATE_LEGS => 21,
  "@" => 22,
  :GEO => 23,
  "-" => 24,
  :VS => 25,
  :INLINE_NP => 26,
  :INLINE_CANC => 27,
  :INLINE_PPD => 28,
  :SCORE_FULL => 29,
  :SCORE_FULLER => 30,
  :SCORE => 31,
  :SCORE_AWD => 32,
  :SCORE_ABD => 33,
  :SCORE_FULLER_MORE => 34,
  :INLINE_AWD => 35,
  :INLINE_ABD => 36,
  :INLINE_VOID => 37,
  :INLINE_SUSP => 38,
  :TEAM_HOME => 39,
  :TEAM_AWAY => 40,
  :TEAM_NEUTRAL => 41,
  :ORD => 42,
  :match_line_alt_props => 43,
  :STATUS => 44,
  :INLINE_ATTENDANCE => 45,
  :INLINE_ATTENDANCE_SEP => 46,
  :INLINE_GOALS => 47,
  :GOALS_END => 48,
  :INLINE_ROUND => 49,
  :INLINE_BYE => 50,
  :INLINE_WO => 51,
  :SCORE_LEGS => 52,
  :GOALS => 53,
  :GOALS_NONE => 54,
  ";" => 55,
  :GOAL_SEP_ALT => 56,
  :PLAYER => 57,
  :GOAL_COUNT => 58,
  :GOAL_MINUTE_SEP => 59,
  :GOAL_MINUTE => 60,
  :GOALS_ALT => 61,
  :GOAL_TYPE => 62,
  :GOALS_COMPAT => 63,
  :MINUTE => 64,
  :PROP_ATTENDANCE => 65,
  :PROP_NUM => 66,
  :PROP_END => 67,
  :PROP_REFEREE => 68,
  :PROP_NAME => 69,
  :ENCLOSED_NAME => 70,
  :ATTENDANCE => 71,
  :PROP_YELLOWCARDS => 72,
  :PROP_REDCARDS => 73,
  :PROP_PENALTIES => 74,
  :PROP => 75,
  :COACH => 76,
  :INLINE_CAPTAIN => 77,
  "(" => 78,
  ")" => 79,
  :INLINE_YELLOW => 80,
  :INLINE_YELLOW_RED => 81,
  :INLINE_RED => 82 }

racc_nt_base = 83

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]
Ractor.make_shareable(Racc_arg) if defined?(Ractor)

Racc_token_to_s_table = [
  "$end",
  "error",
  "BLANK",
  "H1",
  "NEWLINE",
  "H2",
  "H3",
  "NOTE",
  "NOTA_BENE",
  "\"|\"",
  "\":\"",
  "GROUP_DEF",
  "TEAM",
  "\",\"",
  "ROUND_OUTLINE",
  "ROUND_DEF",
  "DATE",
  "DURATION",
  "YEAR",
  "DATETIME",
  "TIME",
  "DATE_LEGS",
  "\"@\"",
  "GEO",
  "\"-\"",
  "VS",
  "INLINE_NP",
  "INLINE_CANC",
  "INLINE_PPD",
  "SCORE_FULL",
  "SCORE_FULLER",
  "SCORE",
  "SCORE_AWD",
  "SCORE_ABD",
  "SCORE_FULLER_MORE",
  "INLINE_AWD",
  "INLINE_ABD",
  "INLINE_VOID",
  "INLINE_SUSP",
  "TEAM_HOME",
  "TEAM_AWAY",
  "TEAM_NEUTRAL",
  "ORD",
  "match_line_alt_props",
  "STATUS",
  "INLINE_ATTENDANCE",
  "INLINE_ATTENDANCE_SEP",
  "INLINE_GOALS",
  "GOALS_END",
  "INLINE_ROUND",
  "INLINE_BYE",
  "INLINE_WO",
  "SCORE_LEGS",
  "GOALS",
  "GOALS_NONE",
  "\";\"",
  "GOAL_SEP_ALT",
  "PLAYER",
  "GOAL_COUNT",
  "GOAL_MINUTE_SEP",
  "GOAL_MINUTE",
  "GOALS_ALT",
  "GOAL_TYPE",
  "GOALS_COMPAT",
  "MINUTE",
  "PROP_ATTENDANCE",
  "PROP_NUM",
  "PROP_END",
  "PROP_REFEREE",
  "PROP_NAME",
  "ENCLOSED_NAME",
  "ATTENDANCE",
  "PROP_YELLOWCARDS",
  "PROP_REDCARDS",
  "PROP_PENALTIES",
  "PROP",
  "COACH",
  "INLINE_CAPTAIN",
  "\"(\"",
  "\")\"",
  "INLINE_YELLOW",
  "INLINE_YELLOW_RED",
  "INLINE_RED",
  "$start",
  "document",
  "elements",
  "element",
  "heading",
  "group_def",
  "round_def",
  "round_outline",
  "date_header",
  "match_line_with_header",
  "match_line",
  "date_header_legs",
  "match_line_legs",
  "note_line",
  "nota_bene",
  "goal_lines",
  "goal_lines_alt",
  "goal_lines_compat",
  "lineup_lines",
  "yellowcard_lines",
  "redcard_lines",
  "penalties_lines",
  "referee_line",
  "attendance_line",
  "opt_blank_lines",
  "blank_lines",
  "group_def_sep",
  "team_values",
  "round_def_sep",
  "round_date_opts",
  "date",
  "datetime",
  "time",
  "date_datetime",
  "opt_date",
  "geo",
  "geo_names",
  "opt_geo",
  "match_sep",
  "match_fixture",
  "match_fixture_not_played",
  "match_fixture_postponed",
  "SCORE_FULL_OR_FULLER",
  "match_result",
  "match_fixture_base",
  "match_result_base",
  "ord",
  "opt_ord",
  "match_header",
  "match_line_header",
  "match",
  "more_match_header_opts",
  "opt_inline_attendance",
  "inline_attendance",
  "opt_inline_note",
  "match_opts",
  "more_match_opts",
  "match_bye",
  "match_walkover",
  "goal_lines_body",
  "opt_inline_round_n_geo",
  "goals",
  "goals_sep",
  "opt_goal_sep",
  "goal",
  "goal_minutes",
  "opt_goal_minute_sep",
  "goal_minute",
  "goals_alt",
  "goal_alt",
  "goals_compat",
  "goal_compat",
  "referees",
  "attendance_opt",
  "referee",
  "card_body",
  "player_w_minute",
  "card_sep",
  "penalties_body",
  "penalty_sep",
  "penalty",
  "lineup",
  "coach_opt",
  "lineup_sep",
  "lineup_name",
  "lineup_name_plus_cards_opts",
  "lineup_sub_opts",
  "lineup_captain_opt",
  "lineup_cards_opts",
  "cards" ]
Ractor.make_shareable(Racc_token_to_s_table) if defined?(Ractor)

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'parser.y', 9)
  def _reduce_1(val, _values, result)
     result = []
    result
  end
.,.,

# reduce 2 omitted

# reduce 3 omitted

# reduce 4 omitted

# reduce 5 omitted

# reduce 6 omitted

# reduce 7 omitted

# reduce 8 omitted

# reduce 9 omitted

# reduce 10 omitted

# reduce 11 omitted

# reduce 12 omitted

# reduce 13 omitted

# reduce 14 omitted

# reduce 15 omitted

# reduce 16 omitted

# reduce 17 omitted

# reduce 18 omitted

# reduce 19 omitted

# reduce 20 omitted

# reduce 21 omitted

# reduce 22 omitted

# reduce 23 omitted

# reduce 24 omitted

module_eval(<<'.,.,', 'parser.y', 50)
  def _reduce_25(val, _values, result)
                   ## _trace( "REDUCE BLANK" )
               @tree << BlankLine.new

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 56)
  def _reduce_26(val, _values, result)
     puts "!! skipping invalid content (trying to recover from parse error):"
                pp val[0]
                ##  note - do NOT report recover errors for now
                ##  @errors << "parser error (recover) - skipping #{val[0].pretty_inspect}"

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 67)
  def _reduce_27(val, _values, result)
      @tree << Heading1.new( text: val[0].as_str)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 68)
  def _reduce_28(val, _values, result)
      @tree << Heading2.new( text: val[0].as_str)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 69)
  def _reduce_29(val, _values, result)
      @tree << Heading3.new( text: val[0].as_str)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 73)
  def _reduce_30(val, _values, result)
     @tree << NoteLine.new( text: val[0].as_str)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 76)
  def _reduce_31(val, _values, result)
     @tree << NotaBene.new( text: val[0].as_str)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 84)
  def _reduce_32(val, _values, result)
    
    result
  end
.,.,

# reduce 33 omitted

# reduce 34 omitted

# reduce 35 omitted

# reduce 36 omitted

# reduce 37 omitted

module_eval(<<'.,.,', 'parser.y', 106)
  def _reduce_38(val, _values, result)
                          @tree << GroupDef.new( name:  val[0].as_str,
                                             teams: val[2] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 111)
  def _reduce_39(val, _values, result)
     result = [val[0].as_str]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 112)
  def _reduce_40(val, _values, result)
     result.push( val[1].as_str )
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 113)
  def _reduce_41(val, _values, result)
     result.push( val[2].as_str )
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 123)
  def _reduce_42(val, _values, result)
                                      @tree << RoundOutline.new( **val[0].as_hash )

    result
  end
.,.,

# reduce 43 omitted

# reduce 44 omitted

module_eval(<<'.,.,', 'parser.y', 138)
  def _reduce_45(val, _values, result)
                          kwargs = { name: val[0].as_str }.merge( val[2] )
                      @tree << RoundDef.new( **kwargs )

                      ## auto-add RoundOutline here - why? why not?
                      ##    or handle "implicit" round_outline
                      ##     in tree walker?
                      @tree << RoundOutline.new( outline: val[0].as_str, level: 1 )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 151)
  def _reduce_46(val, _values, result)
     result = { date: val[0].as_hash }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 152)
  def _reduce_47(val, _values, result)
     result = { duration: val[0].as_hash }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 162)
  def _reduce_48(val, _values, result)
     result = { date: val[0].as_hash }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 163)
  def _reduce_49(val, _values, result)
     result = { year: val[0].as_int }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 168)
  def _reduce_50(val, _values, result)
     result = val[0].as_hash
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 171)
  def _reduce_51(val, _values, result)
     result = val[0].as_hash
    result
  end
.,.,

# reduce 52 omitted

# reduce 53 omitted

module_eval(<<'.,.,', 'parser.y', 184)
  def _reduce_54(val, _values, result)
      result = {}
    result
  end
.,.,

# reduce 55 omitted

# reduce 56 omitted

module_eval(<<'.,.,', 'parser.y', 197)
  def _reduce_57(val, _values, result)
                         @tree <<  DateHeader.new( **val[0] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 204)
  def _reduce_58(val, _values, result)
                         @tree <<  DateHeaderLegs.new( **val[0].as_hash )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 215)
  def _reduce_59(val, _values, result)
     result = { geo: val[1] }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 218)
  def _reduce_60(val, _values, result)
      result = [val[0].as_str]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 219)
  def _reduce_61(val, _values, result)
      result.push( val[2].as_str )
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 223)
  def _reduce_62(val, _values, result)
     result = {}
    result
  end
.,.,

# reduce 63 omitted

# reduce 64 omitted

# reduce 65 omitted

module_eval(<<'.,.,', 'parser.y', 245)
  def _reduce_66(val, _values, result)
                                   _trace( "RECUDE match_fixture" )
                               result = { team1: val[0].as_str,
                                          team2: val[2].as_str }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 257)
  def _reduce_67(val, _values, result)
                                   ## note - auto-add (match) status canceled - why? why not?
                               ##   A n/p B   short (inline) form of =>
                               ##   A v B [canceled]

                               result = { team1: val[0].as_str,
                                          team2: val[2].as_str,
                                          status_inline: 'canceled' }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 267)
  def _reduce_68(val, _values, result)
                                   result = { team1: val[0].as_str,
                                          team2: val[2].as_str,
                                          status_inline: 'canceled' }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 274)
  def _reduce_69(val, _values, result)
                                   result = { team1: val[0].as_str,
                                          team2: val[2].as_str,
                                          status_inline: 'postponed' }

    result
  end
.,.,

# reduce 70 omitted

# reduce 71 omitted

module_eval(<<'.,.,', 'parser.y', 292)
  def _reduce_72(val, _values, result)
                               _trace( "REDUCE => match_result : TEAM SCORE TEAM" )

                          ## note - use/keep generic score (as array!! NOT hash!!!)
                          ##      - as array e.g. [1,1] !!
                           result = { team1: val[0].as_str, team2: val[2].as_str,
                                      score: val[1].as_ary
                                    }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 302)
  def _reduce_73(val, _values, result)
                               result = { team1: val[0].as_str, team2: val[2].as_str,
                                      score: val[1].as_ary,
                                      status_inline: 'awarded'
                                    }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 309)
  def _reduce_74(val, _values, result)
                               result = { team1: val[0].as_str, team2: val[2].as_str,
                                      score: val[1].as_ary,
                                      status_inline: 'abandoned'
                                    }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 316)
  def _reduce_75(val, _values, result)
                                _trace( "REDUCE => match_result : TEAM SCORE TEAM SCORE_FULLER_MORE" )
                            score =  if val[3].as_hash[:score] &&
                                        val[3].as_hash[:score]=='et'   ## check aet flag present?
                                         val[3].as_hash.delete( :score )  ## note - remove/delete  flag
                                           { et: val[1].as_ary }
                                     elsif val[3].as_hash[:score] &&
                                           val[3].as_hash[:score]=='ht' ## check ht flag present?
                                         val[3].as_hash.delete( :score ) ## note - remove/delete flag
                                           { ht: val[1].as_ary }
                                     elsif val[3].as_hash[:score] &&
                                           val[3].as_hash[:score]=='ft'  ## check ft flag present?
                                         val[3].as_hash.delete( :score )  ## note - remove/delete flag
                                           { ft: val[1].as_ary }
                                     else   ## assume full-time (ft)
                                            { ft: val[1].as_ary }
                                     end

                           result = {  team1: val[0].as_str,
                                      team2: val[2].as_str,
                                      score: score.merge( val[3].as_hash )
                                    }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 340)
  def _reduce_76(val, _values, result)
                               result = { team1: val[0].as_str,
                                      team2: val[2].as_str,
                                      score: val[1].as_hash
                                    }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 354)
  def _reduce_77(val, _values, result)
                              _trace( "REDUCE  => match_result : match_fixture SCORE" )
                          ## note - use/keep generic score (as array!! NOT hash!!!)
                          ##      - as array e.g. [1,1] !!
                          result = { score: val[1].as_ary }.merge( val[0] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 361)
  def _reduce_78(val, _values, result)
                              _trace( "REDUCE  => match_result : match_fixture SCORE_FULL_OR_FULLER" )
                          result = { score: val[1].as_hash }.merge( val[0] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 373)
  def _reduce_79(val, _values, result)
                               result = { team1: val[0].as_str, team2: val[2].as_str,
                                      status_inline: 'awarded'
                                    }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 379)
  def _reduce_80(val, _values, result)
                               result = { team1: val[0].as_str, team2: val[2].as_str,
                                      status_inline: 'abandoned'
                                    }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 385)
  def _reduce_81(val, _values, result)
                               result = { team1: val[0].as_str, team2: val[2].as_str,
                                      status_inline: 'annulled'
                                    }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 391)
  def _reduce_82(val, _values, result)
                               result = { team1: val[0].as_str, team2: val[2].as_str,
                                      status_inline: 'suspended'
                                    }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 405)
  def _reduce_83(val, _values, result)
     result = { team1: '_', team2: val[1].as_str }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 406)
  def _reduce_84(val, _values, result)
     result = { team1: val[1].as_str, team2: '_' }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 407)
  def _reduce_85(val, _values, result)
     result = { team1: '_', team2: val[1].as_str,
                                                       neutral: true }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 414)
  def _reduce_86(val, _values, result)
                              _trace( "REDUCE  => match_result_base : match_fixture_base SCORE" )
                          ## note - use/keep generic score (as array!! NOT hash!!!)
                          ##      - as array e.g. [1,1] !!
                          result = { score: val[1].as_ary }.merge( val[0] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 421)
  def _reduce_87(val, _values, result)
                              _trace( "REDUCE  => match_result_base : match_fixture_base SCORE_FULL_OR_FULLER" )
                          result = { score: val[1].as_hash }.merge( val[0] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 431)
  def _reduce_88(val, _values, result)
      result = { num: val[0].as_int }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 434)
  def _reduce_89(val, _values, result)
      result = {}
    result
  end
.,.,

# reduce 90 omitted

module_eval(<<'.,.,', 'parser.y', 448)
  def _reduce_91(val, _values, result)
                         ## note - header flag (header: true)
                     ##    used downstream for scope / e.g. DateHeader merge/inheritance or such
                      kwargs = { header: true }.merge( val[0], val[2] )
                      @tree << MatchLine.new( **kwargs )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 457)
  def _reduce_92(val, _values, result)
                          result = {}.merge( val[0], val[1], val[2] )

    result
  end
.,.,

# reduce 93 omitted

module_eval(<<'.,.,', 'parser.y', 475)
  def _reduce_94(val, _values, result)
                          result = val[0].as_hash

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 477)
  def _reduce_95(val, _values, result)
     result = { note: val[0].as_str }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 478)
  def _reduce_96(val, _values, result)
     result = {}
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 489)
  def _reduce_97(val, _values, result)
                          result = {}.merge( val[0], val[1], val[2] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 493)
  def _reduce_98(val, _values, result)
                          result = {}.merge( val[0], val[1] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 504)
  def _reduce_99(val, _values, result)
                           result = { att: val[0].as_hash[:value] }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 509)
  def _reduce_100(val, _values, result)
                           result = { att: val[1].as_hash[:value] }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 513)
  def _reduce_101(val, _values, result)
      result = {}
    result
  end
.,.,

# reduce 102 omitted

module_eval(<<'.,.,', 'parser.y', 520)
  def _reduce_103(val, _values, result)
      result = {}
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 521)
  def _reduce_104(val, _values, result)
      result = { note: val[0].as_str }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 532)
  def _reduce_105(val, _values, result)
                           kwargs = {}.merge( val[0], val[1], val[2] )
                       @tree << MatchLine.new( **kwargs )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 537)
  def _reduce_106(val, _values, result)
                           kwargs = {}.merge( val[0], val[1])
                       @tree << MatchLine.new( **kwargs )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 542)
  def _reduce_107(val, _values, result)
                           kwargs = {}.merge( val[0], val[1] )
                       @tree << MatchLine.new( **kwargs )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 547)
  def _reduce_108(val, _values, result)
                           kwargs = {}.merge( val[0] )
                       @tree << MatchLine.new( **kwargs )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 553)
  def _reduce_109(val, _values, result)
                             kwargs = {}.merge( val[0], val[1] )
                         @tree << MatchLineBye.new( **kwargs )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 558)
  def _reduce_110(val, _values, result)
                             kwargs = {}.merge( val[0], val[1] )
                         @tree << MatchLineWalkover.new( **kwargs )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 570)
  def _reduce_111(val, _values, result)
                          kwargs = {}.merge( val[0] )
                      @tree << MatchLine.new( **kwargs )

                      kwargs = val[2]
                      @tree << GoalLine.new( **kwargs )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 582)
  def _reduce_112(val, _values, result)
     result = {}
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 584)
  def _reduce_113(val, _values, result)
                                       _trace( "REDUCE => INLINE_ROUND  opt_geo" )
                                    result = { round_inline: val[0].as_str }.merge( val[1] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 595)
  def _reduce_114(val, _values, result)
                                         result = {}.merge( val[0], val[1], val[2] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 598)
  def _reduce_115(val, _values, result)
                                         result = {}.merge( val[0], val[1] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 601)
  def _reduce_116(val, _values, result)
                                         result = {}.merge( val[0], val[1] )

    result
  end
.,.,

# reduce 117 omitted

module_eval(<<'.,.,', 'parser.y', 616)
  def _reduce_118(val, _values, result)
                          result = val[0].as_hash

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 620)
  def _reduce_119(val, _values, result)
                         result = {}.merge( val[0].as_hash, val[1], val[2] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 624)
  def _reduce_120(val, _values, result)
                       result = {}.merge( val[0], val[1], val[2] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 626)
  def _reduce_121(val, _values, result)
     result = { note: val[0].as_str }
    result
  end
.,.,

# reduce 122 omitted

# reduce 123 omitted

# reduce 124 omitted

# reduce 125 omitted

# reduce 126 omitted

# reduce 127 omitted

module_eval(<<'.,.,', 'parser.y', 651)
  def _reduce_128(val, _values, result)
                          result = { team: val[0].as_str }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 660)
  def _reduce_129(val, _values, result)
                          result = { team1: val[0].as_str,
                                 team2: val[2].as_str }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 678)
  def _reduce_130(val, _values, result)
                          kwargs = { score: val[1].as_hash }.merge( val[0] )
                      @tree << MatchLineLegs.new( **kwargs )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 719)
  def _reduce_131(val, _values, result)
                             @tree << GoalLine.new( **val[1] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 723)
  def _reduce_132(val, _values, result)
      result = { goals1: val[0],
                                                              goals2: [] }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 726)
  def _reduce_133(val, _values, result)
      result = { goals1: [],
                                                              goals2: val[1] }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 729)
  def _reduce_134(val, _values, result)
      result = { goals1: val[0],
                                                              goals2: val[2] }

    result
  end
.,.,

# reduce 135 omitted

# reduce 136 omitted

# reduce 137 omitted

# reduce 138 omitted

module_eval(<<'.,.,', 'parser.y', 740)
  def _reduce_139(val, _values, result)
    
    result
  end
.,.,

# reduce 140 omitted

# reduce 141 omitted

# reduce 142 omitted

module_eval(<<'.,.,', 'parser.y', 745)
  def _reduce_143(val, _values, result)
     result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 746)
  def _reduce_144(val, _values, result)
     result.push( val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 754)
  def _reduce_145(val, _values, result)
                           result = Goal.new( player:  val[0].as_str,
                                          minutes: val[1] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 759)
  def _reduce_146(val, _values, result)
                            ### todo/check:
                        ##    auto convert/expand
                        ##    count to minutes - why? why not?
                        ##  todo/fix - pass in empty minutes ary [] - why? why not?
                        result = Goal.new( player: val[0].as_str,
                                           count:  val[1].as_hash )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 768)
  def _reduce_147(val, _values, result)
                            result = Goal.new( player: val[0].as_str,
                                           minutes: [] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 775)
  def _reduce_148(val, _values, result)
    
    result
  end
.,.,

# reduce 149 omitted

module_eval(<<'.,.,', 'parser.y', 778)
  def _reduce_150(val, _values, result)
      result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 779)
  def _reduce_151(val, _values, result)
      result.push( val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 783)
  def _reduce_152(val, _values, result)
                                 result = GoalMinute.new( **val[0].as_hash )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 800)
  def _reduce_153(val, _values, result)
                                 @tree << GoalLineAlt.new( goals: val[1] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 804)
  def _reduce_154(val, _values, result)
     result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 807)
  def _reduce_155(val, _values, result)
     result.push( val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 813)
  def _reduce_156(val, _values, result)
                               result = GoalAlt.new( score:   val[0].as_ary,
                                                 player:  val[1].as_str )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 818)
  def _reduce_157(val, _values, result)
                               goal_minute = GoalMinute.new( **val[2].as_hash )

                           result = GoalAlt.new( score:     val[0].as_ary,
                                                 player:    val[1].as_str,
                                                 minute:    goal_minute.to_minute,
                                                 goal_type: goal_minute.to_goal_type )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 827)
  def _reduce_158(val, _values, result)
                               result = GoalAlt.new( score:     val[0].as_ary,
                                                 player:    val[1].as_str,
                                                 goal_type: GoalType.new( **val[2].as_hash ))

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 837)
  def _reduce_159(val, _values, result)
                               result = GoalAlt.new( player:  val[0].as_str,
                                                 score:   val[1].as_ary )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 842)
  def _reduce_160(val, _values, result)
                               goal_minute = GoalMinute.new( **val[1].as_hash )

                           result = GoalAlt.new( player:    val[0].as_str,
                                                 minute:    goal_minute.to_minute,
                                                 goal_type: goal_minute.to_goal_type,
                                                 score:     val[2].as_ary )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 851)
  def _reduce_161(val, _values, result)
                               result = GoalAlt.new( player:    val[0].as_str,
                                                 goal_type: GoalType.new( **val[1].as_hash ),
                                                 score:     val[2].as_ary )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 863)
  def _reduce_162(val, _values, result)
                                 @tree << GoalLineCompat.new( goals: val[1] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 867)
  def _reduce_163(val, _values, result)
     result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 869)
  def _reduce_164(val, _values, result)
     result.push( val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 890)
  def _reduce_165(val, _values, result)
                               result = GoalCompat.new( minute:  Minute.new(**val[0].as_hash),
                                                    player:  val[1].as_str,
                                                    score:  val[2].as_ary )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 896)
  def _reduce_166(val, _values, result)
                               result = GoalCompat.new( minute: Minute.new(**val[0].as_hash),
                                                    player: val[1].as_str,
                                                    goal_type: GoalType.new( **val[2].as_hash ),
                                                    score:  val[3].as_ary )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 903)
  def _reduce_167(val, _values, result)
                               result = GoalCompat.new( minute:  Minute.new(**val[0].as_hash),
                                                    score:  val[1].as_ary,
                                                    player:  val[2].as_str )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 909)
  def _reduce_168(val, _values, result)
                               result = GoalCompat.new( minute: Minute.new(**val[0].as_hash),
                                                    score:  val[1].as_ary,
                                                    player: val[2].as_str,
                                                    goal_type: GoalType.new( **val[3].as_hash ))

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 930)
  def _reduce_169(val, _values, result)
                                     @tree << AttendanceLine.new( att: val[1].as_int )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 940)
  def _reduce_170(val, _values, result)
                                   @tree << RefereeLine.new( referees: val[1] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 943)
  def _reduce_171(val, _values, result)
      result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 944)
  def _reduce_172(val, _values, result)
      result.push( val[2] )
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 947)
  def _reduce_173(val, _values, result)
      result = Referee.new( name: val[0].as_str )
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 949)
  def _reduce_174(val, _values, result)
      result = Referee.new( name: val[0].as_str, country: val[1].as_str )
    result
  end
.,.,

# reduce 175 omitted

module_eval(<<'.,.,', 'parser.y', 955)
  def _reduce_176(val, _values, result)
                                     @tree << AttendanceLine.new( att: val[2].as_int )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 966)
  def _reduce_177(val, _values, result)
                                   @tree << CardsLine.new( type: 'Y', bookings: val[1] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 970)
  def _reduce_178(val, _values, result)
                                   @tree << CardsLine.new( type: 'R', bookings: val[1] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 977)
  def _reduce_179(val, _values, result)
       result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 979)
  def _reduce_180(val, _values, result)
      result.push( val[2] )
    result
  end
.,.,

# reduce 181 omitted

# reduce 182 omitted

# reduce 183 omitted

module_eval(<<'.,.,', 'parser.y', 986)
  def _reduce_184(val, _values, result)
     result = Booking.new( name: val[0].as_str )
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 988)
  def _reduce_185(val, _values, result)
     result = Booking.new( name:   val[0].as_str,
                                                      minute: val[1].as_hash )
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 995)
  def _reduce_186(val, _values, result)
                                   @tree << PenaltiesLine.new( penalties: val[1] )

    result
  end
.,.,

# reduce 187 omitted

# reduce 188 omitted

# reduce 189 omitted

# reduce 190 omitted

module_eval(<<'.,.,', 'parser.y', 1005)
  def _reduce_191(val, _values, result)
      result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1006)
  def _reduce_192(val, _values, result)
      result.push( val[2] )
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1012)
  def _reduce_193(val, _values, result)
                                     result = Penalty.new( score: val[0].as_ary,
                                                       name:  val[1].as_str )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1017)
  def _reduce_194(val, _values, result)
                                     result = Penalty.new( score: val[0].as_ary,
                                                       name:  val[1].as_str,
                                                       note:  val[2].as_str )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1023)
  def _reduce_195(val, _values, result)
                                     result = Penalty.new( name: val[0].as_str )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1027)
  def _reduce_196(val, _values, result)
                                     result = Penalty.new( name: val[0].as_str,
                                                       note: val[1].as_str )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1039)
  def _reduce_197(val, _values, result)
                              kwargs = { team:    val[0].as_str,
                                     lineup:  val[1]  }.merge( val[2] )
                          @tree << LineupLine.new( **kwargs )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1045)
  def _reduce_198(val, _values, result)
     result = {}
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1047)
  def _reduce_199(val, _values, result)
      result = { coach: val[2].as_str }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1049)
  def _reduce_200(val, _values, result)
      result = { coach: val[3].as_str }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1051)
  def _reduce_201(val, _values, result)
      result = { coach: val[2].as_str }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1053)
  def _reduce_202(val, _values, result)
      result = { coach: val[3].as_str }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1057)
  def _reduce_203(val, _values, result)
     result = ','
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1058)
  def _reduce_204(val, _values, result)
     result = ','
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1059)
  def _reduce_205(val, _values, result)
     result = '-'
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1060)
  def _reduce_206(val, _values, result)
     result = '-'
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1064)
  def _reduce_207(val, _values, result)
     result = [[val[0]]]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1067)
  def _reduce_208(val, _values, result)
                           ## note - if lineup_sep is dash (-) start a new sub array!!
                       if val[1] == '-'
                          result << [val[2]]
                       else
                          result[-1] << val[2]
                       end

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1078)
  def _reduce_209(val, _values, result)
                                  kwargs = {}.merge(val[0] ).merge( val[1])
                              result = Lineup.new( **kwargs )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1085)
  def _reduce_210(val, _values, result)
                                            result = { name: val[0].as_str }.merge( val[1]).merge( val[2] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1089)
  def _reduce_211(val, _values, result)
     result = {}
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1090)
  def _reduce_212(val, _values, result)
     result = { captain: true }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1092)
  def _reduce_213(val, _values, result)
     result = {}
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1093)
  def _reduce_214(val, _values, result)
     result = { cards: val[0] }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1111)
  def _reduce_215(val, _values, result)
     result = {}
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1114)
  def _reduce_216(val, _values, result)
                                  kwargs = {}.merge( val[1] ).merge( val[3] )
                              sub    = Sub.new( sub:    Lineup.new( **kwargs ),
                                                minute: Minute.new(val[2].as_hash)
                                              )
                              result = { sub: sub }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1122)
  def _reduce_217(val, _values, result)
                                  sub = Sub.new( sub: val[1] )
                              result = { sub: sub }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1129)
  def _reduce_218(val, _values, result)
                                  sub = Sub.new( sub:    val[2],
                                             minute: Minute.new(val[1].as_hash)
                                            )
                              result = { sub: sub }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1139)
  def _reduce_219(val, _values, result)
     result = [{ card: 'YELLOW' }.merge( val[0].as_hash )]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1141)
  def _reduce_220(val, _values, result)
     result = [{ card: 'YELLOW' }.merge( val[0].as_hash ),
                                 { card: 'YELLOW_RED' }.merge( val[1].as_hash)]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1144)
  def _reduce_221(val, _values, result)
     result = [{ card: 'YELLOW' }.merge( val[0].as_hash ),
                                { card: 'RED' }.merge( val[1].as_hash)]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1147)
  def _reduce_222(val, _values, result)
      result = [{ card: 'RED' }.merge( val[0].as_hash)]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1149)
  def _reduce_223(val, _values, result)
      result = [{ card: 'YELLOW_RED' }.merge( val[0].as_hash)]
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

end   # class RaccMatchParser
