#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.8.1
# from Racc grammar file "parser.y".
#

require 'racc/parser.rb'
class RaccMatchParser < Racc::Parser
##### State transition tables begin ###

racc_action_table = [
    28,    21,    29,   280,    30,    31,    32,    33,    34,    35,
    36,    37,    38,   251,   274,    39,    76,   341,    40,    41,
    42,   280,    43,    44,    45,    48,   229,   250,   135,   188,
   139,   -77,    60,    61,    62,    63,    86,    64,    68,   251,
    73,    74,    75,    88,   352,   324,   137,    89,   281,   251,
   251,   351,   373,   250,   189,   112,   113,   136,   230,   275,
    77,   140,   325,   250,   250,   346,   281,   350,    78,   280,
    79,   272,    80,   366,  -160,    81,   138,   258,   278,    82,
    83,    84,    85,    28,    21,    29,    90,    30,    31,    32,
    33,    34,    35,    36,    37,    38,    91,   340,    39,    76,
  -160,    40,    41,    42,   288,    43,    44,    45,    48,   248,
   249,  -160,   125,   251,   281,    60,    61,    62,    63,   128,
    64,    68,   217,    73,    74,    75,   284,   250,   178,   128,
   365,   188,   289,   261,   173,   126,   363,   175,   115,    92,
   179,   264,   123,    77,    93,   126,   123,    68,   262,   286,
   263,    78,   255,    79,   257,    80,   189,    68,    81,   116,
   117,   118,    82,    83,    84,    85,    73,    74,    75,    94,
    73,    74,    75,   155,   156,   157,   158,   160,   161,   162,
   170,   293,   163,   164,   165,   166,   167,   168,   169,    42,
    95,    43,    44,    45,   294,   295,   157,   158,   160,   161,
   162,   170,   192,   163,   164,   165,   166,   167,   168,   169,
   192,   267,   178,   194,   195,   192,   173,   112,   113,   175,
    96,   194,   195,   266,   179,    97,   194,   195,    68,    60,
    61,    62,    63,   101,    64,   116,   117,   150,   116,   117,
   118,   318,   105,   319,    98,    99,   103,   102,   204,   205,
   112,   113,   112,   113,   314,  -169,   106,   108,   129,   129,
   132,   133,   134,   141,    68,   149,   152,   153,   154,   182,
   183,   185,   199,   200,   202,   206,   213,   214,   215,   218,
    68,   221,   222,   225,   226,   227,   228,    68,   232,   233,
   234,   235,   236,   237,   238,   239,   240,   241,   242,   243,
   244,   245,   246,   175,   260,   268,   270,   271,   276,   277,
   282,   283,   292,   296,   298,   299,   129,   302,   303,   304,
   305,   306,   307,   308,   175,   310,   311,   312,   175,   316,
   320,   321,   322,   182,   326,   327,   328,   329,   330,   332,
   333,   334,   335,   192,   337,   338,   339,   199,   343,   344,
   346,   348,   353,   354,   257,   356,   357,   358,   359,   360,
   361,   362,   367,   368,   369,   292,   371,   199,   374,   346,
   376 ]

racc_action_check = [
     0,     0,     0,   347,     0,     0,     0,     0,     0,     0,
     0,     0,     0,   253,   186,     0,     0,   286,     0,     0,
     0,   190,     0,     0,     0,     0,   141,   253,    60,    82,
    62,   110,     0,     0,     0,     0,     1,     0,     0,   309,
     0,     0,     0,    29,   297,   266,    61,    30,   347,   176,
   172,   297,   370,   309,    82,   110,   110,    60,   141,   186,
     0,    62,   266,   176,   172,   370,   190,   297,     0,   196,
     0,   186,     0,   347,   253,     0,    61,   176,   190,     0,
     0,     0,     0,     2,     2,     2,    31,     2,     2,     2,
     2,     2,     2,     2,     2,     2,    32,   286,     2,     2,
   309,     2,     2,     2,   197,     2,     2,     2,     2,   172,
   172,   172,    53,   180,   196,     2,     2,     2,     2,    53,
     2,     2,   120,     2,     2,     2,   196,   180,    78,   120,
   346,   273,   197,   179,    77,    53,   346,    77,    51,    33,
    78,   180,    52,     2,    34,   120,   208,    53,   179,   197,
   179,     2,   175,     2,   175,     2,   273,   120,     2,    51,
    51,    51,     2,     2,     2,     2,    52,    52,    52,    35,
   208,   208,   208,    76,    76,    76,    76,    76,    76,    76,
    76,   201,    76,    76,    76,    76,    76,    76,    76,    65,
    36,    65,    65,    65,   201,   201,   123,   123,   123,   123,
   123,   123,    83,   123,   123,   123,   123,   123,   123,   123,
    84,   182,   259,    83,    83,   292,   132,    50,    50,   132,
    37,    84,    84,   182,   259,    38,   292,   292,    50,   109,
   109,   109,   109,    40,   109,    71,    71,    71,   122,   122,
   122,   260,    46,   260,    39,    39,    41,    41,   104,   104,
   127,   127,   219,   219,   254,   254,    48,    49,    54,    55,
    56,    58,    59,    63,    66,    68,    73,    74,    75,    79,
    80,    81,    85,    86,   100,   107,   111,   113,   115,   124,
   126,   130,   131,   134,   135,   137,   139,   145,   148,   156,
   159,   160,   161,   162,   163,   164,   165,   166,   167,   168,
   169,   170,   171,   173,   178,   183,   184,   185,   188,   189,
   192,   193,   199,   203,   211,   216,   220,   223,   225,   229,
   230,   232,   238,   246,   247,   248,   249,   250,   252,   258,
   262,   263,   264,   265,   267,   268,   269,   270,   272,   274,
   275,   276,   278,   279,   281,   284,   285,   287,   288,   289,
   290,   295,   302,   304,   315,   325,   326,   328,   329,   339,
   340,   341,   350,   351,   362,   363,   364,   365,   372,   373,
   375 ]

racc_action_pointer = [
    -1,    36,    82,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    39,
    43,    82,    92,   135,   140,   165,   186,   216,   221,   230,
   229,   232,   nil,   nil,   nil,   nil,   238,   nil,   252,   255,
   189,   108,   125,   108,   247,   248,   229,   nil,   257,   258,
    24,    42,    26,   226,   nil,   168,   225,   nil,   225,   nil,
   nil,   184,   nil,   249,   250,   251,   129,    72,    75,   197,
   196,   193,   -24,   124,   132,   194,   273,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   257,   nil,   nil,   nil,   227,   nil,   nil,   273,   nil,   196,
    27,   272,   nil,   249,   nil,   274,   nil,   nil,   nil,   nil,
   118,   nil,   187,   150,   275,   nil,   241,   222,   nil,   nil,
   277,   278,   154,   nil,   256,   251,   nil,   251,   nil,   251,
   nil,    22,   nil,   nil,   nil,   248,   nil,   nil,   270,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   272,   nil,   nil,   273,
   274,   275,   276,   277,   278,   279,   280,   281,   282,   283,
   284,   270,    46,   238,   nil,    86,    45,   nil,   239,    80,
   109,   nil,   158,   230,   243,   228,    -4,   nil,   230,   230,
     3,   nil,   238,   239,   nil,   nil,    51,    86,   nil,   225,
   nil,   177,   nil,   309,   nil,   nil,   nil,   nil,   129,   nil,
   nil,   310,   nil,   nil,   nil,   nil,   311,   nil,   nil,   224,
   305,   nil,   nil,   285,   nil,   314,   nil,   nil,   nil,   283,
   283,   nil,   281,   nil,   nil,   nil,   nil,   nil,   262,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   319,   259,   321,   322,
   323,   nil,   263,     9,   187,   nil,   nil,   nil,   325,   159,
   173,   nil,   277,   278,   328,   261,    -8,   269,   331,   261,
   260,   nil,   334,    78,   335,   336,   262,   nil,   338,   265,
   nil,   340,   nil,   nil,   341,   271,    13,   269,   344,   345,
   265,   nil,   137,   nil,   nil,   334,   nil,    40,   nil,   nil,
   nil,   nil,   348,   nil,   316,   nil,   nil,   nil,   nil,    35,
   nil,   nil,   nil,   nil,   nil,   286,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   302,   286,   nil,   353,   284,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   355,
   282,   277,   nil,   nil,   nil,   nil,    58,   -15,   nil,   nil,
   358,   359,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   286,   278,   280,   289,   nil,   nil,   nil,   nil,
   -20,   nil,   282,   284,   nil,   284,   nil ]

racc_action_default = [
    -1,  -238,    -2,    -3,    -5,    -6,    -7,    -8,    -9,   -10,
   -11,   -12,   -13,   -14,   -15,   -16,   -17,   -18,   -19,   -20,
   -21,   -22,   -23,   -24,   -25,   -26,   -27,   -28,   -29,  -238,
  -238,  -238,  -238,  -238,  -238,  -238,  -238,  -238,  -238,  -238,
  -238,  -238,   -52,   -53,   -54,   -55,   -56,   -57,  -238,   -63,
  -115,  -121,  -238,  -238,   -80,   -80,  -120,   -89,  -238,  -238,
  -238,  -238,  -238,  -238,  -106,   -58,  -115,  -110,  -238,  -122,
  -123,  -124,  -125,  -238,  -238,  -238,  -238,  -238,  -238,  -238,
  -238,  -238,  -238,  -238,  -238,  -238,  -238,    -4,   -30,   -31,
   -32,   -33,   -34,   -35,   -36,   -37,   -38,   -39,   -40,   -41,
  -238,   -46,   -47,   -48,  -238,   -61,   -62,   -64,   -65,  -104,
  -116,  -238,   -75,  -238,  -108,  -238,  -137,  -138,  -148,  -149,
  -238,  -120,  -121,  -238,  -238,   -85,  -111,   -77,  -114,   -81,
  -238,  -238,  -238,   -90,   -92,  -238,   -98,  -238,   -99,  -238,
  -100,  -238,   -56,   -59,   -60,  -115,  -109,  -116,  -117,  -118,
  -150,  -151,  -126,  -127,  -128,  -129,  -238,  -131,  -132,  -238,
  -238,  -238,  -238,  -238,  -238,  -238,  -238,  -238,  -238,  -238,
  -238,  -238,  -153,  -238,  -164,  -168,  -160,  -175,  -238,  -238,
  -160,  -184,  -238,  -238,  -192,  -194,  -238,  -197,  -238,  -205,
  -238,  -209,  -214,  -234,  -236,  -237,  -238,  -217,  -220,  -227,
   377,  -238,   -43,  -238,   -50,   -51,   -66,   -67,  -238,   -69,
  -105,  -238,   -78,   -74,   -76,   -79,  -238,   -83,   -84,   -77,
   -80,   -86,   -87,  -238,   -91,  -238,   -94,   -95,   -96,  -238,
  -238,  -107,  -238,  -130,  -133,  -134,  -135,  -136,  -139,  -140,
  -141,  -142,  -143,  -144,  -145,  -147,  -238,  -238,  -156,  -158,
  -161,  -163,  -238,  -154,  -166,  -167,  -171,  -173,  -238,  -238,
  -177,  -180,  -238,  -238,  -238,  -238,  -238,  -238,  -238,  -238,
  -238,  -195,  -238,  -238,  -199,  -201,  -203,  -206,  -238,  -238,
  -211,  -212,  -215,  -235,  -238,  -238,  -238,  -238,  -222,  -224,
  -229,  -228,  -238,   -42,   -44,  -238,   -49,  -238,   -73,   -82,
  -112,  -113,  -238,   -93,  -238,  -101,  -119,  -146,  -152,  -155,
  -157,  -159,  -162,  -165,  -170,  -238,  -174,  -176,  -178,  -179,
  -181,  -182,  -183,  -185,  -186,  -238,  -188,  -190,  -238,  -238,
  -196,  -198,  -200,  -202,  -204,  -207,  -210,  -213,  -208,  -238,
  -238,  -238,  -221,  -223,  -225,  -226,  -238,  -238,   -45,   -68,
  -238,  -238,   -72,   -88,   -97,  -172,  -187,  -189,  -191,  -193,
  -216,  -218,  -238,  -227,  -238,  -238,  -233,   -70,   -71,  -219,
  -229,  -231,  -238,  -229,  -232,  -238,  -230 ]

racc_goto_table = [
   198,   190,   196,   187,   181,   177,   130,   131,   120,   290,
   122,   121,   256,   211,   253,   110,   114,   124,   127,   171,
   259,     3,     1,    87,   265,     2,   100,   201,   104,   203,
   220,   147,   146,   142,   144,   143,   145,   109,   107,   207,
   208,   349,   209,   111,   224,   210,   148,   151,   247,   313,
   254,   315,   176,   180,   184,   269,   186,   273,   336,   197,
   285,   287,   375,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   223,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   216,   127,   nil,   nil,   309,   nil,
   nil,   219,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   147,   231,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   300,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   355,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   297,   nil,   122,   121,   nil,   nil,
   nil,   nil,   301,   370,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   317,   nil,   nil,   nil,
   323,   nil,   nil,   nil,   331,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   342,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   347,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   364,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   372 ]

racc_goto_check = [
    89,    84,    84,    82,    78,    76,    48,    48,    41,    91,
    47,    53,    74,    45,    68,    44,    60,    50,    44,    54,
    70,     3,     1,     3,    70,     2,    27,    28,    29,    30,
    45,    44,    60,    31,    33,    34,    35,    36,    37,    39,
    40,    42,    43,    46,    57,    59,    61,    67,    69,    71,
    72,    73,    75,    77,    79,    80,    81,    83,    85,    87,
    88,    90,    92,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,    54,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,    50,    44,   nil,   nil,    68,   nil,
   nil,    44,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
    44,    60,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    45,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    74,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,    41,   nil,    47,    53,   nil,   nil,
   nil,   nil,    48,    91,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,    76,   nil,   nil,   nil,
    78,   nil,   nil,   nil,    82,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    89,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
    84,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,    89,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
    89 ]

racc_goto_pointer = [
   nil,    22,    25,    21,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   -13,   -73,   -13,
   -75,   -32,   nil,   -31,   -30,   -29,   -12,   -11,   nil,   -70,
   -69,   -44,  -256,   -67,   -35,   -97,    -7,   -42,   -48,   nil,
   -36,   nil,   nil,   -41,   -58,   nil,   nil,   -90,   nil,   -64,
   -34,   -22,   nil,   nil,   nil,   nil,   nil,   -24,  -159,  -124,
  -156,  -203,  -125,  -203,  -163,   -26,   -73,   -26,   -75,   -27,
  -129,   -26,   -79,  -129,   -82,  -221,   nil,   -26,  -137,   -85,
  -136,  -190,  -311,   nil,   nil ]

racc_goto_default = [
   nil,   nil,   nil,   nil,     4,     5,     6,     7,     8,     9,
    10,    11,    12,    13,    14,    15,    16,    17,    18,    19,
    20,    22,    23,    24,    25,    26,    27,   nil,   nil,   nil,
   nil,    46,    47,    66,    50,   nil,   nil,   nil,    49,   nil,
   nil,    53,   nil,    57,    67,   nil,   212,    51,   nil,    52,
   nil,    54,    55,    56,   nil,    58,    59,   nil,   nil,    65,
   nil,   nil,    69,    70,    71,    72,   159,   119,   172,   nil,
   252,   174,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   191,   279,   nil,   nil,   nil,
   nil,   nil,   345,   291,   193 ]

racc_reduce_table = [
  0, 0, :racc_error,
  0, 92, :_reduce_1,
  1, 92, :_reduce_none,
  1, 93, :_reduce_none,
  2, 93, :_reduce_none,
  1, 94, :_reduce_none,
  1, 94, :_reduce_none,
  1, 94, :_reduce_none,
  1, 94, :_reduce_none,
  1, 94, :_reduce_none,
  1, 94, :_reduce_none,
  1, 94, :_reduce_none,
  1, 94, :_reduce_none,
  1, 94, :_reduce_none,
  1, 94, :_reduce_none,
  1, 94, :_reduce_none,
  1, 94, :_reduce_none,
  1, 94, :_reduce_none,
  1, 94, :_reduce_none,
  1, 94, :_reduce_none,
  1, 94, :_reduce_none,
  1, 94, :_reduce_none,
  1, 94, :_reduce_22,
  1, 94, :_reduce_none,
  1, 94, :_reduce_none,
  1, 94, :_reduce_none,
  1, 94, :_reduce_none,
  1, 94, :_reduce_none,
  1, 94, :_reduce_none,
  1, 94, :_reduce_29,
  2, 95, :_reduce_30,
  2, 95, :_reduce_31,
  2, 95, :_reduce_32,
  2, 108, :_reduce_33,
  2, 108, :_reduce_34,
  2, 108, :_reduce_35,
  2, 108, :_reduce_36,
  2, 105, :_reduce_37,
  2, 106, :_reduce_38,
  2, 107, :_reduce_39,
  1, 118, :_reduce_none,
  1, 118, :_reduce_none,
  4, 96, :_reduce_42,
  1, 119, :_reduce_43,
  2, 119, :_reduce_44,
  3, 119, :_reduce_45,
  2, 98, :_reduce_46,
  1, 120, :_reduce_none,
  1, 120, :_reduce_none,
  4, 97, :_reduce_49,
  1, 121, :_reduce_50,
  1, 121, :_reduce_51,
  1, 122, :_reduce_52,
  1, 122, :_reduce_53,
  1, 123, :_reduce_54,
  1, 124, :_reduce_55,
  1, 125, :_reduce_none,
  1, 125, :_reduce_none,
  0, 126, :_reduce_58,
  1, 126, :_reduce_none,
  1, 126, :_reduce_none,
  2, 99, :_reduce_61,
  2, 103, :_reduce_62,
  0, 127, :_reduce_none,
  1, 127, :_reduce_none,
  1, 128, :_reduce_none,
  2, 128, :_reduce_none,
  3, 100, :_reduce_67,
  3, 130, :_reduce_68,
  1, 130, :_reduce_none,
  2, 133, :_reduce_70,
  2, 133, :_reduce_71,
  1, 133, :_reduce_72,
  4, 129, :_reduce_73,
  3, 129, :_reduce_74,
  1, 137, :_reduce_75,
  2, 137, :_reduce_76,
  0, 136, :_reduce_77,
  1, 136, :_reduce_none,
  3, 104, :_reduce_79,
  0, 139, :_reduce_80,
  1, 139, :_reduce_81,
  4, 101, :_reduce_82,
  3, 101, :_reduce_83,
  3, 101, :_reduce_84,
  2, 101, :_reduce_85,
  3, 101, :_reduce_86,
  3, 101, :_reduce_87,
  5, 101, :_reduce_88,
  1, 102, :_reduce_89,
  2, 134, :_reduce_90,
  3, 134, :_reduce_91,
  0, 148, :_reduce_92,
  2, 148, :_reduce_93,
  3, 147, :_reduce_94,
  3, 147, :_reduce_95,
  3, 147, :_reduce_96,
  5, 147, :_reduce_97,
  2, 146, :_reduce_98,
  2, 146, :_reduce_99,
  2, 146, :_reduce_100,
  4, 146, :_reduce_101,
  0, 149, :_reduce_none,
  1, 149, :_reduce_none,
  0, 131, :_reduce_104,
  1, 131, :_reduce_none,
  1, 150, :_reduce_106,
  3, 140, :_reduce_107,
  2, 140, :_reduce_108,
  2, 140, :_reduce_109,
  1, 140, :_reduce_none,
  1, 141, :_reduce_111,
  3, 141, :_reduce_112,
  3, 141, :_reduce_113,
  1, 141, :_reduce_114,
  0, 151, :_reduce_115,
  1, 151, :_reduce_none,
  2, 135, :_reduce_117,
  1, 152, :_reduce_118,
  3, 152, :_reduce_119,
  1, 132, :_reduce_none,
  1, 132, :_reduce_none,
  1, 132, :_reduce_none,
  1, 132, :_reduce_none,
  1, 132, :_reduce_none,
  1, 132, :_reduce_none,
  2, 155, :_reduce_126,
  2, 155, :_reduce_127,
  2, 155, :_reduce_128,
  2, 142, :_reduce_129,
  3, 143, :_reduce_130,
  1, 157, :_reduce_none,
  1, 157, :_reduce_none,
  3, 138, :_reduce_133,
  3, 153, :_reduce_134,
  3, 153, :_reduce_135,
  3, 154, :_reduce_136,
  1, 158, :_reduce_none,
  1, 158, :_reduce_none,
  3, 144, :_reduce_139,
  3, 144, :_reduce_140,
  3, 144, :_reduce_141,
  3, 144, :_reduce_142,
  3, 144, :_reduce_143,
  3, 144, :_reduce_144,
  3, 144, :_reduce_145,
  4, 144, :_reduce_146,
  3, 144, :_reduce_147,
  2, 144, :_reduce_148,
  2, 144, :_reduce_149,
  2, 156, :_reduce_150,
  2, 156, :_reduce_151,
  4, 109, :_reduce_152,
  1, 145, :_reduce_153,
  2, 145, :_reduce_154,
  3, 145, :_reduce_155,
  1, 160, :_reduce_none,
  2, 160, :_reduce_none,
  1, 160, :_reduce_none,
  2, 160, :_reduce_none,
  0, 161, :_reduce_160,
  1, 161, :_reduce_none,
  2, 161, :_reduce_none,
  1, 161, :_reduce_none,
  1, 159, :_reduce_164,
  3, 159, :_reduce_165,
  2, 162, :_reduce_166,
  2, 162, :_reduce_167,
  1, 162, :_reduce_168,
  0, 164, :_reduce_169,
  1, 164, :_reduce_none,
  1, 163, :_reduce_171,
  3, 163, :_reduce_172,
  1, 165, :_reduce_173,
  4, 110, :_reduce_174,
  1, 166, :_reduce_175,
  3, 166, :_reduce_176,
  2, 167, :_reduce_177,
  3, 167, :_reduce_178,
  3, 167, :_reduce_179,
  2, 167, :_reduce_180,
  3, 167, :_reduce_181,
  3, 167, :_reduce_182,
  4, 111, :_reduce_183,
  1, 168, :_reduce_184,
  3, 168, :_reduce_185,
  3, 169, :_reduce_186,
  4, 169, :_reduce_187,
  3, 169, :_reduce_188,
  4, 169, :_reduce_189,
  4, 117, :_reduce_190,
  5, 116, :_reduce_191,
  0, 171, :_reduce_none,
  3, 171, :_reduce_193,
  1, 170, :_reduce_194,
  2, 170, :_reduce_195,
  4, 115, :_reduce_196,
  1, 172, :_reduce_197,
  3, 172, :_reduce_198,
  1, 174, :_reduce_none,
  2, 174, :_reduce_none,
  1, 174, :_reduce_none,
  2, 174, :_reduce_none,
  2, 173, :_reduce_203,
  3, 173, :_reduce_204,
  1, 173, :_reduce_205,
  2, 173, :_reduce_206,
  4, 113, :_reduce_207,
  4, 114, :_reduce_208,
  1, 175, :_reduce_209,
  3, 175, :_reduce_210,
  1, 177, :_reduce_none,
  1, 177, :_reduce_none,
  2, 177, :_reduce_none,
  1, 176, :_reduce_214,
  2, 176, :_reduce_215,
  5, 112, :_reduce_216,
  0, 179, :_reduce_217,
  3, 179, :_reduce_218,
  4, 179, :_reduce_219,
  1, 178, :_reduce_220,
  3, 178, :_reduce_221,
  1, 181, :_reduce_none,
  2, 181, :_reduce_223,
  1, 181, :_reduce_none,
  2, 181, :_reduce_225,
  3, 180, :_reduce_226,
  0, 182, :_reduce_227,
  1, 182, :_reduce_228,
  0, 183, :_reduce_229,
  6, 183, :_reduce_230,
  3, 183, :_reduce_231,
  4, 183, :_reduce_232,
  3, 184, :_reduce_233,
  1, 175, :_reduce_234,
  2, 175, :_reduce_235,
  1, 185, :_reduce_none,
  1, 185, :_reduce_none ]

racc_reduce_n = 238

racc_shift_n = 377

racc_token_table = {
  false => 0,
  :error => 1,
  :BLANK => 2,
  :H1 => 3,
  :NEWLINE => 4,
  :H2 => 5,
  :H3 => 6,
  :TABLE_HEADING => 7,
  :TABLE_LINE => 8,
  :TABLE_NOTE => 9,
  :TABLE_DIVIDER => 10,
  :NOTE => 11,
  :NOTA_BENE => 12,
  :HRULER => 13,
  "|" => 14,
  ":" => 15,
  :GROUP_DEF => 16,
  :TEAM => 17,
  "," => 18,
  :ROUND_OUTLINE => 19,
  :ROUND_DEF => 20,
  :DATE => 21,
  :DURATION => 22,
  :YEAR => 23,
  :DATETIME => 24,
  :TIME => 25,
  :DATE_LEGS => 26,
  :STATUS => 27,
  :INLINE_ATTENDANCE => 28,
  :INLINE_ATTENDANCE_SEP => 29,
  :SCORE_LEGS => 30,
  :INLINE_GOALS => 31,
  :GOALS_END => 32,
  :TEAMALT => 33,
  :TEAMALT_PEN => 34,
  :TEAMALT_NUM => 35,
  :TTY_TEXT => 36,
  :TTY_NUM => 37,
  :ORD => 38,
  "@" => 39,
  :GEO => 40,
  :TEAM_HOME => 41,
  :TEAM_AWAY => 42,
  :TEAM_NEUTRAL => 43,
  :INLINE_BYE => 44,
  :INLINE_WO => 45,
  "-" => 46,
  :VS => 47,
  :INLINE_NP => 48,
  :INLINE_CANC => 49,
  :INLINE_PPD => 50,
  :SCORE_FULL => 51,
  :SCORE_FULLER => 52,
  :SCORE => 53,
  :SCORE_AWD => 54,
  :INLINE_AWD => 55,
  :SCORE_ABD => 56,
  :INLINE_ABD => 57,
  :INLINE_VOID => 58,
  :INLINE_SUSP => 59,
  :SCORE_FULLER_MORE => 60,
  :GOALS => 61,
  :GOALS_NONE => 62,
  ";" => 63,
  :GOAL_SEP_ALT => 64,
  :PLAYER => 65,
  :GOAL_COUNT => 66,
  :GOAL_MINUTE_SEP => 67,
  :GOAL_MINUTE => 68,
  :GOALS_ALT => 69,
  :GOAL_TYPE => 70,
  :GOALS_COMPAT => 71,
  :MINUTE => 72,
  :PROP_ATTENDANCE => 73,
  :PROP_NUM => 74,
  :PROP_END => 75,
  :PROP_REFEREE => 76,
  :ATTENDANCE => 77,
  :PROP_NAME => 78,
  :ENCLOSED_NAME => 79,
  :PROP_PENALTIES => 80,
  :PROP_YELLOWCARDS => 81,
  :PROP_REDCARDS => 82,
  :PROP => 83,
  :COACH => 84,
  "(" => 85,
  ")" => 86,
  "[" => 87,
  "]" => 88,
  :YELLOW_CARD => 89,
  :RED_CARD => 90 }

racc_nt_base = 91

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]
Ractor.make_shareable(Racc_arg) if defined?(Ractor)

Racc_token_to_s_table = [
  "$end",
  "error",
  "BLANK",
  "H1",
  "NEWLINE",
  "H2",
  "H3",
  "TABLE_HEADING",
  "TABLE_LINE",
  "TABLE_NOTE",
  "TABLE_DIVIDER",
  "NOTE",
  "NOTA_BENE",
  "HRULER",
  "\"|\"",
  "\":\"",
  "GROUP_DEF",
  "TEAM",
  "\",\"",
  "ROUND_OUTLINE",
  "ROUND_DEF",
  "DATE",
  "DURATION",
  "YEAR",
  "DATETIME",
  "TIME",
  "DATE_LEGS",
  "STATUS",
  "INLINE_ATTENDANCE",
  "INLINE_ATTENDANCE_SEP",
  "SCORE_LEGS",
  "INLINE_GOALS",
  "GOALS_END",
  "TEAMALT",
  "TEAMALT_PEN",
  "TEAMALT_NUM",
  "TTY_TEXT",
  "TTY_NUM",
  "ORD",
  "\"@\"",
  "GEO",
  "TEAM_HOME",
  "TEAM_AWAY",
  "TEAM_NEUTRAL",
  "INLINE_BYE",
  "INLINE_WO",
  "\"-\"",
  "VS",
  "INLINE_NP",
  "INLINE_CANC",
  "INLINE_PPD",
  "SCORE_FULL",
  "SCORE_FULLER",
  "SCORE",
  "SCORE_AWD",
  "INLINE_AWD",
  "SCORE_ABD",
  "INLINE_ABD",
  "INLINE_VOID",
  "INLINE_SUSP",
  "SCORE_FULLER_MORE",
  "GOALS",
  "GOALS_NONE",
  "\";\"",
  "GOAL_SEP_ALT",
  "PLAYER",
  "GOAL_COUNT",
  "GOAL_MINUTE_SEP",
  "GOAL_MINUTE",
  "GOALS_ALT",
  "GOAL_TYPE",
  "GOALS_COMPAT",
  "MINUTE",
  "PROP_ATTENDANCE",
  "PROP_NUM",
  "PROP_END",
  "PROP_REFEREE",
  "ATTENDANCE",
  "PROP_NAME",
  "ENCLOSED_NAME",
  "PROP_PENALTIES",
  "PROP_YELLOWCARDS",
  "PROP_REDCARDS",
  "PROP",
  "COACH",
  "\"(\"",
  "\")\"",
  "\"[\"",
  "\"]\"",
  "YELLOW_CARD",
  "RED_CARD",
  "$start",
  "document",
  "elements",
  "element",
  "heading",
  "group_def",
  "round_def",
  "round_outline",
  "date_header",
  "match_line_with_header",
  "match_line",
  "match_line_alt",
  "date_header_legs",
  "match_line_legs",
  "note_line",
  "nota_bene",
  "hruler",
  "table_line",
  "goal_lines",
  "goal_lines_alt",
  "goal_lines_compat",
  "lineup_lines",
  "yellowcard_lines",
  "redcard_lines",
  "penalties_lines",
  "referee_line",
  "attendance_line",
  "group_def_sep",
  "team_values",
  "round_def_sep",
  "round_date_opts",
  "date",
  "datetime",
  "time",
  "date_clause",
  "opt_date",
  "opt_blank_lines",
  "blank_lines",
  "match_header",
  "match_line_header",
  "opt_ord",
  "match",
  "more_match_header_opts",
  "match_line_alt_props",
  "geo_opts",
  "opt_inline_attendance",
  "inline_attendance",
  "match_fixture",
  "opt_inline_note",
  "match_opts",
  "more_match_opts",
  "match_bye",
  "match_walkover",
  "match_result",
  "goal_lines_body",
  "match_alt_inline",
  "match_alt_block",
  "opt_status_line",
  "opt_newline",
  "ord",
  "opt_geo",
  "geo_values",
  "match_fixture_not_played",
  "match_fixture_postponed",
  "match_fixture_base",
  "match_result_base",
  "match_sep",
  "score_full_or_fuller",
  "goals",
  "goals_sep",
  "opt_goal_sep",
  "goal",
  "goal_minutes",
  "opt_goal_minute_sep",
  "goal_minute",
  "goals_alt",
  "goal_alt",
  "goals_compat",
  "goal_compat",
  "referee",
  "attendance_opt",
  "penalties_body",
  "penalty",
  "penalty_sep",
  "card_body",
  "player_w_minute",
  "card_sep",
  "lineup",
  "coach_opt",
  "lineup_name",
  "lineup_sep",
  "lineup_card_opts",
  "lineup_sub_opts",
  "card",
  "card_type" ]
Ractor.make_shareable(Racc_token_to_s_table) if defined?(Ractor)

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'parser.y', 18)
  def _reduce_1(val, _values, result)
    
    result
  end
.,.,

# reduce 2 omitted

# reduce 3 omitted

# reduce 4 omitted

# reduce 5 omitted

# reduce 6 omitted

# reduce 7 omitted

# reduce 8 omitted

# reduce 9 omitted

# reduce 10 omitted

# reduce 11 omitted

# reduce 12 omitted

# reduce 13 omitted

# reduce 14 omitted

# reduce 15 omitted

# reduce 16 omitted

# reduce 17 omitted

# reduce 18 omitted

# reduce 19 omitted

# reduce 20 omitted

# reduce 21 omitted

module_eval(<<'.,.,', 'parser.y', 57)
  def _reduce_22(val, _values, result)
                   trace( "REDUCE BLANK" ) 
               @tree << BlankLine.new

    result
  end
.,.,

# reduce 23 omitted

# reduce 24 omitted

# reduce 25 omitted

# reduce 26 omitted

# reduce 27 omitted

# reduce 28 omitted

module_eval(<<'.,.,', 'parser.y', 67)
  def _reduce_29(val, _values, result)
     puts "!! skipping invalid content (trying to recover from parse error):"
                pp val[0]
                ##  note - do NOT report recover errors for now 
                ##  @errors << "parser error (recover) - skipping #{val[0].pretty_inspect}"

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 79)
  def _reduce_30(val, _values, result)
      @tree << Heading1.new( text: val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 80)
  def _reduce_31(val, _values, result)
      @tree << Heading2.new( text: val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 81)
  def _reduce_32(val, _values, result)
      @tree << Heading3.new( text: val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 84)
  def _reduce_33(val, _values, result)
     @tree << TableHeading.new( text: val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 85)
  def _reduce_34(val, _values, result)
     @tree << TableLine.new( text: val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 86)
  def _reduce_35(val, _values, result)
     @tree << TableNote.new( text: val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 87)
  def _reduce_36(val, _values, result)
     @tree << TableDivider.new( text: val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 90)
  def _reduce_37(val, _values, result)
     @tree << NoteLine.new( text: val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 93)
  def _reduce_38(val, _values, result)
     @tree << NotaBene.new( text: val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 96)
  def _reduce_39(val, _values, result)
     @tree << HRuler.new
    result
  end
.,.,

# reduce 40 omitted

# reduce 41 omitted

module_eval(<<'.,.,', 'parser.y', 108)
  def _reduce_42(val, _values, result)
                          @tree << GroupDef.new( name:  val[0],
                                             teams: val[2] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 113)
  def _reduce_43(val, _values, result)
     result = val
                                               ## e.g. val is ["Austria"] 

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 116)
  def _reduce_44(val, _values, result)
     result.push( val[1] )
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 117)
  def _reduce_45(val, _values, result)
     result.push( val[2] )
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 125)
  def _reduce_46(val, _values, result)
                                      kwargs = val[0][1]
                                  @tree << RoundOutline.new( **kwargs )

    result
  end
.,.,

# reduce 47 omitted

# reduce 48 omitted

module_eval(<<'.,.,', 'parser.y', 142)
  def _reduce_49(val, _values, result)
                          kwargs = { name: val[0] }.merge( val[2] )
                      @tree << RoundDef.new( **kwargs )

                      ## auto-add RoundOutline here - why? why not?
                      ##    or handle "implicit" round_outline
                      ##     in tree walker?
                      @tree << RoundOutline.new( outline: val[0], level: 1 )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 151)
  def _reduce_50(val, _values, result)
     result = { date: val[0][1] }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 152)
  def _reduce_51(val, _values, result)
     result = { duration: val[0][1] }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 159)
  def _reduce_52(val, _values, result)
     result = { date: val[0][1] }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 160)
  def _reduce_53(val, _values, result)
     result = { year: val[0] }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 163)
  def _reduce_54(val, _values, result)
     result = {}.merge( val[0][1] )
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 166)
  def _reduce_55(val, _values, result)
     result = {}.merge( val[0][1] )
    result
  end
.,.,

# reduce 56 omitted

# reduce 57 omitted

module_eval(<<'.,.,', 'parser.y', 176)
  def _reduce_58(val, _values, result)
      result = {}
    result
  end
.,.,

# reduce 59 omitted

# reduce 60 omitted

module_eval(<<'.,.,', 'parser.y', 189)
  def _reduce_61(val, _values, result)
                         @tree <<  DateHeader.new( **val[0] )  

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 195)
  def _reduce_62(val, _values, result)
                         kwargs =  val[0][1]  
                     @tree <<  DateHeaderLegs.new( **kwargs )                      

    result
  end
.,.,

# reduce 63 omitted

# reduce 64 omitted

# reduce 65 omitted

# reduce 66 omitted

module_eval(<<'.,.,', 'parser.y', 215)
  def _reduce_67(val, _values, result)
                         ## note - header flag (header: true)
                     ##    used downstream for scope / e.g. DateHeader merge/inheritance or such                     
                      kwargs = { header: true }.merge( val[0], val[2] )
                      @tree << MatchLine.new( **kwargs )  

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 224)
  def _reduce_68(val, _values, result)
                          result = {}.merge( val[0], val[1], val[2] )

    result
  end
.,.,

# reduce 69 omitted

module_eval(<<'.,.,', 'parser.y', 240)
  def _reduce_70(val, _values, result)
                          result = {}.merge( val[0][1] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 242)
  def _reduce_71(val, _values, result)
     result = { note: val[0] }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 243)
  def _reduce_72(val, _values, result)
     result = {}
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 256)
  def _reduce_73(val, _values, result)
                          result = {}.merge( val[0], val[1], val[2] ) 

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 260)
  def _reduce_74(val, _values, result)
                          result = {}.merge( val[0], val[1] ) 

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 271)
  def _reduce_75(val, _values, result)
                           result = { att: val[0][1][:value] }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 276)
  def _reduce_76(val, _values, result)
                           result = { att: val[1][1][:value] }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 280)
  def _reduce_77(val, _values, result)
      result = {}
    result
  end
.,.,

# reduce 78 omitted

module_eval(<<'.,.,', 'parser.y', 292)
  def _reduce_79(val, _values, result)
                          kwargs = { score: val[1][1] }.merge( val[0] )
                      @tree << MatchLineLegs.new( **kwargs )             

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 298)
  def _reduce_80(val, _values, result)
      result = {}
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 299)
  def _reduce_81(val, _values, result)
      result = { note: val[0] }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 307)
  def _reduce_82(val, _values, result)
                           kwargs = {}.merge( val[0], val[1], val[2] )
                       @tree << MatchLine.new( **kwargs )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 312)
  def _reduce_83(val, _values, result)
                           kwargs = {}.merge( val[0], val[1])
                       @tree << MatchLine.new( **kwargs )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 317)
  def _reduce_84(val, _values, result)
                           kwargs = {}.merge( val[0], val[1] )
                       @tree << MatchLine.new( **kwargs )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 322)
  def _reduce_85(val, _values, result)
                           kwargs = {}.merge( val[0] )
                       @tree << MatchLine.new( **kwargs )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 328)
  def _reduce_86(val, _values, result)
                             kwargs = {}.merge( val[0], val[1] )
                         @tree << MatchLineBye.new( **kwargs ) 

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 333)
  def _reduce_87(val, _values, result)
                             kwargs = {}.merge( val[0], val[1] )
                         @tree << MatchLineWalkover.new( **kwargs )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 344)
  def _reduce_88(val, _values, result)
                          kwargs = {}.merge( val[0] )
                      @tree << MatchLine.new( **kwargs )

                      kwargs = val[2]
                      @tree << GoalLine.new( **kwargs ) 

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 355)
  def _reduce_89(val, _values, result)
                                 kwargs = {}.merge( val[0] )
                             @tree << MatchLine.new( **kwargs )                           

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 364)
  def _reduce_90(val, _values, result)
                                      result = {}.merge( val[0] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 368)
  def _reduce_91(val, _values, result)
                                   result = {}.merge( val[0], val[2] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 374)
  def _reduce_92(val, _values, result)
     result = {}
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 377)
  def _reduce_93(val, _values, result)
                          puts "status_line:"
                      pp val[0]
                      result = val[0][1]   

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 390)
  def _reduce_94(val, _values, result)
                               ## puts "debug match_alt reduce:"
                           ## pp val[0]
                           ## pp val[2]

                           ## assume ht/ft  
                           ## or let's use [[0,1],[1,2]] - why? why not?
                           score_team1 = val[0][1][:score]
                           score_team2 = val[2][1][:score]

  
                           score =  [[score_team1[0], score_team2[0]],
                                     [score_team1[1], score_team2[1]]] 

                           result = { team1: val[0][1][:team], 
                                      team2: val[2][1][:team],
                                      score: score
                                    }

                           ## puts "  result:"
                           ## pp result   

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 413)
  def _reduce_95(val, _values, result)
                               ## assume pen for score_ii
                           ##    score_i might be ft or et???
                           ## or let's use [[0,1],[1,2]] - why? why not?
                           score_team1 = val[0][1][:score]
                           score_team2 = val[2][1][:score]
  
                           score =  { '_': [score_team1[0], score_team2[0]],
                                      pen: [score_team1[1], score_team2[1]] 
                                    } 

                           result = { team1: val[0][1][:team], 
                                      team2: val[2][1][:team],
                                      score: score
                                    }   

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 430)
  def _reduce_96(val, _values, result)
                               score_team1 = val[0][1][:score]
                           score_team2 = val[2][1][:score]
  
                           score =  [score_team1, score_team2] 

                           result = { team1: val[0][1][:team], 
                                      team2: val[2][1][:team],
                                      score: score
                                    }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 442)
  def _reduce_97(val, _values, result)
                               result = { team1: val[0], 
                                      team2: val[3],
                                      score: [val[1], val[4]]
                                    }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 456)
  def _reduce_98(val, _values, result)
                               ## assume ht/ft  
                           ## or let's use [[0,1],[1,2]] - why? why not?
                           score_team1 = val[0][1][:score]
                           score_team2 = val[1][1][:score]

                           score =  [[score_team1[0], score_team2[0]],
                                     [score_team1[1], score_team2[1]]] 

                           result = { team1: val[0][1][:team], 
                                      team2: val[1][1][:team],
                                      score: score
                                    }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 471)
  def _reduce_99(val, _values, result)
                               ## assume pen for score_ii
                           ##    score_i might be ft or et???
                           ## or let's use [[0,1],[1,2]] - why? why not?
                           score_team1 = val[0][1][:score]
                           score_team2 = val[1][1][:score]
  
                           score =  { '_': [score_team1[0], score_team2[0]],
                                      pen: [score_team1[1], score_team2[1]] 
                                    } 

                           result = { team1: val[0][1][:team], 
                                      team2: val[1][1][:team],
                                      score: score
                                    }   

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 488)
  def _reduce_100(val, _values, result)
                               score_team1 = val[0][1][:score]
                           score_team2 = val[1][1][:score]
  
                           score =  [score_team1, score_team2] 

                           result = { team1: val[0][1][:team], 
                                      team2: val[1][1][:team],
                                      score: score
                                    }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 500)
  def _reduce_101(val, _values, result)
                               result = { team1: val[0], 
                                      team2: val[2],
                                      score: [val[1], val[3]]
                                    }

    result
  end
.,.,

# reduce 102 omitted

# reduce 103 omitted

module_eval(<<'.,.,', 'parser.y', 513)
  def _reduce_104(val, _values, result)
      result = {}
    result
  end
.,.,

# reduce 105 omitted

module_eval(<<'.,.,', 'parser.y', 517)
  def _reduce_106(val, _values, result)
      result = { num: val[0][1][:value] }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 522)
  def _reduce_107(val, _values, result)
                                         result = {}.merge( val[0], val[1], val[2] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 525)
  def _reduce_108(val, _values, result)
                                         result = {}.merge( val[0], val[1] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 528)
  def _reduce_109(val, _values, result)
                                         result = {}.merge( val[0], val[1] )

    result
  end
.,.,

# reduce 110 omitted

module_eval(<<'.,.,', 'parser.y', 549)
  def _reduce_111(val, _values, result)
                          result = {}.merge( val[0][1] ) 

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 553)
  def _reduce_112(val, _values, result)
                         result = {}.merge( val[0][1], val[1], val[2] ) 

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 557)
  def _reduce_113(val, _values, result)
                       result = {}.merge( val[0], val[1], val[2] ) 

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 559)
  def _reduce_114(val, _values, result)
     result = { note: val[0] }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 564)
  def _reduce_115(val, _values, result)
     result = {}
    result
  end
.,.,

# reduce 116 omitted

module_eval(<<'.,.,', 'parser.y', 570)
  def _reduce_117(val, _values, result)
     result = { geo: val[1] }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 573)
  def _reduce_118(val, _values, result)
      result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 574)
  def _reduce_119(val, _values, result)
      result.push( val[2] )
    result
  end
.,.,

# reduce 120 omitted

# reduce 121 omitted

# reduce 122 omitted

# reduce 123 omitted

# reduce 124 omitted

# reduce 125 omitted

module_eval(<<'.,.,', 'parser.y', 597)
  def _reduce_126(val, _values, result)
     result = { team1: '_', team2: val[1] }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 598)
  def _reduce_127(val, _values, result)
     result = { team1: val[1], team2: '_' }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 599)
  def _reduce_128(val, _values, result)
     result = { team1: '_', team2: val[1],
                                                       neutral: true }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 607)
  def _reduce_129(val, _values, result)
                          result = { team: val[0] }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 616)
  def _reduce_130(val, _values, result)
                          result = { team1: val[0],
                                 team2: val[2] }

    result
  end
.,.,

# reduce 131 omitted

# reduce 132 omitted

module_eval(<<'.,.,', 'parser.y', 626)
  def _reduce_133(val, _values, result)
                                   trace( "RECUDE match_fixture" )
                               result = { team1: val[0],
                                          team2: val[2] }   

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 635)
  def _reduce_134(val, _values, result)
                                   ## note - auto-add (match) status canceled - why? why not?
                               ##   A n/p B   short (inline) form of =>
                               ##   A v B [canceled]

                               result = { team1: val[0],
                                          team2: val[2],
                                          status_inline: 'canceled' }   

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 645)
  def _reduce_135(val, _values, result)
                                   result = { team1: val[0],
                                          team2: val[2],
                                          status_inline: 'canceled' }   

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 652)
  def _reduce_136(val, _values, result)
                                   result = { team1: val[0],
                                          team2: val[2],
                                          status_inline: 'postponed' }   

    result
  end
.,.,

# reduce 137 omitted

# reduce 138 omitted

module_eval(<<'.,.,', 'parser.y', 668)
  def _reduce_139(val, _values, result)
                               trace( "REDUCE => match_result : TEAM SCORE TEAM" )
 
                          ## note - use/keep generic score (as array!! NOT hash!!!)
                           result = { team1: val[0], team2: val[2],
                                      score: val[1][1][:score]  ## note - as array e.g. [1,1] !!
                                    }   
                           ## pp result

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 678)
  def _reduce_140(val, _values, result)
                               result = { team1: val[0], team2: val[2],
                                      score: val[1][1],
                                      status_inline: 'awarded'
                                    }                          

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 685)
  def _reduce_141(val, _values, result)
                               result = { team1: val[0], team2: val[2], 
                                      status_inline: 'awarded' 
                                    }                          

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 691)
  def _reduce_142(val, _values, result)
                               result = { team1: val[0], team2: val[2],
                                      score: val[1][1],
                                      status_inline: 'abandoned'
                                    }                          

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 698)
  def _reduce_143(val, _values, result)
                               result = { team1: val[0], team2: val[2], 
                                      status_inline: 'abandoned' 
                                    }                          

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 704)
  def _reduce_144(val, _values, result)
                               result = { team1: val[0], team2: val[2], 
                                      status_inline: 'annulled' 
                                    }                          

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 710)
  def _reduce_145(val, _values, result)
                               result = { team1: val[0], team2: val[2], 
                                      status_inline: 'suspended' 
                                    }                          

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 717)
  def _reduce_146(val, _values, result)
                                trace( "REDUCE => match_result : TEAM SCORE TEAM SCORE_FULLER_MORE" )
                            score = nil
                            score =  if val[3][1][:score] && 
                                        val[3][1][:score]=='et'   ## check aet flag present? 
                                         val[3][1].delete( :score )  ## note - remove/delete  flag
                                           { et: val[1][1][:score] }
                                     elsif val[3][1][:score] && 
                                           val[3][1][:score]=='ht' ## check ht flag present?
                                         val[3][1].delete( :score ) ## note - remove/delete flag
                                           { ht: val[1][1][:score] }      
                                     elsif val[3][1][:score] && 
                                           val[3][1][:score]=='ft'  ## check ft flag present?
                                         val[3][1].delete( :score )  ## note - remove/delete flag
                                           { ft: val[1][1][:score] }
                                     else   ## assume full-time (ft)
                                            { ft: val[1][1][:score] }
                                     end 

                           result = {  team1: val[0],
                                      team2: val[2],
                                      score: score.merge( val[3][1] )
                                    }                                    

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 742)
  def _reduce_147(val, _values, result)
                               result = { team1: val[0],
                                      team2: val[2],
                                      score: val[1][1]
                                    }                          

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 749)
  def _reduce_148(val, _values, result)
                              trace( "REDUCE  => match_result : match_fixture SCORE" )
                          ## note - use/keep generic score (as array!! NOT hash!!!)
                          result = { score: val[1][1][:score]  ## note - as array e.g. [1,1] !! 
                                   }.merge( val[0] )  
                          ## pp result

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 757)
  def _reduce_149(val, _values, result)
                              trace( "REDUCE  => match_result : match_fixture score" )
                          result = { score: val[1][1] }.merge( val[0] )  
                          ## pp result

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 766)
  def _reduce_150(val, _values, result)
                              trace( "REDUCE  => match_result_base : match_fixture_base SCORE" )
                          ## note - use/keep generic score (as array!! NOT hash!!!)
                          result = { score: val[1][1][:score]  ## note - as array e.g. [1,1] !! 
                                   }.merge( val[0] )  
                          ## pp result

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 774)
  def _reduce_151(val, _values, result)
                              trace( "REDUCE  => match_result_base : match_fixture_base score" )
                          result = { score: val[1][1] }.merge( val[0] )  
                          ## pp result

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 813)
  def _reduce_152(val, _values, result)
                             kwargs = val[1]
                         @tree << GoalLine.new( **kwargs )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 818)
  def _reduce_153(val, _values, result)
      result = { goals1: val[0],
                                                              goals2: [] } 

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 821)
  def _reduce_154(val, _values, result)
      result = { goals1: [],
                                                              goals2: val[1] } 

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 824)
  def _reduce_155(val, _values, result)
      result = { goals1: val[0],
                                                              goals2: val[2] }

    result
  end
.,.,

# reduce 156 omitted

# reduce 157 omitted

# reduce 158 omitted

# reduce 159 omitted

module_eval(<<'.,.,', 'parser.y', 835)
  def _reduce_160(val, _values, result)
    
    result
  end
.,.,

# reduce 161 omitted

# reduce 162 omitted

# reduce 163 omitted

module_eval(<<'.,.,', 'parser.y', 840)
  def _reduce_164(val, _values, result)
     result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 841)
  def _reduce_165(val, _values, result)
     result.push( val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 849)
  def _reduce_166(val, _values, result)
                           result = Goal.new( player:  val[0],
                                          minutes: val[1] )   

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 854)
  def _reduce_167(val, _values, result)
                            ### todo/check:
                        ##    auto convert/expand 
                        ##    count to minutes - why? why not?
                        ##  todo/fix - pass in empty minutes ary [] - why? why not?
                        result = Goal.new( player: val[0],
                                           count:  val[1][1] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 863)
  def _reduce_168(val, _values, result)
                            result = Goal.new( player: val[0],
                                           minutes: [] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 870)
  def _reduce_169(val, _values, result)
    
    result
  end
.,.,

# reduce 170 omitted

module_eval(<<'.,.,', 'parser.y', 873)
  def _reduce_171(val, _values, result)
      result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 874)
  def _reduce_172(val, _values, result)
      result.push( val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 878)
  def _reduce_173(val, _values, result)
                                 kwargs = {}.merge( val[0][1] )
                             result = GoalMinute.new( **kwargs )  

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 895)
  def _reduce_174(val, _values, result)
                                 @tree << GoalLineAlt.new( goals: val[1] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 899)
  def _reduce_175(val, _values, result)
     result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 902)
  def _reduce_176(val, _values, result)
     result.push( val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 908)
  def _reduce_177(val, _values, result)
                               result = GoalAlt.new( score:   val[0][1][:score],
                                                 player:  val[1] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 913)
  def _reduce_178(val, _values, result)
                               goal_minute = GoalMinute.new( **val[2][1] )

                           result = GoalAlt.new( score:     val[0][1][:score],
                                                 player:    val[1],
                                                 minute:    goal_minute.to_minute,
                                                 goal_type: goal_minute.to_goal_type )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 922)
  def _reduce_179(val, _values, result)
                               result = GoalAlt.new( score:     val[0][1][:score],
                                                 player:    val[1],
                                                 goal_type: GoalType.new( **val[2][1] ))

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 932)
  def _reduce_180(val, _values, result)
                               result = GoalAlt.new( player:  val[0],
                                                 score:   val[1][1][:score] )                         

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 937)
  def _reduce_181(val, _values, result)
                               goal_minute = GoalMinute.new( **val[1][1] )
 
                           result = GoalAlt.new( player:    val[0],
                                                 minute:    goal_minute.to_minute,
                                                 goal_type: goal_minute.to_goal_type,
                                                 score:     val[2][1][:score] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 946)
  def _reduce_182(val, _values, result)
                               result = GoalAlt.new( player:    val[0],
                                                 goal_type: GoalType.new( **val[1][1] ),
                                                 score:     val[2][1][:score] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 958)
  def _reduce_183(val, _values, result)
                                 @tree << GoalLineCompat.new( goals: val[1] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 962)
  def _reduce_184(val, _values, result)
     result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 964)
  def _reduce_185(val, _values, result)
     result.push( val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 983)
  def _reduce_186(val, _values, result)
                               result = GoalCompat.new( minute:  Minute.new(**val[0][1]),
                                                    player:  val[1],
                                                    score:  val[2][1][:score] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 989)
  def _reduce_187(val, _values, result)
                               result = GoalCompat.new( minute: Minute.new(**val[0][1]),
                                                    player: val[1],
                                                    goal_type: GoalType.new( **val[2][1] ),
                                                    score:  val[3][1][:score] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 996)
  def _reduce_188(val, _values, result)
                               result = GoalCompat.new( minute:  Minute.new(**val[0][1]),
                                                    score:  val[1][1][:score],
                                                    player:  val[2] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1002)
  def _reduce_189(val, _values, result)
                               result = GoalCompat.new( minute: Minute.new(**val[0][1]),
                                                    score:  val[1][1][:score],
                                                    player: val[2],
                                                    goal_type: GoalType.new( **val[3][1] ))

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1015)
  def _reduce_190(val, _values, result)
                                     @tree << AttendanceLine.new( att: val[1][1][:value] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1021)
  def _reduce_191(val, _values, result)
                                   kwargs = val[1] 
                               @tree << RefereeLine.new( **kwargs ) 

    result
  end
.,.,

# reduce 192 omitted

module_eval(<<'.,.,', 'parser.y', 1028)
  def _reduce_193(val, _values, result)
                                     @tree << AttendanceLine.new( att: val[2][1][:value] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1033)
  def _reduce_194(val, _values, result)
      result = { name: val[0]}
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1035)
  def _reduce_195(val, _values, result)
      result = { name: val[0], country: val[1] }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1040)
  def _reduce_196(val, _values, result)
                                   @tree << PenaltiesLine.new( penalties: val[1] )                                                            

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1043)
  def _reduce_197(val, _values, result)
      result = [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1044)
  def _reduce_198(val, _values, result)
      result << val[2]
    result
  end
.,.,

# reduce 199 omitted

# reduce 200 omitted

# reduce 201 omitted

# reduce 202 omitted

module_eval(<<'.,.,', 'parser.y', 1054)
  def _reduce_203(val, _values, result)
                                     result = Penalty.new( score: val[0][1][:score],
                                                       name: val[1] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1059)
  def _reduce_204(val, _values, result)
                                     result = Penalty.new( score: val[0][1][:score],
                                                       name: val[1],
                                                       note: val[2] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1065)
  def _reduce_205(val, _values, result)
                                     result = Penalty.new( name: val[0] )                                

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1069)
  def _reduce_206(val, _values, result)
                                     result = Penalty.new( name: val[0],
                                                       note: val[1] )                                

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1076)
  def _reduce_207(val, _values, result)
                                   @tree << CardsLine.new( type: 'Y', bookings: val[1] )                               

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1080)
  def _reduce_208(val, _values, result)
                                   @tree << CardsLine.new( type: 'R', bookings: val[1] )                    

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1087)
  def _reduce_209(val, _values, result)
       result = [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1089)
  def _reduce_210(val, _values, result)
      result << val[2]
    result
  end
.,.,

# reduce 211 omitted

# reduce 212 omitted

# reduce 213 omitted

module_eval(<<'.,.,', 'parser.y', 1096)
  def _reduce_214(val, _values, result)
     result = Booking.new( name: val[0] )
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1098)
  def _reduce_215(val, _values, result)
     result = Booking.new( name: val[0], minute: val[1][1] )
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1106)
  def _reduce_216(val, _values, result)
                              kwargs = { team:    val[0],
                                     lineup:  val[1]  }.merge( val[2] ) 
                          @tree << LineupLine.new( **kwargs ) 

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1112)
  def _reduce_217(val, _values, result)
     result = {}
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1114)
  def _reduce_218(val, _values, result)
      result = { coach: val[2] }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1116)
  def _reduce_219(val, _values, result)
      result = { coach: val[3] }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1119)
  def _reduce_220(val, _values, result)
     result = [[val[0]]]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1122)
  def _reduce_221(val, _values, result)
                           ## if lineup_sep is -  start a new sub array!!
                       if val[1] == '-'
                          result << [val[2]]
                       else
                          result[-1] << val[2]
                       end

    result
  end
.,.,

# reduce 222 omitted

module_eval(<<'.,.,', 'parser.y', 1132)
  def _reduce_223(val, _values, result)
     result = val[0]
    result
  end
.,.,

# reduce 224 omitted

module_eval(<<'.,.,', 'parser.y', 1134)
  def _reduce_225(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1139)
  def _reduce_226(val, _values, result)
                                  kwargs = { name: val[0] }.merge( val[1] ).merge( val[2] )
                              result = Lineup.new( **kwargs )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1143)
  def _reduce_227(val, _values, result)
     result = {}
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1144)
  def _reduce_228(val, _values, result)
     result = { card: val[0] }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1161)
  def _reduce_229(val, _values, result)
     result = {}
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1164)
  def _reduce_230(val, _values, result)
                                  kwargs = { name: val[1] }.merge( val[2] ).merge( val[4] )
                              sub    = Sub.new( sub:    Lineup.new( **kwargs ),
                                                minute: Minute.new(val[3][1]) 
                                              )
                              result = { sub: sub }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1172)
  def _reduce_231(val, _values, result)
                                  sub = Sub.new( sub: val[1] )
                              result = { sub: sub }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1178)
  def _reduce_232(val, _values, result)
                                  sub = Sub.new( sub:    val[2],
                                             minute: Minute.new(val[1][1]) 
                                            )
                              result = { sub: sub }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1188)
  def _reduce_233(val, _values, result)
                                  kwargs = val[1]
                              result = Card.new( **kwargs )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1193)
  def _reduce_234(val, _values, result)
     result = { name: val[0] }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1195)
  def _reduce_235(val, _values, result)
     result = { name: val[0],
                                        minute: Minute.new(val[1][1]) } 

    result
  end
.,.,

# reduce 236 omitted

# reduce 237 omitted

def _reduce_none(val, _values, result)
  val[0]
end

end   # class RaccMatchParser
