#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.8.1
# from Racc grammar file "parser.y".
#

require 'racc/parser.rb'
class RaccMatchParser < Racc::Parser
##### State transition tables begin ###

racc_action_table = [
    27,    26,    28,   251,    29,    30,    31,    32,  -100,   251,
    33,    44,   321,    34,    35,    36,   258,    37,    38,    39,
    42,    43,   223,   223,    43,   323,   233,   251,    79,   170,
   298,   222,   222,   223,   113,   114,   115,   168,    46,    47,
    48,    50,   222,    51,   223,   248,    51,   126,   127,   126,
   127,    68,    81,   222,   223,   234,   117,   235,   259,  -200,
    69,   299,    70,   222,    71,  -200,   246,    72,   249,   242,
   257,    73,    74,    75,    76,  -148,  -148,   230,    77,    78,
    27,    26,    28,  -200,    29,    30,    31,    32,   236,   320,
    33,    44,   176,    34,    35,    36,   176,    37,    38,    39,
    42,    43,   322,   218,   266,   220,   221,  -148,   131,   136,
    43,   243,   136,   136,   170,   265,    43,   157,    46,    47,
    48,    50,   168,    51,    43,   170,   152,    43,   131,   154,
   177,    68,    51,   168,   177,    46,    47,    48,    51,   239,
    69,    82,    70,   158,    71,   135,   264,    72,   135,   135,
    83,    73,    74,    75,    76,    46,    47,    48,    77,    78,
    36,   157,    37,    38,    39,   238,    43,    97,    98,   100,
   101,   102,   106,   362,   103,   104,   105,   270,   107,   108,
   109,   110,   170,    84,   358,   271,   272,   158,    51,   357,
   168,    85,   111,   112,   331,   332,   333,    97,    98,   100,
   101,   102,   106,    89,   103,   104,   105,    93,   107,   108,
   109,   110,   152,    86,    87,   154,   113,   114,   121,   113,
   114,   115,   227,   292,   229,   293,   331,   332,   333,   331,
   332,   333,   331,   332,   333,    91,    90,   185,   186,   126,
   127,   126,   127,   288,  -157,   332,   333,    94,    96,   118,
   119,   120,   124,   136,   136,   144,    43,   161,   162,   165,
   180,   181,   183,   187,   188,   189,   190,   191,   192,   193,
   194,   195,   196,   197,   198,   199,   200,   201,   202,    50,
   206,   209,   211,    43,   214,   215,   217,   154,   232,   240,
   244,   245,   170,   253,   254,   255,   256,   261,   262,   269,
   273,   274,   275,   277,   278,   136,   281,   282,   154,   284,
   285,   286,   154,   290,   294,   295,   296,   161,   300,   301,
   302,   165,   304,   305,   170,   307,   308,   170,   310,   311,
   312,   313,   314,   315,   316,   318,   319,   324,   180,   334,
   338,   229,   340,   341,   342,   343,   344,   345,   346,   347,
   348,   351,   354,   355,   356,   364,   365,   351,   368 ]

racc_action_check = [
     0,     0,     0,   167,     0,     0,     0,     0,   128,   252,
     0,     0,   264,     0,     0,     0,   174,     0,     0,     0,
     0,     0,   225,   283,    53,   265,   158,   306,     1,    73,
   238,   225,   283,   155,    45,    45,    45,    73,     0,     0,
     0,     0,   155,     0,   159,   167,    53,    53,    53,   128,
   128,     0,    28,   159,   151,   158,    45,   158,   174,   167,
     0,   238,     0,   151,     0,   252,   167,     0,   167,   163,
   174,     0,     0,     0,     0,   225,   283,   155,     0,     0,
     2,     2,     2,   306,     2,     2,     2,     2,   159,   264,
     2,     2,    77,     2,     2,     2,   260,     2,     2,     2,
     2,     2,   265,   151,   178,   151,   151,   151,    54,    55,
    61,   163,   133,   276,    74,   178,   147,    69,     2,     2,
     2,     2,    74,     2,    55,    75,    68,   133,   205,    68,
    77,     2,    61,    75,   260,    54,    54,    54,   147,   161,
     2,    29,     2,    69,     2,    55,   178,     2,   133,   276,
    30,     2,     2,     2,     2,   205,   205,   205,     2,     2,
    59,   231,    59,    59,    59,   161,    59,    44,    44,    44,
    44,    44,    44,   357,    44,    44,    44,   182,    44,    44,
    44,    44,    76,    31,   351,   182,   182,   231,    59,   351,
    76,    32,    44,    44,   357,   357,   357,   131,   131,   131,
   131,   131,   131,    34,   131,   131,   131,    40,   131,   131,
   131,   131,   144,    33,    33,   144,    49,    49,    49,   132,
   132,   132,   154,   232,   154,   232,   268,   268,   268,   362,
   362,   362,   364,   364,   364,    35,    35,    92,    92,   139,
   139,   212,   212,   226,   226,   328,   328,    42,    43,    46,
    47,    48,    52,    56,    57,    58,    63,    70,    71,    72,
    78,    79,    88,    95,    99,   100,   101,   102,   103,   104,
   105,   106,   107,   108,   109,   110,   112,   117,   123,   125,
   127,   129,   137,   138,   142,   143,   150,   152,   157,   162,
   165,   166,   168,   170,   171,   172,   173,   176,   177,   180,
   184,   187,   192,   208,   210,   213,   216,   217,   219,   220,
   221,   222,   224,   230,   234,   235,   236,   237,   239,   240,
   241,   242,   243,   245,   247,   248,   249,   250,   251,   254,
   255,   256,   257,   258,   259,   261,   263,   266,   267,   272,
   281,   289,   299,   300,   302,   304,   319,   320,   321,   322,
   323,   326,   335,   346,   348,   358,   359,   360,   363 ]

racc_action_pointer = [
    -1,    28,    79,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    48,   137,
   146,   179,   187,   204,   199,   226,   nil,   nil,   nil,   nil,
   203,   nil,   243,   225,   143,     5,   237,   238,   239,   187,
   nil,   nil,   250,     2,    96,   102,   246,   247,   208,   144,
   nil,    88,   nil,   234,   nil,   nil,   nil,   nil,    72,    86,
   193,   192,   190,   -40,    45,    56,   113,    61,   191,   261,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   250,   nil,
   nil,   nil,   221,   nil,   nil,   250,   nil,   nil,   nil,   252,
   253,   254,   255,   256,   257,   258,   259,   260,   261,   262,
   263,   nil,   264,   nil,   nil,   nil,   nil,   273,   nil,   nil,
   nil,   nil,   nil,   276,   nil,   237,   nil,   235,     4,   277,
   nil,   173,   190,   105,   nil,   nil,   nil,   278,   261,   194,
   nil,   nil,   280,   281,   158,   nil,   nil,    94,   nil,   nil,
   238,    50,   230,   nil,   164,    29,   nil,   231,    -5,    40,
   nil,   108,   222,    56,   nil,   220,   224,   -10,   223,   nil,
   229,   227,   228,   229,     3,   nil,   228,   228,    91,   nil,
   217,   nil,   173,   nil,   296,   nil,   nil,   278,   nil,   nil,
   nil,   nil,   268,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   116,   nil,   nil,   299,   nil,
   300,   nil,   196,   298,   nil,   nil,   258,   303,   nil,   251,
   305,   306,   307,   nil,   255,    18,   184,   nil,   nil,   nil,
   309,   130,   163,   nil,   283,   284,   312,   253,    -1,   261,
   315,   253,   252,   251,   nil,   319,   nil,   255,   321,   322,
   258,   324,    -4,   nil,   325,   326,   327,   328,   329,   330,
    65,   265,   nil,   269,     8,    21,   333,   269,   141,   nil,
   nil,   nil,   327,   nil,   nil,   nil,   106,   nil,   nil,   nil,
   nil,   336,   nil,    19,   nil,   nil,   nil,   nil,   nil,   281,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   311,
   281,   nil,   340,   nil,   279,   nil,    14,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   342,
   278,   267,   280,   269,   nil,   nil,   268,   nil,   159,   nil,
   nil,   nil,   nil,   nil,   nil,   348,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   284,   nil,   285,   nil,
   nil,   120,   nil,   nil,   nil,   nil,   nil,   109,   286,   272,
   274,   nil,   144,   294,   147,   nil,   nil,   nil,   nil,   nil ]

racc_action_default = [
    -1,  -250,    -2,    -3,    -5,    -6,    -7,    -8,    -9,   -10,
   -11,   -12,   -13,   -14,   -15,   -16,   -17,   -18,   -19,   -20,
   -21,   -22,   -23,   -24,   -25,   -26,   -27,   -28,  -250,  -250,
  -250,  -250,  -250,  -250,  -250,  -250,   -50,   -51,   -52,   -53,
   -54,   -55,  -250,  -250,  -250,  -131,  -250,  -250,  -250,  -134,
   -90,   -97,   -34,  -117,  -250,  -125,   -95,   -95,  -130,  -114,
  -116,  -119,  -121,  -122,  -124,  -132,  -133,  -135,  -250,  -250,
  -250,  -250,  -250,  -250,  -250,  -250,  -250,  -250,  -250,  -250,
    -4,   -29,   -30,   -31,   -32,   -33,   -38,   -39,  -250,   -44,
   -45,   -46,  -250,   -59,   -60,   -61,   -62,   -66,   -67,  -250,
  -250,  -250,  -250,  -250,  -250,  -250,  -250,  -250,  -250,  -250,
  -250,  -136,  -250,   -72,   -73,   -79,   -80,  -250,   -85,   -86,
   -87,   -88,   -89,   -35,   -36,   -91,   -98,  -250,  -124,  -250,
  -118,  -250,  -131,  -125,  -130,   -93,   -94,  -250,  -126,  -100,
  -129,   -96,  -250,  -250,  -250,   -54,  -115,  -117,  -120,  -123,
  -250,  -140,  -250,  -152,  -156,  -148,  -163,  -250,  -250,  -148,
  -172,  -250,  -250,  -184,  -180,  -182,  -250,  -190,  -250,  -198,
  -203,  -250,  -250,  -250,  -250,  -210,  -250,  -214,  -217,  -226,
  -229,   370,  -250,   -41,  -250,   -48,   -49,  -250,   -68,   -69,
   -70,   -71,   -74,   -75,   -76,   -78,   -81,   -82,   -83,   -84,
  -137,  -138,   -37,   -92,  -102,  -250,   -99,  -101,  -250,  -104,
  -250,  -110,  -100,   -95,  -111,  -112,  -250,  -250,  -141,  -250,
  -144,  -146,  -149,  -151,  -250,  -142,  -154,  -155,  -159,  -161,
  -250,  -250,  -165,  -168,  -250,  -250,  -250,  -250,  -250,  -250,
  -250,  -250,  -250,  -250,  -183,  -250,  -191,  -250,  -194,  -196,
  -250,  -201,  -192,  -204,  -250,  -250,  -250,  -250,  -206,  -208,
  -250,  -212,  -215,  -250,  -250,  -224,  -222,  -250,  -240,  -230,
   -40,   -42,  -250,   -47,   -63,   -77,  -106,  -103,  -109,  -127,
  -128,  -250,  -139,  -143,  -145,  -147,  -150,  -153,  -158,  -250,
  -162,  -164,  -166,  -167,  -169,  -170,  -171,  -173,  -174,  -250,
  -176,  -178,  -250,  -181,  -250,  -186,  -193,  -195,  -197,  -199,
  -202,  -187,  -188,  -189,  -205,  -207,  -209,  -211,  -213,  -250,
  -250,  -250,  -250,  -225,  -223,  -227,  -235,  -241,  -242,  -245,
  -246,  -247,  -248,  -249,   -43,  -250,  -107,  -108,  -113,  -160,
  -175,  -177,  -179,  -185,  -216,  -218,  -250,  -220,  -250,  -228,
  -236,  -250,  -243,  -244,  -105,  -219,  -221,  -240,  -250,  -250,
  -238,  -231,  -240,  -241,  -240,  -237,  -239,  -232,  -233,  -234 ]

racc_goto_table = [
   140,   179,   175,   164,   160,   156,   142,   143,   132,   134,
   133,   228,   326,   130,   128,   137,   139,   252,   208,   150,
   225,   148,   350,   231,   149,     1,     3,   237,    80,   213,
   166,   171,   172,   173,     2,   125,   123,    88,   182,    92,
   184,   145,   147,    95,   122,   203,   205,   336,   129,   204,
   335,   146,   219,   287,   226,   289,   366,   155,   159,   163,
   241,   247,   309,   174,   260,   178,   263,   267,   268,   349,
   360,   363,   359,   352,   353,   nil,   nil,   nil,   140,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   283,   nil,   nil,
   nil,   nil,   nil,   210,   139,   216,   306,   nil,   nil,   212,
   nil,   361,   279,   nil,   nil,   nil,   367,   130,   369,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   339,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   132,
   134,   276,   nil,   280,   nil,   nil,   nil,   291,   nil,   nil,
   nil,   297,   nil,   303,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   317,   nil,   nil,   nil,   nil,
   325,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   337 ]

racc_goto_check = [
    51,    92,    88,    80,    77,    75,    52,    52,    41,    45,
    58,    73,    94,    66,    37,    61,    37,    82,    55,    64,
    67,    66,    98,    69,    37,     1,     3,    69,     3,    55,
    81,    81,    81,    81,     2,    26,    27,    28,    29,    30,
    31,    32,    35,    38,    44,    48,    49,    50,    54,    57,
    59,    65,    68,    70,    71,    72,    98,    74,    76,    78,
    79,    83,    84,    86,    87,    89,    90,    91,    93,    95,
    96,    97,    99,   101,   102,   nil,   nil,   nil,    51,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    67,   nil,   nil,
   nil,   nil,   nil,    61,    37,    64,    82,   nil,   nil,    37,
   nil,    94,    55,   nil,   nil,   nil,    94,    66,    94,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,    73,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    41,
    45,    58,   nil,    52,   nil,   nil,   nil,    75,   nil,   nil,
   nil,    77,   nil,    80,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    88,   nil,   nil,   nil,   nil,
    92,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,    51 ]

racc_goto_pointer = [
   nil,    25,    34,    26,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   -17,   -16,     4,   -50,
     4,   -52,   -18,   nil,   nil,   -17,   nil,   -39,     0,   nil,
   nil,   -46,   nil,   nil,    -5,   -45,   nil,   nil,   -80,   -79,
  -229,   -55,   -50,   nil,    -5,  -110,   nil,   -76,   -44,  -226,
   nil,   -40,   nil,   nil,   -49,    -8,   -40,  -132,   -99,  -132,
  -171,  -100,  -171,  -143,   -12,   -64,   -12,   -66,   -13,  -103,
   -69,   -43,  -151,  -106,  -188,   nil,   -14,  -110,   -75,   -13,
  -112,  -111,   -77,  -112,  -256,  -257,  -281,  -286,  -304,  -279,
   nil,  -255,  -254 ]

racc_goto_default = [
   nil,   nil,   nil,   nil,     4,     5,     6,     7,     8,     9,
    10,    11,    12,    13,    14,    15,    16,    17,    18,    19,
    20,    21,    22,    23,    24,    25,   nil,   nil,   nil,   nil,
   nil,   nil,    40,    41,    61,    53,   nil,    64,   nil,   nil,
    99,    45,    65,    66,   116,    58,    49,    67,    59,   nil,
   138,   141,   nil,    63,   207,   nil,    52,   nil,    55,   nil,
    54,   nil,    56,    57,   nil,    60,    62,   151,   nil,   224,
   153,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   167,   nil,   169,   250,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   327,   nil,   nil,
   328,   330,   329 ]

racc_reduce_table = [
  0, 0, :racc_error,
  0, 89, :_reduce_1,
  1, 89, :_reduce_none,
  1, 90, :_reduce_none,
  2, 90, :_reduce_none,
  1, 91, :_reduce_none,
  1, 91, :_reduce_none,
  1, 91, :_reduce_none,
  1, 91, :_reduce_none,
  1, 91, :_reduce_none,
  1, 91, :_reduce_none,
  1, 91, :_reduce_none,
  1, 91, :_reduce_none,
  1, 91, :_reduce_none,
  1, 91, :_reduce_none,
  1, 91, :_reduce_none,
  1, 91, :_reduce_none,
  1, 91, :_reduce_none,
  1, 91, :_reduce_none,
  1, 91, :_reduce_none,
  1, 91, :_reduce_none,
  1, 91, :_reduce_none,
  1, 91, :_reduce_none,
  1, 91, :_reduce_none,
  1, 91, :_reduce_none,
  1, 91, :_reduce_none,
  1, 91, :_reduce_none,
  1, 91, :_reduce_27,
  1, 91, :_reduce_28,
  2, 92, :_reduce_29,
  2, 92, :_reduce_30,
  2, 92, :_reduce_31,
  2, 101, :_reduce_32,
  2, 102, :_reduce_33,
  0, 114, :_reduce_34,
  1, 114, :_reduce_none,
  1, 115, :_reduce_none,
  2, 115, :_reduce_none,
  1, 116, :_reduce_none,
  1, 116, :_reduce_none,
  4, 93, :_reduce_40,
  1, 117, :_reduce_41,
  2, 117, :_reduce_42,
  3, 117, :_reduce_43,
  2, 95, :_reduce_44,
  1, 118, :_reduce_none,
  1, 118, :_reduce_none,
  4, 94, :_reduce_47,
  1, 119, :_reduce_48,
  1, 119, :_reduce_49,
  1, 120, :_reduce_50,
  1, 120, :_reduce_51,
  1, 121, :_reduce_52,
  1, 122, :_reduce_53,
  1, 123, :_reduce_none,
  1, 123, :_reduce_none,
  0, 124, :_reduce_56,
  1, 124, :_reduce_none,
  1, 124, :_reduce_none,
  2, 96, :_reduce_59,
  2, 99, :_reduce_60,
  2, 125, :_reduce_61,
  1, 126, :_reduce_62,
  3, 126, :_reduce_63,
  0, 127, :_reduce_64,
  1, 127, :_reduce_none,
  1, 128, :_reduce_none,
  1, 128, :_reduce_none,
  3, 129, :_reduce_68,
  3, 130, :_reduce_69,
  3, 130, :_reduce_70,
  3, 131, :_reduce_71,
  1, 132, :_reduce_none,
  1, 132, :_reduce_none,
  3, 133, :_reduce_74,
  3, 133, :_reduce_75,
  3, 133, :_reduce_76,
  4, 133, :_reduce_77,
  3, 133, :_reduce_78,
  2, 133, :_reduce_79,
  2, 133, :_reduce_80,
  3, 133, :_reduce_81,
  3, 133, :_reduce_82,
  3, 133, :_reduce_83,
  3, 133, :_reduce_84,
  2, 134, :_reduce_85,
  2, 134, :_reduce_86,
  2, 134, :_reduce_87,
  2, 135, :_reduce_88,
  2, 135, :_reduce_89,
  1, 136, :_reduce_90,
  0, 137, :_reduce_91,
  1, 137, :_reduce_none,
  1, 138, :_reduce_93,
  1, 139, :_reduce_94,
  0, 140, :_reduce_95,
  1, 140, :_reduce_none,
  1, 141, :_reduce_97,
  1, 142, :_reduce_98,
  2, 142, :_reduce_99,
  0, 143, :_reduce_100,
  1, 143, :_reduce_none,
  3, 97, :_reduce_102,
  4, 144, :_reduce_103,
  3, 144, :_reduce_104,
  4, 145, :_reduce_105,
  0, 147, :_reduce_106,
  1, 147, :_reduce_none,
  1, 147, :_reduce_none,
  4, 98, :_reduce_109,
  3, 98, :_reduce_110,
  3, 98, :_reduce_111,
  3, 98, :_reduce_112,
  5, 98, :_reduce_113,
  1, 148, :_reduce_none,
  2, 148, :_reduce_115,
  1, 148, :_reduce_none,
  1, 153, :_reduce_none,
  2, 153, :_reduce_118,
  1, 153, :_reduce_none,
  2, 153, :_reduce_120,
  1, 153, :_reduce_none,
  1, 154, :_reduce_none,
  2, 154, :_reduce_123,
  1, 154, :_reduce_none,
  0, 149, :_reduce_125,
  1, 149, :_reduce_none,
  3, 149, :_reduce_127,
  3, 149, :_reduce_128,
  1, 149, :_reduce_none,
  1, 146, :_reduce_none,
  1, 146, :_reduce_none,
  1, 146, :_reduce_none,
  1, 146, :_reduce_none,
  1, 146, :_reduce_none,
  1, 146, :_reduce_none,
  2, 150, :_reduce_136,
  3, 151, :_reduce_137,
  3, 100, :_reduce_138,
  4, 103, :_reduce_139,
  1, 152, :_reduce_140,
  2, 152, :_reduce_141,
  2, 152, :_reduce_142,
  3, 152, :_reduce_143,
  1, 156, :_reduce_none,
  2, 156, :_reduce_none,
  1, 156, :_reduce_none,
  2, 156, :_reduce_none,
  0, 157, :_reduce_none,
  1, 157, :_reduce_none,
  2, 157, :_reduce_none,
  1, 157, :_reduce_none,
  1, 155, :_reduce_152,
  3, 155, :_reduce_153,
  2, 158, :_reduce_154,
  2, 158, :_reduce_155,
  1, 158, :_reduce_156,
  0, 160, :_reduce_157,
  1, 160, :_reduce_none,
  1, 159, :_reduce_159,
  3, 159, :_reduce_160,
  1, 161, :_reduce_161,
  4, 104, :_reduce_162,
  1, 162, :_reduce_163,
  3, 162, :_reduce_164,
  2, 163, :_reduce_165,
  3, 163, :_reduce_166,
  3, 163, :_reduce_167,
  2, 163, :_reduce_168,
  3, 163, :_reduce_169,
  3, 163, :_reduce_170,
  4, 105, :_reduce_171,
  1, 164, :_reduce_172,
  3, 164, :_reduce_173,
  3, 165, :_reduce_174,
  4, 165, :_reduce_175,
  3, 165, :_reduce_176,
  4, 165, :_reduce_177,
  4, 109, :_reduce_178,
  5, 108, :_reduce_179,
  1, 166, :_reduce_180,
  3, 166, :_reduce_181,
  1, 168, :_reduce_182,
  2, 168, :_reduce_183,
  0, 167, :_reduce_none,
  3, 167, :_reduce_185,
  4, 110, :_reduce_186,
  4, 111, :_reduce_187,
  4, 112, :_reduce_188,
  4, 113, :_reduce_189,
  1, 169, :_reduce_190,
  2, 169, :_reduce_191,
  2, 169, :_reduce_192,
  3, 169, :_reduce_193,
  1, 171, :_reduce_none,
  2, 171, :_reduce_none,
  1, 171, :_reduce_none,
  2, 171, :_reduce_none,
  1, 170, :_reduce_198,
  3, 170, :_reduce_199,
  0, 173, :_reduce_none,
  1, 173, :_reduce_none,
  2, 173, :_reduce_none,
  1, 172, :_reduce_203,
  2, 172, :_reduce_204,
  4, 107, :_reduce_205,
  1, 175, :_reduce_none,
  2, 175, :_reduce_none,
  1, 175, :_reduce_none,
  2, 175, :_reduce_none,
  1, 174, :_reduce_210,
  3, 174, :_reduce_211,
  2, 176, :_reduce_212,
  3, 176, :_reduce_213,
  1, 176, :_reduce_214,
  2, 176, :_reduce_215,
  5, 106, :_reduce_216,
  0, 178, :_reduce_217,
  3, 178, :_reduce_218,
  4, 178, :_reduce_219,
  3, 178, :_reduce_220,
  4, 178, :_reduce_221,
  1, 179, :_reduce_222,
  2, 179, :_reduce_223,
  1, 179, :_reduce_224,
  2, 179, :_reduce_225,
  1, 177, :_reduce_226,
  3, 177, :_reduce_227,
  4, 180, :_reduce_228,
  0, 181, :_reduce_229,
  1, 181, :_reduce_230,
  2, 184, :_reduce_231,
  3, 184, :_reduce_232,
  3, 184, :_reduce_233,
  3, 184, :_reduce_234,
  0, 183, :_reduce_235,
  1, 183, :_reduce_none,
  3, 186, :_reduce_237,
  1, 187, :_reduce_238,
  2, 187, :_reduce_239,
  0, 182, :_reduce_240,
  1, 182, :_reduce_241,
  1, 185, :_reduce_242,
  2, 185, :_reduce_243,
  2, 185, :_reduce_244,
  1, 185, :_reduce_245,
  1, 185, :_reduce_246,
  1, 188, :_reduce_247,
  1, 189, :_reduce_248,
  1, 190, :_reduce_249 ]

racc_reduce_n = 250

racc_shift_n = 370

racc_token_table = {
  false => 0,
  :error => 1,
  :BLANK => 2,
  :H1 => 3,
  :NEWLINE => 4,
  :H2 => 5,
  :H3 => 6,
  :NOTE => 7,
  :NOTA_BENE => 8,
  "|" => 9,
  ":" => 10,
  :GROUP_DEF => 11,
  :TEAM => 12,
  "," => 13,
  :ROUND_OUTLINE => 14,
  :ROUND_DEF => 15,
  :DATE => 16,
  :DURATION => 17,
  :YEAR => 18,
  :DATETIME => 19,
  :TIME => 20,
  :DATE_LEGS => 21,
  "@" => 22,
  :GEO => 23,
  "-" => 24,
  :VS => 25,
  :INLINE_NP => 26,
  :INLINE_CANC => 27,
  :INLINE_PPD => 28,
  :SCORE_FULL => 29,
  :SCORE_FULLER => 30,
  :SCORE => 31,
  :SCORE_AWD => 32,
  :SCORE_ABD => 33,
  :SCORE_FULLER_MORE => 34,
  :INLINE_AWD => 35,
  :INLINE_ABD => 36,
  :INLINE_VOID => 37,
  :INLINE_SUSP => 38,
  :TEAM_HOME => 39,
  :TEAM_AWAY => 40,
  :TEAM_NEUTRAL => 41,
  :ORD => 42,
  :STATUS => 43,
  :INLINE_ROUND => 44,
  :INLINE_ATTENDANCE => 45,
  :INLINE_ATTENDANCE_SEP => 46,
  :INLINE_GOALS => 47,
  :GOALS_END => 48,
  :INLINE_BYE => 49,
  :INLINE_WO => 50,
  :SCORE_LEGS => 51,
  :GOALS => 52,
  :GOALS_NONE_RIGHT => 53,
  :GOALS_NONE => 54,
  ";" => 55,
  :GOAL_SEP_ALT => 56,
  :PLAYER => 57,
  :GOAL_COUNT => 58,
  :GOAL_MINUTE_SEP => 59,
  :GOAL_MINUTE => 60,
  :GOALS_ALT => 61,
  :GOAL_TYPE => 62,
  :GOALS_COMPAT => 63,
  :MINUTE => 64,
  :PROP_ATTENDANCE => 65,
  :PROP_NUM => 66,
  :PROP_END => 67,
  :PROP_REFEREE => 68,
  :PROP_NAME => 69,
  :ENCLOSED_NAME => 70,
  :ATTENDANCE => 71,
  :PROP_YELLOWCARDS => 72,
  :PROP_REDCARDS => 73,
  :PROP_REDYELLOWCARDS => 74,
  :PROP_SENTOFF => 75,
  :CARDS_NONE_RIGHT => 76,
  :CARDS_NONE_LEFT => 77,
  :CARDS_SEP_ALT => 78,
  :PROP_PENALTIES => 79,
  :PROP => 80,
  :COACH => 81,
  :INLINE_CAPTAIN => 82,
  "(" => 83,
  ")" => 84,
  :INLINE_YELLOW => 85,
  :INLINE_YELLOW_RED => 86,
  :INLINE_RED => 87 }

racc_nt_base = 88

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]
Ractor.make_shareable(Racc_arg) if defined?(Ractor)

Racc_token_to_s_table = [
  "$end",
  "error",
  "BLANK",
  "H1",
  "NEWLINE",
  "H2",
  "H3",
  "NOTE",
  "NOTA_BENE",
  "\"|\"",
  "\":\"",
  "GROUP_DEF",
  "TEAM",
  "\",\"",
  "ROUND_OUTLINE",
  "ROUND_DEF",
  "DATE",
  "DURATION",
  "YEAR",
  "DATETIME",
  "TIME",
  "DATE_LEGS",
  "\"@\"",
  "GEO",
  "\"-\"",
  "VS",
  "INLINE_NP",
  "INLINE_CANC",
  "INLINE_PPD",
  "SCORE_FULL",
  "SCORE_FULLER",
  "SCORE",
  "SCORE_AWD",
  "SCORE_ABD",
  "SCORE_FULLER_MORE",
  "INLINE_AWD",
  "INLINE_ABD",
  "INLINE_VOID",
  "INLINE_SUSP",
  "TEAM_HOME",
  "TEAM_AWAY",
  "TEAM_NEUTRAL",
  "ORD",
  "STATUS",
  "INLINE_ROUND",
  "INLINE_ATTENDANCE",
  "INLINE_ATTENDANCE_SEP",
  "INLINE_GOALS",
  "GOALS_END",
  "INLINE_BYE",
  "INLINE_WO",
  "SCORE_LEGS",
  "GOALS",
  "GOALS_NONE_RIGHT",
  "GOALS_NONE",
  "\";\"",
  "GOAL_SEP_ALT",
  "PLAYER",
  "GOAL_COUNT",
  "GOAL_MINUTE_SEP",
  "GOAL_MINUTE",
  "GOALS_ALT",
  "GOAL_TYPE",
  "GOALS_COMPAT",
  "MINUTE",
  "PROP_ATTENDANCE",
  "PROP_NUM",
  "PROP_END",
  "PROP_REFEREE",
  "PROP_NAME",
  "ENCLOSED_NAME",
  "ATTENDANCE",
  "PROP_YELLOWCARDS",
  "PROP_REDCARDS",
  "PROP_REDYELLOWCARDS",
  "PROP_SENTOFF",
  "CARDS_NONE_RIGHT",
  "CARDS_NONE_LEFT",
  "CARDS_SEP_ALT",
  "PROP_PENALTIES",
  "PROP",
  "COACH",
  "INLINE_CAPTAIN",
  "\"(\"",
  "\")\"",
  "INLINE_YELLOW",
  "INLINE_YELLOW_RED",
  "INLINE_RED",
  "$start",
  "document",
  "elements",
  "element",
  "heading",
  "group_def",
  "round_def",
  "round_outline",
  "date_header",
  "match_line_with_header",
  "match_line",
  "date_header_legs",
  "match_line_legs",
  "note_line",
  "nota_bene",
  "goal_lines",
  "goal_lines_alt",
  "goal_lines_compat",
  "lineup_lines",
  "penalties_lines",
  "referee_line",
  "attendance_line",
  "yellowcard_line",
  "redcard_line",
  "yellowredcard_line",
  "sentoff_line",
  "opt_blank_lines",
  "blank_lines",
  "group_def_sep",
  "team_values",
  "round_def_sep",
  "round_date_opts",
  "date",
  "datetime",
  "time",
  "date_datetime",
  "opt_date",
  "geo",
  "geo_names",
  "opt_geo",
  "match_sep",
  "match_fixture",
  "match_fixture_not_played",
  "match_fixture_postponed",
  "SCORE_FULL_OR_FULLER",
  "match_result",
  "match_fixture_base",
  "match_result_base",
  "ord",
  "opt_ord",
  "status",
  "note",
  "opt_inline_note",
  "inline_round",
  "inline_attendance",
  "opt_inline_attendance",
  "match_header",
  "match_line_header",
  "match",
  "more_match_header_opts",
  "pre_match_opts",
  "more_match_opts",
  "match_bye",
  "match_walkover",
  "goal_lines_body",
  "pre_match1",
  "pre_match2",
  "goals",
  "goals_sep",
  "opt_goal_sep",
  "goal",
  "goal_minutes",
  "opt_goal_minute_sep",
  "goal_minute",
  "goals_alt",
  "goal_alt",
  "goals_compat",
  "goal_compat",
  "referees",
  "attendance_opt",
  "referee",
  "card_body",
  "cards",
  "cards_sep",
  "player_w_minute",
  "opt_card_sep",
  "penalties_body",
  "penalty_sep",
  "penalty",
  "lineup",
  "opt_coach",
  "lineup_sep",
  "lineup_name",
  "opt_captain",
  "opt_inline_cards",
  "opt_lineup_sub",
  "lineup_sub_props",
  "inline_cards",
  "lineup_sub",
  "lineup_sub_contents",
  "inline_yellow",
  "inline_yellow_red",
  "inline_red" ]
Ractor.make_shareable(Racc_token_to_s_table) if defined?(Ractor)

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'parser.y', 9)
  def _reduce_1(val, _values, result)
     result = []
    result
  end
.,.,

# reduce 2 omitted

# reduce 3 omitted

# reduce 4 omitted

# reduce 5 omitted

# reduce 6 omitted

# reduce 7 omitted

# reduce 8 omitted

# reduce 9 omitted

# reduce 10 omitted

# reduce 11 omitted

# reduce 12 omitted

# reduce 13 omitted

# reduce 14 omitted

# reduce 15 omitted

# reduce 16 omitted

# reduce 17 omitted

# reduce 18 omitted

# reduce 19 omitted

# reduce 20 omitted

# reduce 21 omitted

# reduce 22 omitted

# reduce 23 omitted

# reduce 24 omitted

# reduce 25 omitted

# reduce 26 omitted

module_eval(<<'.,.,', 'parser.y', 54)
  def _reduce_27(val, _values, result)
                   ## _trace( "REDUCE BLANK" )
               @tree << BlankLine.new

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 60)
  def _reduce_28(val, _values, result)
     puts "!! skipping invalid content (trying to recover from parse error):"
                pp val[0]
                ##  note - do NOT report recover errors for now
                ##  @errors << "parser error (recover) - skipping #{val[0].pretty_inspect}"

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 71)
  def _reduce_29(val, _values, result)
      @tree << Heading1.new( text: val[0].as_str)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 72)
  def _reduce_30(val, _values, result)
      @tree << Heading2.new( text: val[0].as_str)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 73)
  def _reduce_31(val, _values, result)
      @tree << Heading3.new( text: val[0].as_str)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 77)
  def _reduce_32(val, _values, result)
     @tree << NoteLine.new( text: val[0].as_str)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 80)
  def _reduce_33(val, _values, result)
     @tree << NotaBene.new( text: val[0].as_str)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 88)
  def _reduce_34(val, _values, result)
    
    result
  end
.,.,

# reduce 35 omitted

# reduce 36 omitted

# reduce 37 omitted

# reduce 38 omitted

# reduce 39 omitted

module_eval(<<'.,.,', 'parser.y', 110)
  def _reduce_40(val, _values, result)
                          @tree << GroupDef.new( name:  val[0].as_str,
                                             teams: val[2] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 115)
  def _reduce_41(val, _values, result)
     result = [val[0].as_str]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 116)
  def _reduce_42(val, _values, result)
     result.push( val[1].as_str )
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 117)
  def _reduce_43(val, _values, result)
     result.push( val[2].as_str )
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 127)
  def _reduce_44(val, _values, result)
                                      @tree << RoundOutline.new( **val[0].as_hash )

    result
  end
.,.,

# reduce 45 omitted

# reduce 46 omitted

module_eval(<<'.,.,', 'parser.y', 142)
  def _reduce_47(val, _values, result)
                          kwargs = { name: val[0].as_str }.merge( val[2] )
                      @tree << RoundDef.new( **kwargs )

                      ## auto-add RoundOutline here - why? why not?
                      ##    or handle "implicit" round_outline
                      ##     in tree walker?
                      @tree << RoundOutline.new( outline: val[0].as_str, level: 1 )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 155)
  def _reduce_48(val, _values, result)
     result = { date: val[0].as_hash }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 156)
  def _reduce_49(val, _values, result)
     result = { duration: val[0].as_hash }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 166)
  def _reduce_50(val, _values, result)
     result = { date: val[0].as_hash }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 167)
  def _reduce_51(val, _values, result)
     result = { year: val[0].as_int }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 172)
  def _reduce_52(val, _values, result)
     result = val[0].as_hash
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 175)
  def _reduce_53(val, _values, result)
     result = val[0].as_hash
    result
  end
.,.,

# reduce 54 omitted

# reduce 55 omitted

module_eval(<<'.,.,', 'parser.y', 190)
  def _reduce_56(val, _values, result)
      result = {}
    result
  end
.,.,

# reduce 57 omitted

# reduce 58 omitted

module_eval(<<'.,.,', 'parser.y', 203)
  def _reduce_59(val, _values, result)
                         @tree <<  DateHeader.new( **val[0] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 210)
  def _reduce_60(val, _values, result)
                         @tree <<  DateHeaderLegs.new( **val[0].as_hash )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 221)
  def _reduce_61(val, _values, result)
     result = { geo: val[1] }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 224)
  def _reduce_62(val, _values, result)
      result = [val[0].as_str]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 225)
  def _reduce_63(val, _values, result)
      result.push( val[2].as_str )
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 229)
  def _reduce_64(val, _values, result)
     result = {}
    result
  end
.,.,

# reduce 65 omitted

# reduce 66 omitted

# reduce 67 omitted

module_eval(<<'.,.,', 'parser.y', 251)
  def _reduce_68(val, _values, result)
                                   _trace( "RECUDE match_fixture" )
                               result = { team1: val[0].as_str,
                                          team2: val[2].as_str }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 263)
  def _reduce_69(val, _values, result)
                                   ## note - auto-add (match) status canceled - why? why not?
                               ##   A n/p B   short (inline) form of =>
                               ##   A v B [canceled]

                               result = { team1: val[0].as_str,
                                          team2: val[2].as_str,
                                          status_inline: 'canceled' }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 273)
  def _reduce_70(val, _values, result)
                                   result = { team1: val[0].as_str,
                                          team2: val[2].as_str,
                                          status_inline: 'canceled' }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 280)
  def _reduce_71(val, _values, result)
                                   result = { team1: val[0].as_str,
                                          team2: val[2].as_str,
                                          status_inline: 'postponed' }

    result
  end
.,.,

# reduce 72 omitted

# reduce 73 omitted

module_eval(<<'.,.,', 'parser.y', 298)
  def _reduce_74(val, _values, result)
                               _trace( "REDUCE => match_result : TEAM SCORE TEAM" )

                          ## note - use/keep generic score (as array!! NOT hash!!!)
                          ##      - as array e.g. [1,1] !!
                           result = { team1: val[0].as_str, team2: val[2].as_str,
                                      score: val[1].as_ary
                                    }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 308)
  def _reduce_75(val, _values, result)
                               result = { team1: val[0].as_str, team2: val[2].as_str,
                                      score: val[1].as_ary,
                                      status_inline: 'awarded'
                                    }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 315)
  def _reduce_76(val, _values, result)
                               result = { team1: val[0].as_str, team2: val[2].as_str,
                                      score: val[1].as_ary,
                                      status_inline: 'abandoned'
                                    }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 322)
  def _reduce_77(val, _values, result)
                                _trace( "REDUCE => match_result : TEAM SCORE TEAM SCORE_FULLER_MORE" )
                            score =  if val[3].as_hash[:score] &&
                                        val[3].as_hash[:score]=='et'   ## check aet flag present?
                                         val[3].as_hash.delete( :score )  ## note - remove/delete  flag
                                           { et: val[1].as_ary }
                                     elsif val[3].as_hash[:score] &&
                                           val[3].as_hash[:score]=='ht' ## check ht flag present?
                                         val[3].as_hash.delete( :score ) ## note - remove/delete flag
                                           { ht: val[1].as_ary }
                                     elsif val[3].as_hash[:score] &&
                                           val[3].as_hash[:score]=='ft'  ## check ft flag present?
                                         val[3].as_hash.delete( :score )  ## note - remove/delete flag
                                           { ft: val[1].as_ary }
                                     else   ## assume full-time (ft)
                                            { ft: val[1].as_ary }
                                     end

                           result = {  team1: val[0].as_str,
                                      team2: val[2].as_str,
                                      score: score.merge( val[3].as_hash )
                                    }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 346)
  def _reduce_78(val, _values, result)
                               result = { team1: val[0].as_str,
                                      team2: val[2].as_str,
                                      score: val[1].as_hash
                                    }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 360)
  def _reduce_79(val, _values, result)
                              _trace( "REDUCE  => match_result : match_fixture SCORE" )
                          ## note - use/keep generic score (as array!! NOT hash!!!)
                          ##      - as array e.g. [1,1] !!
                          result = { score: val[1].as_ary }.merge( val[0] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 367)
  def _reduce_80(val, _values, result)
                              _trace( "REDUCE  => match_result : match_fixture SCORE_FULL_OR_FULLER" )
                          result = { score: val[1].as_hash }.merge( val[0] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 379)
  def _reduce_81(val, _values, result)
                               result = { team1: val[0].as_str, team2: val[2].as_str,
                                      status_inline: 'awarded'
                                    }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 385)
  def _reduce_82(val, _values, result)
                               result = { team1: val[0].as_str, team2: val[2].as_str,
                                      status_inline: 'abandoned'
                                    }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 391)
  def _reduce_83(val, _values, result)
                               result = { team1: val[0].as_str, team2: val[2].as_str,
                                      status_inline: 'annulled'
                                    }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 397)
  def _reduce_84(val, _values, result)
                               result = { team1: val[0].as_str, team2: val[2].as_str,
                                      status_inline: 'suspended'
                                    }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 411)
  def _reduce_85(val, _values, result)
     result = { team1: '_', team2: val[1].as_str }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 412)
  def _reduce_86(val, _values, result)
     result = { team1: val[1].as_str, team2: '_' }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 413)
  def _reduce_87(val, _values, result)
     result = { team1: '_', team2: val[1].as_str,
                                                       neutral: true }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 420)
  def _reduce_88(val, _values, result)
                              _trace( "REDUCE  => match_result_base : match_fixture_base SCORE" )
                          ## note - use/keep generic score (as array!! NOT hash!!!)
                          ##      - as array e.g. [1,1] !!
                          result = { score: val[1].as_ary }.merge( val[0] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 427)
  def _reduce_89(val, _values, result)
                              _trace( "REDUCE  => match_result_base : match_fixture_base SCORE_FULL_OR_FULLER" )
                          result = { score: val[1].as_hash }.merge( val[0] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 437)
  def _reduce_90(val, _values, result)
      result = { num: val[0].as_int }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 440)
  def _reduce_91(val, _values, result)
      result = {}
    result
  end
.,.,

# reduce 92 omitted

module_eval(<<'.,.,', 'parser.y', 449)
  def _reduce_93(val, _values, result)
      result = val[0].as_hash
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 451)
  def _reduce_94(val, _values, result)
     result = { note: val[0].as_str }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 454)
  def _reduce_95(val, _values, result)
      result = {}
    result
  end
.,.,

# reduce 96 omitted

module_eval(<<'.,.,', 'parser.y', 458)
  def _reduce_97(val, _values, result)
     result = { inline_round: val[0].as_str }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 471)
  def _reduce_98(val, _values, result)
                           result = { att: val[0].as_hash[:value] }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 475)
  def _reduce_99(val, _values, result)
                           result = { att: val[1].as_hash[:value] }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 479)
  def _reduce_100(val, _values, result)
      result = {}
    result
  end
.,.,

# reduce 101 omitted

module_eval(<<'.,.,', 'parser.y', 496)
  def _reduce_102(val, _values, result)
                         ## note - header flag (header: true)
                     ##    used downstream for scope / e.g. DateHeader merge/inheritance or such
                      kwargs = { header: true }.merge( val[0], val[2] )
                      @tree << MatchLine.new( **kwargs )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 511)
  def _reduce_103(val, _values, result)
                          result = {}.merge( val[0], val[1], val[2] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 515)
  def _reduce_104(val, _values, result)
                          result = {}.merge( val[0], val[1] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 521)
  def _reduce_105(val, _values, result)
                          result = {}.merge( val[0], val[1], val[2] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 529)
  def _reduce_106(val, _values, result)
      result = {}
    result
  end
.,.,

# reduce 107 omitted

# reduce 108 omitted

module_eval(<<'.,.,', 'parser.y', 542)
  def _reduce_109(val, _values, result)
                           kwargs = {}.merge( val[0], val[1], val[2] )
                       @tree << MatchLine.new( **kwargs )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 547)
  def _reduce_110(val, _values, result)
                           kwargs = {}.merge( val[0], val[1] )
                       @tree << MatchLine.new( **kwargs )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 554)
  def _reduce_111(val, _values, result)
                             kwargs = {}.merge( val[0], val[1] )
                         @tree << MatchLineBye.new( **kwargs )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 559)
  def _reduce_112(val, _values, result)
                             kwargs = {}.merge( val[0], val[1] )
                         @tree << MatchLineWalkover.new( **kwargs )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 571)
  def _reduce_113(val, _values, result)
                          kwargs = {}.merge( val[0] )
                      @tree << MatchLine.new( **kwargs )

                      kwargs = val[2]
                      @tree << GoalLine.new( **kwargs )

    result
  end
.,.,

# reduce 114 omitted

module_eval(<<'.,.,', 'parser.y', 594)
  def _reduce_115(val, _values, result)
     result = {}.merge( val[0], val[1])
    result
  end
.,.,

# reduce 116 omitted

# reduce 117 omitted

module_eval(<<'.,.,', 'parser.y', 599)
  def _reduce_118(val, _values, result)
     result = {}.merge( val[0], val[1])
    result
  end
.,.,

# reduce 119 omitted

module_eval(<<'.,.,', 'parser.y', 601)
  def _reduce_120(val, _values, result)
     result = {}.merge( val[0], val[1])
    result
  end
.,.,

# reduce 121 omitted

# reduce 122 omitted

module_eval(<<'.,.,', 'parser.y', 606)
  def _reduce_123(val, _values, result)
     result = {}.merge( val[0], val[1])
    result
  end
.,.,

# reduce 124 omitted

module_eval(<<'.,.,', 'parser.y', 617)
  def _reduce_125(val, _values, result)
     result = {}
    result
  end
.,.,

# reduce 126 omitted

module_eval(<<'.,.,', 'parser.y', 621)
  def _reduce_127(val, _values, result)
                         result = {}.merge( val[0], val[1], val[2] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 625)
  def _reduce_128(val, _values, result)
                       result = {}.merge( val[0], val[1], val[2] )

    result
  end
.,.,

# reduce 129 omitted

# reduce 130 omitted

# reduce 131 omitted

# reduce 132 omitted

# reduce 133 omitted

# reduce 134 omitted

# reduce 135 omitted

module_eval(<<'.,.,', 'parser.y', 652)
  def _reduce_136(val, _values, result)
                          result = { team: val[0].as_str }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 661)
  def _reduce_137(val, _values, result)
                          result = { team1: val[0].as_str,
                                 team2: val[2].as_str }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 679)
  def _reduce_138(val, _values, result)
                          kwargs = { score: val[1].as_hash }.merge( val[0] )
                      @tree << MatchLineLegs.new( **kwargs )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 720)
  def _reduce_139(val, _values, result)
                             @tree << GoalLine.new( **val[1] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 737)
  def _reduce_140(val, _values, result)
      result = { goals1: val[0],
                                                               goals2: [] }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 740)
  def _reduce_141(val, _values, result)
      result = { goals1: val[0],
                                                               goals2: [] }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 743)
  def _reduce_142(val, _values, result)
      result = { goals1: [],
                                                              goals2: val[1] }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 746)
  def _reduce_143(val, _values, result)
      result = { goals1: val[0],
                                                              goals2: val[2] }

    result
  end
.,.,

# reduce 144 omitted

# reduce 145 omitted

# reduce 146 omitted

# reduce 147 omitted

# reduce 148 omitted

# reduce 149 omitted

# reduce 150 omitted

# reduce 151 omitted

module_eval(<<'.,.,', 'parser.y', 762)
  def _reduce_152(val, _values, result)
     result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 763)
  def _reduce_153(val, _values, result)
     result.push( val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 771)
  def _reduce_154(val, _values, result)
                           result = Goal.new( player:  val[0].as_str,
                                          minutes: val[1] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 776)
  def _reduce_155(val, _values, result)
                            ### todo/check:
                        ##    auto convert/expand
                        ##    count to minutes - why? why not?
                        ##  todo/fix - pass in empty minutes ary [] - why? why not?
                        result = Goal.new( player: val[0].as_str,
                                           count:  val[1].as_hash )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 785)
  def _reduce_156(val, _values, result)
                            result = Goal.new( player: val[0].as_str,
                                           minutes: [] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 792)
  def _reduce_157(val, _values, result)
    
    result
  end
.,.,

# reduce 158 omitted

module_eval(<<'.,.,', 'parser.y', 795)
  def _reduce_159(val, _values, result)
      result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 796)
  def _reduce_160(val, _values, result)
      result.push( val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 800)
  def _reduce_161(val, _values, result)
                                 result = GoalMinute.new( **val[0].as_hash )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 817)
  def _reduce_162(val, _values, result)
                                 @tree << GoalLineAlt.new( goals: val[1] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 821)
  def _reduce_163(val, _values, result)
     result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 824)
  def _reduce_164(val, _values, result)
     result.push( val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 830)
  def _reduce_165(val, _values, result)
                               result = GoalAlt.new( score:   val[0].as_ary,
                                                 player:  val[1].as_str )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 835)
  def _reduce_166(val, _values, result)
                               goal_minute = GoalMinute.new( **val[2].as_hash )

                           result = GoalAlt.new( score:     val[0].as_ary,
                                                 player:    val[1].as_str,
                                                 minute:    goal_minute.to_minute,
                                                 goal_type: goal_minute.to_goal_type )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 844)
  def _reduce_167(val, _values, result)
                               result = GoalAlt.new( score:     val[0].as_ary,
                                                 player:    val[1].as_str,
                                                 goal_type: GoalType.new( **val[2].as_hash ))

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 854)
  def _reduce_168(val, _values, result)
                               result = GoalAlt.new( player:  val[0].as_str,
                                                 score:   val[1].as_ary )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 859)
  def _reduce_169(val, _values, result)
                               goal_minute = GoalMinute.new( **val[1].as_hash )

                           result = GoalAlt.new( player:    val[0].as_str,
                                                 minute:    goal_minute.to_minute,
                                                 goal_type: goal_minute.to_goal_type,
                                                 score:     val[2].as_ary )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 868)
  def _reduce_170(val, _values, result)
                               result = GoalAlt.new( player:    val[0].as_str,
                                                 goal_type: GoalType.new( **val[1].as_hash ),
                                                 score:     val[2].as_ary )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 880)
  def _reduce_171(val, _values, result)
                                 @tree << GoalLineCompat.new( goals: val[1] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 884)
  def _reduce_172(val, _values, result)
     result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 886)
  def _reduce_173(val, _values, result)
     result.push( val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 907)
  def _reduce_174(val, _values, result)
                               result = GoalCompat.new( minute:  Minute.new(**val[0].as_hash),
                                                    player:  val[1].as_str,
                                                    score:  val[2].as_ary )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 913)
  def _reduce_175(val, _values, result)
                               result = GoalCompat.new( minute: Minute.new(**val[0].as_hash),
                                                    player: val[1].as_str,
                                                    goal_type: GoalType.new( **val[2].as_hash ),
                                                    score:  val[3].as_ary )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 920)
  def _reduce_176(val, _values, result)
                               result = GoalCompat.new( minute:  Minute.new(**val[0].as_hash),
                                                    score:  val[1].as_ary,
                                                    player:  val[2].as_str )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 926)
  def _reduce_177(val, _values, result)
                               result = GoalCompat.new( minute: Minute.new(**val[0].as_hash),
                                                    score:  val[1].as_ary,
                                                    player: val[2].as_str,
                                                    goal_type: GoalType.new( **val[3].as_hash ))

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 947)
  def _reduce_178(val, _values, result)
                                     @tree << AttendanceLine.new( att: val[1].as_int )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 957)
  def _reduce_179(val, _values, result)
                                   @tree << RefereeLine.new( referees: val[1] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 960)
  def _reduce_180(val, _values, result)
      result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 961)
  def _reduce_181(val, _values, result)
      result.push( val[2] )
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 964)
  def _reduce_182(val, _values, result)
      result = Referee.new( name: val[0].as_str )
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 966)
  def _reduce_183(val, _values, result)
      result = Referee.new( name: val[0].as_str, country: val[1].as_str )
    result
  end
.,.,

# reduce 184 omitted

module_eval(<<'.,.,', 'parser.y', 972)
  def _reduce_185(val, _values, result)
                                     @tree << AttendanceLine.new( att: val[2].as_int )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 983)
  def _reduce_186(val, _values, result)
                                   @tree << CardsLine.new( type: 'Y', bookings: val[1] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 987)
  def _reduce_187(val, _values, result)
                                   @tree << CardsLine.new( type: 'R', bookings: val[1] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 991)
  def _reduce_188(val, _values, result)
                                   @tree << CardsLine.new( type: 'Y/R', bookings: val[1] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 997)
  def _reduce_189(val, _values, result)
                                   @tree << CardsLine.new( type: 'SENTOFF', bookings: val[1] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1009)
  def _reduce_190(val, _values, result)
     result = { bookings:  val[0] }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1010)
  def _reduce_191(val, _values, result)
     result = { bookings1: val[0],
                                                             bookings2: []}
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1012)
  def _reduce_192(val, _values, result)
     result = { bookings1: [],
                                                             bookings2: val[1]}
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1014)
  def _reduce_193(val, _values, result)
     result = { bookings1: val[0],
                                                             bookings2: val[2]}
    result
  end
.,.,

# reduce 194 omitted

# reduce 195 omitted

# reduce 196 omitted

# reduce 197 omitted

module_eval(<<'.,.,', 'parser.y', 1023)
  def _reduce_198(val, _values, result)
      result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1026)
  def _reduce_199(val, _values, result)
                                result.push( val[2] )

    result
  end
.,.,

# reduce 200 omitted

# reduce 201 omitted

# reduce 202 omitted

module_eval(<<'.,.,', 'parser.y', 1035)
  def _reduce_203(val, _values, result)
     result = Booking.new( name: val[0].as_str )
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1037)
  def _reduce_204(val, _values, result)
     result = Booking.new( name:   val[0].as_str,
                                                      minute: Minute.new(**val[1].as_hash) )
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1044)
  def _reduce_205(val, _values, result)
                                   @tree << PenaltiesLine.new( penalties: val[1] )

    result
  end
.,.,

# reduce 206 omitted

# reduce 207 omitted

# reduce 208 omitted

# reduce 209 omitted

module_eval(<<'.,.,', 'parser.y', 1054)
  def _reduce_210(val, _values, result)
      result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1055)
  def _reduce_211(val, _values, result)
      result.push( val[2] )
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1061)
  def _reduce_212(val, _values, result)
                                     result = Penalty.new( score: val[0].as_ary,
                                                       name:  val[1].as_str )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1066)
  def _reduce_213(val, _values, result)
                                     result = Penalty.new( score: val[0].as_ary,
                                                       name:  val[1].as_str,
                                                       note:  val[2].as_str )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1072)
  def _reduce_214(val, _values, result)
                                     result = Penalty.new( name: val[0].as_str )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1076)
  def _reduce_215(val, _values, result)
                                     result = Penalty.new( name: val[0].as_str,
                                                       note: val[1].as_str )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1088)
  def _reduce_216(val, _values, result)
                              kwargs = { team:    val[0].as_str,
                                     lineup:  val[1]  }.merge( val[2] )
                          @tree << LineupLine.new( **kwargs )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1097)
  def _reduce_217(val, _values, result)
     result = {}
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1099)
  def _reduce_218(val, _values, result)
      result = { coach: val[2].as_str }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1101)
  def _reduce_219(val, _values, result)
      result = { coach: val[3].as_str }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1103)
  def _reduce_220(val, _values, result)
      result = { coach: val[2].as_str }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1105)
  def _reduce_221(val, _values, result)
      result = { coach: val[3].as_str }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1109)
  def _reduce_222(val, _values, result)
     result = ','
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1110)
  def _reduce_223(val, _values, result)
     result = ','
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1111)
  def _reduce_224(val, _values, result)
     result = '-'
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1112)
  def _reduce_225(val, _values, result)
     result = '-'
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1117)
  def _reduce_226(val, _values, result)
                           ## note - value must be DOUBLE [[]] nested in array
                       ##    allows formations (e.g. 4-3-3 or such)
                       ##   via dash (-) separator, see below!
                       result = [[val[0]]]

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1124)
  def _reduce_227(val, _values, result)
                           ## note - if lineup_sep is dash (-) start a new sub array!!
                       if val[1] == '-'
                          result << [val[2]]
                       else
                          result[-1] << val[2]
                       end

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1135)
  def _reduce_228(val, _values, result)
                                  kwargs = { name: val[0].as_str }.merge( val[1], val[2], val[3] )
                              result = Lineup.new( **kwargs )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1142)
  def _reduce_229(val, _values, result)
     result = {}
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1143)
  def _reduce_230(val, _values, result)
     result = { captain: true }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1166)
  def _reduce_231(val, _values, result)
                                 _trace( "REDUCE => lineup_sub_props : PROP_NAME  opt_cards" )
                             result = { name: val[0].as_str }.merge( val[1] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1173)
  def _reduce_232(val, _values, result)
                                 _trace( "REDUCE => lineup_sub_props : PROP_NAME  MINUTE  opt_cards" )
                              result = { name:   val[0].as_str,
                                         minute: Minute.new( **val[1].as_hash )
                                       }.merge( val[2])

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1183)
  def _reduce_233(val, _values, result)
                                 _trace( "REDUCE => lineup_sub_props : PROP_NAME  cards  MINUTE" )
                              result = { name:   val[0].as_str,
                                         minute: Minute.new( **val[2].as_hash ),
                                         cards:  val[1]
                                       }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1194)
  def _reduce_234(val, _values, result)
                                 _trace( "REDUCE => lineup_sub_props : MINUTE  PROP_NAME  opt_cards" )

                               result = { name:   val[1].as_str,
                                          minute: Minute.new( **val[0].as_hash )
                                        }.merge( val[2])

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1206)
  def _reduce_235(val, _values, result)
      result = {}
    result
  end
.,.,

# reduce 236 omitted

module_eval(<<'.,.,', 'parser.y', 1214)
  def _reduce_237(val, _values, result)
      result = val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1218)
  def _reduce_238(val, _values, result)
                                       _trace( "REDUCE => lineup_sub_contents : line_sub_props" )
                                   kwargs  = {}.merge( val[0] )
                                   minute  = kwargs.delete( :minute )
                                   sub = Sub.new(  sub:     Lineup.new( **kwargs ),
                                                   minute:  minute )
                                   result = { sub: sub }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1227)
  def _reduce_239(val, _values, result)
                                        _trace( "REDUCE => lineup_sub_contents : line_sub_props lineup_sub" )
                                   kwargs  = {}.merge( val[0] ).merge( val[1] )
                                   minute  = kwargs.delete( :minute )
                                   sub = Sub.new(  sub:     Lineup.new( **kwargs ),
                                                   minute:  minute )
                                   result = { sub: sub }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1237)
  def _reduce_240(val, _values, result)
     result = {}
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1238)
  def _reduce_241(val, _values, result)
     result = { cards: val[0] }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1248)
  def _reduce_242(val, _values, result)
      result =  [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1249)
  def _reduce_243(val, _values, result)
      result =  [val[0],val[1]]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1250)
  def _reduce_244(val, _values, result)
      result =  [val[0],val[1]]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1251)
  def _reduce_245(val, _values, result)
      result =  [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1252)
  def _reduce_246(val, _values, result)
      result =  [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1258)
  def _reduce_247(val, _values, result)
                    minute = val[0].as_hash.empty? ? nil : Minute.new( **val[0].as_hash )
                result = Card.new( name: 'Y',  minute: minute )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1264)
  def _reduce_248(val, _values, result)
                    minute = val[0].as_hash.empty? ? nil : Minute.new( **val[0].as_hash )
                result = Card.new( name: 'Y/R',  minute: minute )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1270)
  def _reduce_249(val, _values, result)
                    minute = val[0].as_hash.empty? ? nil : Minute.new( **val[0].as_hash )
                result = Card.new( name: 'R',  minute: minute )

    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

end   # class RaccMatchParser
