require 'hoe'
require './lib/fbtxt/document/version.rb'



Hoe.spec 'fbtxt-document' do

  self.version = Fbtxt::Module::Document::VERSION

  self.summary = "fbtxt-document - football.txt match readers (incl. Fbtxt::Document) and more"
  self.description = summary

  self.urls = { home: 'https://github.com/sportdb/sport.db' }

  self.author = 'Gerald Bauer'
  self.email  = 'gerald.bauer@gmail.com'

  # switch extension to .markdown for gihub formatting
  self.readme_file  = 'README.md'
  self.history_file = 'CHANGELOG.md'

  self.licenses = ['Public Domain']

  self.extra_deps = [
       ['fbtxt-parser',    '>= 0.9.0'],
       ['season-formats',  '>= 0.1.0'],
   ##    ['logutils',        '>= 0.6.1'],
  ]

  self.spec_extras = {
    required_ruby_version: '>= 3.1.0'
  }
end
