#!/usr/bin/env ruby


##
##  fix-fix-fix
##    replaced by fbdoc  (remvoe fbx) - why? why not?


## tip: to test run:
##   $ ruby -I ./lib  bin/fbx


## quick hack
##   if available always use latest (local) source version
$LOAD_PATH.unshift( '/sports/sportdb/sport.db.v2/parser/lib' )
$LOAD_PATH.unshift( '/sports/sportdb/sport.db.v2/document/lib' )



## our own code
require 'fbtok'


Fbx.main