#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.8.1
# from Racc grammar file "parser.y".
#

require 'racc/parser.rb'
class NanoBasicParser < Racc::Parser

module_eval(<<'...end parser.y/module_eval...', 'parser.y', 45)
  def parse(tokens)
    @tokens = tokens
    do_parse
  end

  def next_token
    @tokens.shift
  end
...end parser.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
    26,     4,    21,    22,    23,    24,    25,    21,    22,    23,
    24,    25,    21,    22,    23,    24,    25,     8,     9,    10,
    11,    15,    17,    16,    15,    17,    16,    15,    17,    16,
    15,    17,    16,    15,    17,    16,    15,    17,    16,    15,
    17,    16,    15,    17,    16,    21,    22,    21,    22,    21,
    22,     5,     4,    12,    13,    18,    20,    33 ]

racc_action_check = [
    19,     0,    19,    19,    19,    19,    19,    14,    14,    14,
    14,    14,    27,    27,    27,    27,    27,     4,     4,     4,
     4,     9,     9,     9,    11,    11,    11,    20,    20,    20,
    21,    21,    21,    22,    22,    22,    23,    23,    23,    24,
    24,    24,    25,    25,    25,    30,    30,    31,    31,    32,
    32,     1,     2,     5,     8,    10,    13,    26 ]

racc_action_pointer = [
    -1,    51,    50,   nil,    12,    53,   nil,   nil,    51,    19,
    53,    22,   nil,    46,    -4,   nil,   nil,   nil,   nil,    -9,
    25,    28,    31,    34,    37,    40,    55,     1,   nil,   nil,
    34,    36,    38,   nil ]

racc_action_default = [
   -17,   -17,    -1,    -3,   -17,   -17,    -2,    -4,   -17,   -17,
   -17,   -17,    34,   -17,    -6,    -9,   -10,   -11,    -7,   -17,
   -17,   -17,   -17,   -17,   -17,   -17,   -17,    -5,   -12,   -13,
   -14,   -15,   -16,    -8 ]

racc_goto_table = [
    14,     3,    19,     6,     1,     2,     7,   nil,   nil,   nil,
   nil,    27,    28,    29,    30,    31,    32 ]

racc_goto_check = [
     5,     3,     5,     3,     1,     2,     4,   nil,   nil,   nil,
   nil,     5,     5,     5,     5,     5,     5 ]

racc_goto_pointer = [
   nil,     4,     5,     1,     2,    -9 ]

racc_goto_default = [
   nil,   nil,   nil,   nil,   nil,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 17, :_reduce_1,
  2, 18, :_reduce_2,
  1, 18, :_reduce_3,
  2, 19, :_reduce_4,
  4, 20, :_reduce_5,
  2, 20, :_reduce_6,
  2, 20, :_reduce_7,
  4, 20, :_reduce_8,
  1, 21, :_reduce_9,
  1, 21, :_reduce_10,
  1, 21, :_reduce_11,
  3, 21, :_reduce_12,
  3, 21, :_reduce_13,
  3, 21, :_reduce_14,
  3, 21, :_reduce_15,
  3, 21, :_reduce_16 ]

racc_reduce_n = 17

racc_shift_n = 34

racc_token_table = {
  false => 0,
  :error => 1,
  :NUMBER => 2,
  :IDENTIFIER => 3,
  :STRING => 4,
  :LET => 5,
  :PRINT => 6,
  :GOTO => 7,
  :IF => 8,
  :THEN => 9,
  :EQ => 10,
  :PLUS => 11,
  :MINUS => 12,
  :LT => 13,
  :GT => 14,
  :EQ_COMP => 15 }

racc_nt_base = 16

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]
Ractor.make_shareable(Racc_arg) if defined?(Ractor)

Racc_token_to_s_table = [
  "$end",
  "error",
  "NUMBER",
  "IDENTIFIER",
  "STRING",
  "LET",
  "PRINT",
  "GOTO",
  "IF",
  "THEN",
  "EQ",
  "PLUS",
  "MINUS",
  "LT",
  "GT",
  "EQ_COMP",
  "$start",
  "program",
  "lines",
  "line",
  "statement",
  "expr" ]
Ractor.make_shareable(Racc_token_to_s_table) if defined?(Ractor)

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'parser.y', 13)
  def _reduce_1(val, _values, result)
     result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 16)
  def _reduce_2(val, _values, result)
     result = val + [val]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 17)
  def _reduce_3(val, _values, result)
     result = [val]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 20)
  def _reduce_4(val, _values, result)
     result = { line_num: val, stmt: val }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 23)
  def _reduce_5(val, _values, result)
     result = { type: :let, var: val, val: val }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 24)
  def _reduce_6(val, _values, result)
     result = { type: :print, val: val }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 25)
  def _reduce_7(val, _values, result)
     result = { type: :goto, target: val }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 26)
  def _reduce_8(val, _values, result)
     result = { type: :if, condition: val, target: val }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 29)
  def _reduce_9(val, _values, result)
     result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 30)
  def _reduce_10(val, _values, result)
     result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 31)
  def _reduce_11(val, _values, result)
     result = { type: :variable, name: val }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 32)
  def _reduce_12(val, _values, result)
     result = { type: :add, left: val, right: val }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 33)
  def _reduce_13(val, _values, result)
     result = { type: :sub, left: val, right: val }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 34)
  def _reduce_14(val, _values, result)
     result = { type: :lt, left: val, right: val }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 35)
  def _reduce_15(val, _values, result)
     result = { type: :gt, left: val, right: val }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 36)
  def _reduce_16(val, _values, result)
     result = { type: :eq_comp, left: val, right: val }
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

end   # class NanoBasicParser
