#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.8.1
# from Racc grammar file "parser.y".
#

require 'racc/parser.rb'
class NanoBasicParser < Racc::Parser

module_eval(<<'...end parser.y/module_eval...', 'parser.y', 46)
  def parse(tokens)
    @tokens = tokens
    do_parse
  end

  def next_token

    tok = @tokens.shift

    ##  convert to racc format single char literal tokens e.g. '@' etc.
    ##                  note - literal token MUST be string (NOT symbol)
    ##    note - racc expects array with to items
    ##               -  item[0] is the token id
    ##               -  item[1] is the token value

    ## note - returns nil for end-of-file !!!
    tok = [tok.type, tok.value]   if tok
  end
...end parser.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
    24,    25,    26,    22,    23,    16,    16,    16,    18,    18,
    18,     4,    27,    17,    17,    17,    16,    16,    16,    18,
    18,    18,    22,    23,    17,    17,    17,    16,    16,     5,
    18,    18,    22,    23,     4,    17,    17,     8,    12,     9,
    10,    11,    24,    25,    26,    22,    23,    24,    25,    26,
    22,    23,    22,    23,    13,    14,    19,    21,    34 ]

racc_action_check = [
    20,    20,    20,    20,    20,     9,    11,    21,     9,    11,
    21,     0,    20,     9,    11,    21,    22,    23,    24,    22,
    23,    24,    31,    31,    22,    23,    24,    25,    26,     1,
    25,    26,    32,    32,     2,    25,    26,     4,     5,     4,
     4,     4,    15,    15,    15,    15,    15,    28,    28,    28,
    28,    28,    33,    33,     7,     8,    10,    14,    27 ]

racc_action_pointer = [
     4,    29,    27,   nil,    28,    38,   nil,    46,    45,    -2,
    49,    -1,   nil,   nil,    53,    40,   nil,   nil,   nil,   nil,
    -2,     0,     9,    10,    11,    20,    21,    51,    45,   nil,
   nil,    17,    27,    47,   nil ]

racc_action_default = [
   -17,   -17,    -1,    -2,   -17,   -17,    -3,   -17,   -17,   -17,
   -17,   -17,    35,    -4,   -17,    -6,    -9,   -10,   -11,    -7,
   -17,   -17,   -17,   -17,   -17,   -17,   -17,   -17,    -5,   -12,
   -13,   -14,   -15,   -16,    -8 ]

racc_goto_table = [
    15,     3,    20,     6,     1,     2,     7,   nil,   nil,   nil,
   nil,   nil,    28,    29,    30,    31,    32,    33 ]

racc_goto_check = [
     5,     3,     5,     3,     1,     2,     4,   nil,   nil,   nil,
   nil,   nil,     5,     5,     5,     5,     5,     5 ]

racc_goto_pointer = [
   nil,     4,     5,     1,     2,    -9 ]

racc_goto_default = [
   nil,   nil,   nil,   nil,   nil,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 17, :_reduce_1,
  1, 18, :_reduce_2,
  2, 18, :_reduce_3,
  3, 19, :_reduce_4,
  4, 20, :_reduce_5,
  2, 20, :_reduce_6,
  2, 20, :_reduce_7,
  4, 20, :_reduce_8,
  1, 21, :_reduce_9,
  1, 21, :_reduce_10,
  1, 21, :_reduce_11,
  3, 21, :_reduce_12,
  3, 21, :_reduce_13,
  3, 21, :_reduce_14,
  3, 21, :_reduce_15,
  3, 21, :_reduce_16 ]

racc_reduce_n = 17

racc_shift_n = 35

racc_token_table = {
  false => 0,
  :error => 1,
  "<" => 2,
  ">" => 3,
  "=" => 4,
  "+" => 5,
  "-" => 6,
  :NUMBER => 7,
  "\n" => 8,
  :LET => 9,
  :VARIABLE => 10,
  :PRINT => 11,
  :GOTO => 12,
  :IF => 13,
  :THEN => 14,
  :STRING => 15 }

racc_nt_base = 16

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]
Ractor.make_shareable(Racc_arg) if defined?(Ractor)

Racc_token_to_s_table = [
  "$end",
  "error",
  "\"<\"",
  "\">\"",
  "\"=\"",
  "\"+\"",
  "\"-\"",
  "NUMBER",
  "\"\\n\"",
  "LET",
  "VARIABLE",
  "PRINT",
  "GOTO",
  "IF",
  "THEN",
  "STRING",
  "$start",
  "program",
  "lines",
  "line",
  "statement",
  "expr" ]
Ractor.make_shareable(Racc_token_to_s_table) if defined?(Ractor)

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'parser.y', 12)
  def _reduce_1(val, _values, result)
     result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 15)
  def _reduce_2(val, _values, result)
     result = [val]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 16)
  def _reduce_3(val, _values, result)
     result = val + [val]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 20)
  def _reduce_4(val, _values, result)
     result = { line_num: val, stmt: val }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 24)
  def _reduce_5(val, _values, result)
     result = { type: :let, var: val, val: val }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 25)
  def _reduce_6(val, _values, result)
     result = { type: :print, val: val }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 26)
  def _reduce_7(val, _values, result)
     result = { type: :goto, target: val }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 27)
  def _reduce_8(val, _values, result)
     result = { type: :if, condition: val, target: val }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 30)
  def _reduce_9(val, _values, result)
     result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 31)
  def _reduce_10(val, _values, result)
     result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 32)
  def _reduce_11(val, _values, result)
     result = { type: :variable, name: val }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 33)
  def _reduce_12(val, _values, result)
     result = { type: :add, left: val, right: val }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 34)
  def _reduce_13(val, _values, result)
     result = { type: :sub, left: val, right: val }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 35)
  def _reduce_14(val, _values, result)
     result = { type: :lt, left: val, right: val }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 36)
  def _reduce_15(val, _values, result)
     result = { type: :gt, left: val, right: val }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 37)
  def _reduce_16(val, _values, result)
     result = { type: :eq_comp, left: val, right: val }
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

end   # class NanoBasicParser
