require 'cocos'




require_relative 'parser/version'


require_relative 'parser/debuggable'    ## generic debug/logger helper



##
## add shared/most basic regexes here
## todo - use ANY_RE  to token_commons or such - for shared by many?
module SportDb
class Lexer

## general catch-all  (RECOMMENDED (ALWAYS) use as last entry in union)
##   to avoid advance of pos match!!!
ANY_RE = %r{
               (?<any> .)
          }ix

SPACES_RE = %r{
                  (?<spaces> [ ]{2,})
                | (?<space>  [ ])
             }ix


end # class Lexer
end # module SportDb


require_relative 'parser/token-score'
require_relative 'parser/token-score_full'
require_relative 'parser/token-score_fuller'
require_relative 'parser/token-score_legs'
require_relative 'parser/token-score--helpers'

require_relative 'parser/token-time'
require_relative 'parser/token-date--names'
require_relative 'parser/token-date'
require_relative 'parser/token-date_duration'
require_relative 'parser/token-date--helpers'

require_relative 'parser/token-text'
require_relative 'parser/token-prop'    ## team prop(erty) mode (note - must be before token)
require_relative 'parser/token-prop_name'    ## a.k.a token-text_ii
require_relative 'parser/token-status'
require_relative 'parser/token-status_inline'
require_relative 'parser/token-note'
require_relative 'parser/token-goals'
require_relative 'parser/token-goals--helpers'
require_relative 'parser/token-geo'
require_relative 'parser/token-group'
require_relative 'parser/token-round'
require_relative 'parser/token'





require_relative 'parser/lexer_buffer'   ## incl. Tokens (aka TokenBuffer)
require_relative 'parser/lexer_token'

require_relative 'parser/lexer-prep_doc'
require_relative 'parser/lexer-prep_line'

require_relative 'parser/lexer-logger'   ## e.g. _trace, _warn, _info, etc.
require_relative 'parser/lexer-tokenize'
require_relative 'parser/lexer-on_round_def'
require_relative 'parser/lexer-on_group_def'
require_relative 'parser/lexer-on_prop_misc'
require_relative 'parser/lexer-on_prop_lineup'
require_relative 'parser/lexer-on_prop_penalties'
require_relative 'parser/lexer-on_goal'
require_relative 'parser/lexer-on_top'
require_relative 'parser/lexer'


## note - use "embeded" racc parser runtime
##    MUST uncomment  require 'racc/parser'  in generated parser!!!
require_relative 'parser/parser-runtime'

require_relative 'parser/parser'   ## auto-generated by racc (from parser.y)
require_relative 'parser/parser-top'

require_relative 'parser/parse_tree--core'    ## incl. core extensions eg. as_json on Object/Array/Hash
require_relative 'parser/parse_tree'
require_relative 'parser/parse_tree-match'
require_relative 'parser/parse_tree-props'


## deprecated - remove old RaccMatchParser name sooner than later!!
##    use Fbtxt.parse for "public" api
RaccMatchParser = SportDb::Parser



###
#  make parser api (easily) available - why? why not?
#
#  use Fbtxt.parse( txt ) &&
#      Fbtxt.lex( txt)            -- or Fbtxt.tokenize?
#
#   Fbtxt.lex( txt,
#                 flatten: true|false,        ## keep nested [] for lines (no NEWLINE tokens)
#                 transform: true|false )     ## builtin transforms eg. merge DATE & TIME => DATETIME, etc.
#
#   how to deal with errors?
##    always return   [tokens, errors] or such?
##           or return a Result struct - why? why not?



module Fbtxt

def self.lex( txt )   ## returns SportDb::LexerResult (ok?/tokens/errors)
  # lexer = SportDb::Lexer.new
  # lexer.tokenize( txt )
  puts "to be done; SOON!"
end


def self.parse( txt )   ## returns SportDb::ParserResult (ok?/tree/errors)
  # parser = SportDb::Parser.new
  # parser.parse( txt )
  puts "to be done; SOON!"
end


class Document
   def self.parse( txt )      ## or use/add Fbtxt.parse_doc/load - why? why not??
     puts "to be done; SOON!"
   end

   def self.read( path )       ## or use/add Fbtxt.read_doc/load_file - why? why not??
     puts "to be done; SOON!"
   end
end  # class Document
end #  module Fbtxt






puts SportDb::Module::Parser.banner    # say hello
