require 'hoe'
require './lib/fbtxt/parser/version.rb'


Hoe.spec 'fbtxt-parser' do

  self.version = Fbtxt::Module::Parser::VERSION

  self.summary = "fbtxt-parser - football.txt match parser (& tokenizer)"
  self.description = summary

  self.urls = { home: 'https://github.com/sportdb/sport.db' }

  self.author = 'Gerald Bauer'
  self.email  = 'gerald.bauer@gmail.com'

  # switch extension to .markdown for gihub formatting
  self.readme_file  = 'README.md'
  self.history_file = 'CHANGELOG.md'

  self.licenses = ['Public Domain']

  self.extra_deps = [
       ['cocos', '>= 0.4.1'],
  ]

  self.spec_extras = {
    required_ruby_version: '>= 3.1.0'
  }
end



###
## add our own g task to build parser.rb (via racc & erb)

desc 'Generate parser.rb (via racc & erb)'
task g: 'lib/fbtxt/parser/parser.rb'


file 'lib/fbtxt/parser/parser.rb' => 'fbtxt/parser.y' do |t|
  puts "  [racc] generate parser.rb from parser.y"
  ## sh "racc -v -o #{t.name} #{t.source}"
  sh "racc -o #{t.name} #{t.source}"
end


file 'fbtxt/parser.y' => FileList['fbtxt/grammar/*.y'] do |t|
  puts "  [erb] generate parser.y; merge grammar/*"
  Dir.chdir( 'fbtxt' ) do
    sh "erb parser.y.erb > parser.y"
  end
end
