#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.8.1
# from Racc grammar file "parser.y".
#

## require 'racc/parser.rb'
module Fbtxt
  class Parser < Racc::Parser
##### State transition tables begin ###

racc_action_table = [
    28,    27,    29,    30,    31,    32,    33,   239,   250,   257,
    34,    45,   250,    35,    36,    37,   242,    38,    39,    40,
    43,    44,   230,   250,   154,   170,   128,    80,    37,   177,
    38,    39,    40,   168,    44,   257,   110,   111,   112,    47,
    48,    49,    51,   224,    52,   226,   221,    82,   155,   231,
   259,   232,    68,   247,    47,    48,    49,    52,   114,    69,
   238,    70,  -205,    71,  -195,   221,   178,    72,  -195,   241,
    73,    74,    75,    76,    77,   245,   260,   248,    78,  -195,
    79,    28,    27,    29,    30,    31,    32,    33,  -206,  -142,
   -98,    34,    45,   305,    35,    36,    37,   170,    38,    39,
    40,    43,    44,    86,   307,   168,   219,   220,  -142,   128,
   170,   236,   221,   221,   294,   288,   170,   289,   168,   177,
    47,    48,    49,    51,   168,    52,   133,   177,   134,   123,
   124,   133,   133,    68,   306,   235,   154,    47,    48,    49,
    69,    44,    70,   295,    71,    90,   304,    44,    72,   227,
   233,    73,    74,    75,    76,    77,   178,    83,    84,    78,
   155,    79,    91,   132,   178,   134,    44,    44,   132,   132,
   340,   134,    94,    95,    97,    98,    99,   100,   104,    44,
   101,   102,   103,    93,   105,   106,   107,   108,   115,    52,
    52,   123,   124,   326,   327,   328,   268,    88,    87,   109,
   269,   270,    52,    94,    95,    97,    98,    99,   100,   104,
   116,   101,   102,   103,   336,   105,   106,   107,   108,   117,
   335,   110,   111,   118,   110,   111,   112,   326,   327,   328,
   326,   327,   328,   326,   327,   328,   185,   186,   123,   124,
   123,   124,   284,  -149,   327,   328,   121,   133,   142,    44,
   151,   158,   159,   162,   165,   180,   181,   183,   187,   188,
   189,   190,   191,   192,   193,   194,   195,   196,   197,   198,
   199,   200,   201,   202,    51,   206,   210,   212,    44,   215,
   151,   217,   229,   237,   240,   243,   244,   170,   252,   253,
   254,   255,   256,   263,   264,   267,   271,   272,   273,   275,
   276,   277,   133,   280,   281,   151,   151,   286,   290,   291,
   292,   158,   296,   162,   165,   170,   170,   303,   311,   312,
   316,   226,   318,   319,   267,   329,   332,   342,   343,   332,
   346 ]

racc_action_check = [
     0,     0,     0,     0,     0,     0,     0,   160,   251,   175,
     0,     0,   167,     0,     0,     0,   163,     0,     0,     0,
     0,     0,   155,   299,    69,    74,    55,     1,    59,    78,
    59,    59,    59,    74,    59,   301,    46,    46,    46,     0,
     0,     0,     0,   151,     0,   151,   282,    33,    69,   155,
   175,   155,     0,   167,    55,    55,    55,    59,    46,     0,
   160,     0,   175,     0,   251,   149,    78,     0,   167,   163,
     0,     0,     0,     0,     0,   167,   175,   167,     0,   299,
     0,     2,     2,     2,     2,     2,     2,     2,   301,   282,
   125,     2,     2,   265,     2,     2,     2,    75,     2,     2,
     2,     2,     2,    35,   265,    75,   149,   149,   149,   205,
    76,   158,   152,   156,   235,   229,    77,   229,    76,   261,
     2,     2,     2,     2,    77,     2,    56,   262,   125,   125,
   125,   274,   130,     2,   265,   158,   228,   205,   205,   205,
     2,    56,     2,   235,     2,    41,   265,   130,     2,   152,
   156,     2,     2,     2,     2,     2,   261,    34,    34,     2,
   228,     2,    43,    56,   262,    56,    54,    61,   274,   130,
   335,   130,    45,    45,    45,    45,    45,    45,    45,   145,
    45,    45,    45,    44,    45,    45,    45,    45,    47,    54,
    61,    54,    54,   335,   335,   335,   182,    36,    36,    45,
   182,   182,   145,   128,   128,   128,   128,   128,   128,   128,
    48,   128,   128,   128,   332,   128,   128,   128,   128,    49,
   332,    50,    50,    50,   129,   129,   129,   310,   310,   310,
   340,   340,   340,   342,   342,   342,    89,    89,   137,   137,
   213,   213,   223,   223,   323,   323,    53,    57,    58,    63,
    68,    70,    71,    72,    73,    79,    80,    85,    92,    96,
    97,    98,    99,   100,   101,   102,   103,   104,   105,   106,
   107,   108,   114,   120,   122,   124,   126,   135,   136,   141,
   142,   148,   154,   159,   162,   165,   166,   168,   170,   171,
   172,   173,   174,   177,   178,   179,   184,   187,   193,   208,
   209,   211,   214,   216,   217,   218,   222,   227,   231,   232,
   233,   234,   236,   239,   242,   246,   249,   263,   267,   270,
   280,   285,   295,   296,   309,   313,   321,   336,   337,   338,
   341 ]

racc_action_pointer = [
    -1,    27,    80,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,    39,   148,    95,   188,   nil,   nil,   nil,
   nil,   137,   nil,   154,   160,   148,     6,   176,   198,   207,
   191,   nil,   nil,   244,   144,    14,   119,   240,   199,    12,
   nil,   145,   nil,   227,   nil,   nil,   nil,   nil,   194,    -8,
   188,   187,   184,   185,   -44,    28,    41,    47,    -3,   173,
   256,   nil,   nil,   nil,   nil,   245,   nil,   nil,   nil,   220,
   nil,   nil,   245,   nil,   nil,   nil,   247,   248,   249,   250,
   251,   252,   253,   254,   255,   256,   257,   258,   259,   nil,
   nil,   nil,   nil,   nil,   264,   nil,   nil,   nil,   nil,   nil,
   271,   nil,   231,   nil,   228,    82,   268,   nil,   179,   194,
   125,   nil,   nil,   nil,   nil,   269,   256,   191,   nil,   nil,
   nil,   271,   224,   nil,   nil,   157,   nil,   nil,   231,    52,
   nil,   -14,    99,   nil,   226,   -10,   100,   nil,    79,   217,
    -6,   nil,   214,     3,   nil,   215,   220,    -1,   218,   nil,
   225,   223,   224,   225,   226,    -4,   nil,   224,   224,   226,
   nil,   nil,   188,   nil,   288,   nil,   nil,   274,   nil,   nil,
   nil,   nil,   nil,   263,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    97,   nil,   nil,   291,   292,
   nil,   293,   nil,   193,   295,   nil,   253,   296,   249,   nil,
   nil,   nil,   250,   184,   nil,   nil,   nil,   299,   104,    56,
   nil,   276,   277,   302,   248,    82,   256,   nil,   nil,   244,
   nil,   nil,   245,   nil,   nil,   nil,   246,   nil,   nil,   247,
   nil,    -5,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,    87,    95,   247,   nil,    80,   nil,   235,   nil,   nil,
   307,   nil,   nil,   nil,   124,   nil,   nil,   nil,   nil,   nil,
   312,   nil,    33,   nil,   nil,   262,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   290,   262,   nil,   nil,    10,
   nil,    22,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   255,
   141,   nil,   nil,   317,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   242,   nil,   157,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   151,   nil,   nil,   107,   258,   243,   245,   nil,
   144,   267,   147,   nil,   nil,   nil,   nil,   nil ]

racc_action_default = [
    -1,  -245,    -2,    -3,    -5,    -6,    -7,    -8,    -9,   -10,
   -11,   -12,   -13,   -14,   -15,   -16,   -17,   -18,   -19,   -20,
   -21,   -22,   -23,   -24,   -25,   -26,   -27,   -28,   -29,   -30,
   -31,   -32,   -33,  -245,  -245,  -245,  -245,   -51,   -52,   -53,
   -54,   -55,   -56,  -245,  -245,  -245,  -130,  -245,  -245,  -245,
  -133,   -87,   -94,   -35,  -115,  -245,  -123,   -92,  -129,  -112,
  -114,  -117,  -119,  -120,  -122,  -131,  -132,  -134,  -245,  -245,
  -245,  -245,  -245,  -245,  -245,  -245,  -245,  -245,  -245,  -214,
  -245,    -4,   -34,   -39,   -40,  -245,   -45,   -46,   -47,  -245,
   -57,   -58,   -59,   -60,   -62,   -63,  -245,  -245,  -245,  -245,
  -245,  -245,  -245,  -245,  -245,  -245,  -245,  -245,  -245,  -135,
   -69,   -70,   -76,   -77,  -245,   -82,   -83,   -84,   -85,   -86,
   -36,   -37,   -88,   -96,  -245,  -122,  -245,  -116,  -245,  -130,
  -123,  -129,   -90,   -91,   -95,  -245,  -124,   -98,  -127,  -128,
   -93,  -245,  -245,   -55,  -113,  -115,  -118,  -121,  -245,  -138,
  -144,  -148,  -142,  -155,  -245,  -245,  -142,  -164,  -245,  -245,
  -245,  -174,  -176,  -245,  -179,  -181,  -245,  -187,  -245,  -193,
  -197,  -245,  -245,  -245,  -245,  -201,  -207,  -245,  -211,  -245,
  -215,   348,  -245,   -42,  -245,   -49,   -50,  -245,   -64,   -65,
   -66,   -67,   -68,   -71,   -72,   -73,   -75,   -78,   -79,   -80,
   -81,  -136,   -38,   -89,  -100,  -245,   -97,   -99,  -245,  -245,
  -103,  -245,  -109,   -98,   -92,  -110,  -245,  -245,  -245,  -140,
  -141,  -143,  -245,  -146,  -147,  -151,  -153,  -245,  -245,  -157,
  -160,  -245,  -245,  -245,  -245,  -245,  -245,  -170,  -173,  -245,
  -177,  -178,  -245,  -182,  -183,  -188,  -245,  -191,  -192,  -245,
  -196,  -189,  -198,  -184,  -185,  -186,  -199,  -200,  -202,  -203,
  -204,  -245,  -245,  -209,  -212,  -219,  -221,  -224,   -41,   -43,
  -245,   -48,   -61,   -74,  -105,  -101,  -102,  -108,  -125,  -126,
  -245,  -137,  -139,  -145,  -150,  -245,  -154,  -156,  -158,  -159,
  -161,  -162,  -163,  -165,  -166,  -245,  -168,  -175,  -180,  -190,
  -194,  -201,  -208,  -210,  -213,  -216,  -217,  -218,  -220,  -245,
  -235,  -225,   -44,  -245,  -106,  -107,  -111,  -152,  -167,  -169,
  -222,  -230,  -236,  -237,  -240,  -241,  -242,  -243,  -244,  -104,
  -223,  -231,  -245,  -238,  -239,  -235,  -245,  -245,  -233,  -226,
  -235,  -236,  -235,  -232,  -234,  -227,  -228,  -229 ]

racc_goto_table = [
   140,   175,   164,   161,   157,   153,   141,   225,   129,   131,
   130,   127,   266,   208,   125,   251,   137,   135,   146,   321,
   148,   331,   228,   147,     1,   214,   234,   166,   171,   172,
   173,     3,     2,    81,   122,   120,    85,   182,   344,    89,
   184,   143,   145,    92,   339,   119,   203,   205,   314,   345,
   209,   347,   126,   204,   313,   144,   282,   218,   283,   223,
   285,   152,   156,   160,   163,   246,   300,   174,   261,   302,
   179,   265,   308,   309,   310,   330,   338,   341,   337,   333,
   334,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   137,   211,   nil,   299,   216,   nil,   213,   nil,   nil,   nil,
   nil,   278,   127,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   317,   320,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   140,   129,   131,
   274,   nil,   nil,   279,   287,   nil,   nil,   nil,   293,   nil,
   297,   298,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   301,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   315 ]

racc_goto_check = [
    50,    91,    81,    79,    76,    74,    51,    72,    40,    44,
    58,    65,    97,    55,    37,    83,    37,    61,    65,    99,
    63,   103,    68,    37,     1,    55,    68,    82,    82,    82,
    82,     3,     2,     3,    27,    28,    29,    30,   103,    31,
    32,    33,    36,    38,    99,    43,    47,    48,    49,    99,
    53,    99,    54,    57,    59,    64,    66,    67,    69,    70,
    71,    73,    75,    78,    80,    84,    85,    87,    90,    92,
    93,    94,    95,    96,    98,   100,   101,   102,   104,   106,
   107,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
    37,    61,   nil,    83,    63,   nil,    37,   nil,   nil,   nil,
   nil,    55,    65,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,    72,    97,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    50,    40,    44,
    58,   nil,   nil,    51,    74,   nil,   nil,   nil,    76,   nil,
    79,    81,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,    91,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    50 ]

racc_goto_pointer = [
   nil,    24,    32,    31,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   -19,   -18,     2,
   -48,     3,   -49,   -18,   nil,   nil,   -17,   -40,    -1,   nil,
   -47,   nil,   nil,    -5,   -46,   nil,   nil,   -76,   -75,  -226,
   -57,   -51,   nil,   -75,    -2,  -112,   nil,   -69,   -45,  -220,
   nil,   -39,   nil,   -48,    -4,   -43,  -162,   -92,  -130,  -164,
   -92,  -163,  -144,    -8,   -64,    -8,   -66,   nil,    -9,   -69,
    -9,   -71,   -47,  -153,  -102,  -183,   nil,   -11,   nil,   nil,
  -107,   -77,  -193,    -9,  -108,  -193,  -192,  -167,  -193,  -291,
  -246,  -256,  -258,  -300,  -254,   nil,  -244,  -243 ]

racc_goto_default = [
   nil,   nil,   nil,   nil,     4,     5,     6,     7,     8,     9,
    10,    11,    12,    13,    14,    15,    16,    17,    18,    19,
    20,    21,    22,    23,    24,    25,    26,   nil,   nil,   nil,
   nil,   nil,   nil,    41,    42,    61,    54,    64,   nil,    96,
    46,    65,    66,   113,    58,    50,    67,    59,   nil,   136,
   138,   nil,    63,   139,   207,   nil,    53,   nil,    56,   nil,
    55,   nil,    57,   nil,    60,    62,   149,   nil,   222,   150,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   167,   nil,   169,   249,   nil,   258,   262,
   nil,   nil,   176,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   322,   nil,   nil,   323,   325,   324 ]

racc_reduce_table = [
  0, 0, :racc_error,
  0, 90, :_reduce_1,
  1, 90, :_reduce_none,
  1, 91, :_reduce_none,
  2, 91, :_reduce_none,
  1, 92, :_reduce_none,
  1, 92, :_reduce_none,
  1, 92, :_reduce_none,
  1, 92, :_reduce_none,
  1, 92, :_reduce_none,
  1, 92, :_reduce_none,
  1, 92, :_reduce_none,
  1, 92, :_reduce_none,
  1, 92, :_reduce_none,
  1, 92, :_reduce_none,
  1, 92, :_reduce_none,
  1, 92, :_reduce_none,
  1, 92, :_reduce_none,
  1, 92, :_reduce_none,
  1, 92, :_reduce_none,
  1, 92, :_reduce_none,
  1, 92, :_reduce_none,
  1, 92, :_reduce_none,
  1, 92, :_reduce_none,
  1, 92, :_reduce_none,
  1, 92, :_reduce_none,
  1, 92, :_reduce_none,
  1, 92, :_reduce_none,
  1, 92, :_reduce_28,
  1, 92, :_reduce_29,
  1, 93, :_reduce_30,
  1, 93, :_reduce_31,
  1, 93, :_reduce_32,
  1, 103, :_reduce_33,
  2, 102, :_reduce_34,
  0, 116, :_reduce_35,
  1, 116, :_reduce_none,
  1, 117, :_reduce_none,
  2, 117, :_reduce_none,
  1, 118, :_reduce_none,
  1, 118, :_reduce_none,
  4, 94, :_reduce_41,
  1, 119, :_reduce_42,
  2, 119, :_reduce_43,
  3, 119, :_reduce_44,
  2, 96, :_reduce_45,
  1, 120, :_reduce_none,
  1, 120, :_reduce_none,
  4, 95, :_reduce_48,
  1, 121, :_reduce_49,
  1, 121, :_reduce_50,
  1, 122, :_reduce_51,
  1, 122, :_reduce_52,
  1, 123, :_reduce_53,
  1, 124, :_reduce_54,
  1, 125, :_reduce_none,
  1, 125, :_reduce_none,
  2, 97, :_reduce_57,
  2, 100, :_reduce_58,
  2, 126, :_reduce_59,
  1, 127, :_reduce_60,
  3, 127, :_reduce_61,
  1, 128, :_reduce_none,
  1, 128, :_reduce_none,
  3, 129, :_reduce_64,
  3, 130, :_reduce_65,
  3, 130, :_reduce_66,
  3, 130, :_reduce_67,
  3, 131, :_reduce_68,
  1, 132, :_reduce_none,
  1, 132, :_reduce_none,
  3, 133, :_reduce_71,
  3, 133, :_reduce_72,
  3, 133, :_reduce_73,
  4, 133, :_reduce_74,
  3, 133, :_reduce_75,
  2, 133, :_reduce_76,
  2, 133, :_reduce_77,
  3, 133, :_reduce_78,
  3, 133, :_reduce_79,
  3, 133, :_reduce_80,
  3, 133, :_reduce_81,
  2, 134, :_reduce_82,
  2, 134, :_reduce_83,
  2, 134, :_reduce_84,
  2, 135, :_reduce_85,
  2, 135, :_reduce_86,
  1, 136, :_reduce_87,
  0, 137, :_reduce_88,
  1, 137, :_reduce_none,
  1, 138, :_reduce_90,
  1, 139, :_reduce_91,
  0, 140, :_reduce_92,
  1, 140, :_reduce_none,
  1, 141, :_reduce_94,
  1, 142, :_reduce_95,
  1, 143, :_reduce_96,
  2, 143, :_reduce_97,
  0, 144, :_reduce_98,
  1, 144, :_reduce_none,
  3, 98, :_reduce_100,
  4, 145, :_reduce_101,
  4, 145, :_reduce_102,
  3, 145, :_reduce_103,
  4, 146, :_reduce_104,
  0, 148, :_reduce_105,
  1, 148, :_reduce_none,
  1, 148, :_reduce_none,
  4, 99, :_reduce_108,
  3, 99, :_reduce_109,
  3, 99, :_reduce_110,
  5, 99, :_reduce_111,
  1, 149, :_reduce_none,
  2, 149, :_reduce_113,
  1, 149, :_reduce_none,
  1, 153, :_reduce_none,
  2, 153, :_reduce_116,
  1, 153, :_reduce_none,
  2, 153, :_reduce_118,
  1, 153, :_reduce_none,
  1, 154, :_reduce_none,
  2, 154, :_reduce_121,
  1, 154, :_reduce_none,
  0, 150, :_reduce_123,
  1, 150, :_reduce_none,
  3, 150, :_reduce_125,
  3, 150, :_reduce_126,
  1, 150, :_reduce_none,
  1, 150, :_reduce_none,
  1, 147, :_reduce_none,
  1, 147, :_reduce_none,
  1, 147, :_reduce_none,
  1, 147, :_reduce_none,
  1, 147, :_reduce_none,
  1, 147, :_reduce_none,
  2, 151, :_reduce_135,
  3, 101, :_reduce_136,
  4, 104, :_reduce_137,
  1, 152, :_reduce_138,
  3, 152, :_reduce_139,
  1, 156, :_reduce_none,
  1, 156, :_reduce_none,
  0, 157, :_reduce_none,
  1, 157, :_reduce_none,
  1, 155, :_reduce_144,
  3, 155, :_reduce_145,
  2, 158, :_reduce_146,
  2, 158, :_reduce_147,
  1, 158, :_reduce_148,
  0, 160, :_reduce_149,
  1, 160, :_reduce_none,
  1, 159, :_reduce_151,
  3, 159, :_reduce_152,
  1, 161, :_reduce_153,
  4, 105, :_reduce_154,
  1, 162, :_reduce_155,
  3, 162, :_reduce_156,
  2, 163, :_reduce_157,
  3, 163, :_reduce_158,
  3, 163, :_reduce_159,
  2, 163, :_reduce_160,
  3, 163, :_reduce_161,
  3, 163, :_reduce_162,
  4, 106, :_reduce_163,
  1, 164, :_reduce_164,
  3, 164, :_reduce_165,
  3, 165, :_reduce_166,
  4, 165, :_reduce_167,
  3, 165, :_reduce_168,
  4, 165, :_reduce_169,
  3, 111, :_reduce_170,
  0, 166, :_reduce_none,
  3, 166, :_reduce_172,
  3, 110, :_reduce_173,
  1, 167, :_reduce_174,
  3, 167, :_reduce_175,
  1, 168, :_reduce_176,
  2, 168, :_reduce_177,
  3, 109, :_reduce_178,
  1, 169, :_reduce_179,
  3, 169, :_reduce_180,
  1, 170, :_reduce_181,
  2, 170, :_reduce_182,
  3, 112, :_reduce_183,
  3, 113, :_reduce_184,
  3, 114, :_reduce_185,
  3, 115, :_reduce_186,
  1, 171, :_reduce_187,
  2, 171, :_reduce_188,
  2, 171, :_reduce_189,
  3, 171, :_reduce_190,
  1, 173, :_reduce_none,
  1, 173, :_reduce_none,
  1, 172, :_reduce_193,
  3, 172, :_reduce_194,
  0, 175, :_reduce_none,
  1, 175, :_reduce_none,
  1, 174, :_reduce_197,
  2, 174, :_reduce_198,
  3, 108, :_reduce_199,
  1, 177, :_reduce_none,
  0, 178, :_reduce_201,
  1, 178, :_reduce_none,
  1, 179, :_reduce_none,
  1, 179, :_reduce_none,
  1, 176, :_reduce_205,
  3, 176, :_reduce_206,
  1, 180, :_reduce_207,
  3, 180, :_reduce_208,
  2, 181, :_reduce_209,
  3, 181, :_reduce_210,
  1, 181, :_reduce_211,
  2, 181, :_reduce_212,
  4, 107, :_reduce_213,
  0, 182, :_reduce_214,
  1, 182, :_reduce_215,
  1, 184, :_reduce_216,
  1, 184, :_reduce_217,
  1, 184, :_reduce_218,
  0, 185, :_reduce_219,
  1, 185, :_reduce_none,
  1, 183, :_reduce_221,
  3, 183, :_reduce_222,
  4, 186, :_reduce_223,
  0, 187, :_reduce_224,
  1, 187, :_reduce_225,
  2, 190, :_reduce_226,
  3, 190, :_reduce_227,
  3, 190, :_reduce_228,
  3, 190, :_reduce_229,
  0, 189, :_reduce_230,
  1, 189, :_reduce_none,
  3, 192, :_reduce_232,
  1, 193, :_reduce_233,
  2, 193, :_reduce_234,
  0, 188, :_reduce_235,
  1, 188, :_reduce_236,
  1, 191, :_reduce_237,
  2, 191, :_reduce_238,
  2, 191, :_reduce_239,
  1, 191, :_reduce_240,
  1, 191, :_reduce_241,
  1, 194, :_reduce_242,
  1, 195, :_reduce_243,
  1, 196, :_reduce_244 ]

racc_reduce_n = 245

racc_shift_n = 348

racc_token_table = {
  false => 0,
  :error => 1,
  :BLANK => 2,
  :H1 => 3,
  :H2 => 4,
  :H3 => 5,
  :NOTA_BENE => 6,
  :NOTE => 7,
  :END => 8,
  "|" => 9,
  ":" => 10,
  :GROUP_DEF => 11,
  :TEAM => 12,
  "," => 13,
  :ROUND_OUTLINE => 14,
  :ROUND_DEF => 15,
  :DATE => 16,
  :DURATION => 17,
  :YEAR => 18,
  :DATETIME => 19,
  :TIME => 20,
  :DATE_LEGS => 21,
  "@" => 22,
  :GEO => 23,
  "-" => 24,
  :VS => 25,
  :INLINE_NP => 26,
  :INLINE_CANC => 27,
  :INLINE_WO => 28,
  :INLINE_PPD => 29,
  :SCORE_FULL => 30,
  :SCORE_FULLER => 31,
  :SCORE => 32,
  :SCORE_AWD => 33,
  :SCORE_ABD => 34,
  :SCORE_FULLER_MORE => 35,
  :INLINE_AWD => 36,
  :INLINE_ABD => 37,
  :INLINE_VOID => 38,
  :INLINE_SUSP => 39,
  :TEAM_HOME => 40,
  :TEAM_AWAY => 41,
  :TEAM_NEUTRAL => 42,
  :ORD => 43,
  :STATUS => 44,
  :INLINE_ROUND_SHORT => 45,
  :INLINE_ROUND_BIG => 46,
  :INLINE_ATTENDANCE => 47,
  :INLINE_ATTENDANCE_SEP => 48,
  :INLINE_GOALS => 49,
  :GOALS_END => 50,
  :INLINE_BYE => 51,
  :SCORE_LEGS => 52,
  :GOALS => 53,
  ";" => 54,
  :GOAL_SEP_ALT => 55,
  :PLAYER => 56,
  :GOAL_COUNT => 57,
  :GOAL_MINUTE_SEP => 58,
  :GOAL_MINUTE => 59,
  :GOALS_ALT => 60,
  :GOAL_TYPE => 61,
  :GOALS_COMPAT => 62,
  :MINUTE => 63,
  :PROP_ATTENDANCE => 64,
  :PROP_NUM => 65,
  :PROP_END => 66,
  :ATTENDANCE => 67,
  :PROP_REFEREE => 68,
  :PROP_NAME => 69,
  :ENCLOSED_NAME => 70,
  :PROP_COACH => 71,
  :PROP_YELLOWCARDS => 72,
  :PROP_REDCARDS => 73,
  :PROP_YELLOWREDCARDS => 74,
  :PROP_SENTOFF => 75,
  :CARDS_NONE_RIGHT => 76,
  :CARDS_NONE_LEFT => 77,
  :CARDS_SEP_ALT => 78,
  :PROP_PENALTIES => 79,
  :PENALTIES_SEP_ALT => 80,
  :PROP => 81,
  :FORMATION => 82,
  :INLINE_CAPTAIN => 83,
  "(" => 84,
  ")" => 85,
  :INLINE_YELLOW => 86,
  :INLINE_YELLOW_RED => 87,
  :INLINE_RED => 88 }

racc_nt_base = 89

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]
Ractor.make_shareable(Racc_arg) if defined?(Ractor)

Racc_token_to_s_table = [
  "$end",
  "error",
  "BLANK",
  "H1",
  "H2",
  "H3",
  "NOTA_BENE",
  "NOTE",
  "END",
  "\"|\"",
  "\":\"",
  "GROUP_DEF",
  "TEAM",
  "\",\"",
  "ROUND_OUTLINE",
  "ROUND_DEF",
  "DATE",
  "DURATION",
  "YEAR",
  "DATETIME",
  "TIME",
  "DATE_LEGS",
  "\"@\"",
  "GEO",
  "\"-\"",
  "VS",
  "INLINE_NP",
  "INLINE_CANC",
  "INLINE_WO",
  "INLINE_PPD",
  "SCORE_FULL",
  "SCORE_FULLER",
  "SCORE",
  "SCORE_AWD",
  "SCORE_ABD",
  "SCORE_FULLER_MORE",
  "INLINE_AWD",
  "INLINE_ABD",
  "INLINE_VOID",
  "INLINE_SUSP",
  "TEAM_HOME",
  "TEAM_AWAY",
  "TEAM_NEUTRAL",
  "ORD",
  "STATUS",
  "INLINE_ROUND_SHORT",
  "INLINE_ROUND_BIG",
  "INLINE_ATTENDANCE",
  "INLINE_ATTENDANCE_SEP",
  "INLINE_GOALS",
  "GOALS_END",
  "INLINE_BYE",
  "SCORE_LEGS",
  "GOALS",
  "\";\"",
  "GOAL_SEP_ALT",
  "PLAYER",
  "GOAL_COUNT",
  "GOAL_MINUTE_SEP",
  "GOAL_MINUTE",
  "GOALS_ALT",
  "GOAL_TYPE",
  "GOALS_COMPAT",
  "MINUTE",
  "PROP_ATTENDANCE",
  "PROP_NUM",
  "PROP_END",
  "ATTENDANCE",
  "PROP_REFEREE",
  "PROP_NAME",
  "ENCLOSED_NAME",
  "PROP_COACH",
  "PROP_YELLOWCARDS",
  "PROP_REDCARDS",
  "PROP_YELLOWREDCARDS",
  "PROP_SENTOFF",
  "CARDS_NONE_RIGHT",
  "CARDS_NONE_LEFT",
  "CARDS_SEP_ALT",
  "PROP_PENALTIES",
  "PENALTIES_SEP_ALT",
  "PROP",
  "FORMATION",
  "INLINE_CAPTAIN",
  "\"(\"",
  "\")\"",
  "INLINE_YELLOW",
  "INLINE_YELLOW_RED",
  "INLINE_RED",
  "$start",
  "document",
  "elements",
  "element",
  "heading",
  "group_def",
  "round_def",
  "round_outline",
  "date_header",
  "match_line_with_header",
  "match_line",
  "date_header_legs",
  "match_line_legs",
  "note_line",
  "nota_bene",
  "goal_lines",
  "goal_lines_alt",
  "goal_lines_compat",
  "lineup_lines",
  "penalties_lines",
  "coach_line",
  "referee_line",
  "attendance_line",
  "yellowcard_line",
  "redcard_line",
  "yellowredcard_line",
  "sentoff_line",
  "opt_blank_lines",
  "blank_lines",
  "group_def_sep",
  "team_values",
  "round_def_sep",
  "round_date_opts",
  "date",
  "datetime",
  "time",
  "date_datetime",
  "geo",
  "geo_names",
  "match_sep",
  "match_fixture",
  "match_fixture_not_played",
  "match_fixture_postponed",
  "SCORE_FULL_OR_FULLER",
  "match_result",
  "match_fixture_base",
  "match_result_base",
  "ord",
  "opt_ord",
  "status",
  "note",
  "opt_inline_note",
  "inline_round_short",
  "inline_round_big",
  "inline_attendance",
  "opt_inline_attendance",
  "match_header",
  "match_line_header",
  "match",
  "more_match_header_opts",
  "pre_match_opts",
  "more_match_opts",
  "match_bye",
  "goal_lines_body",
  "pre_match1",
  "pre_match2",
  "goals",
  "goals_sep",
  "opt_goal_sep",
  "goal",
  "goal_minutes",
  "opt_goal_minute_sep",
  "goal_minute",
  "goals_alt",
  "goal_alt",
  "goals_compat",
  "goal_compat",
  "attendance_opt",
  "referees",
  "referee",
  "coaches",
  "coach",
  "card_body",
  "cards",
  "cards_sep",
  "player_w_minute",
  "opt_card_sep",
  "penalties_body",
  "penalty_sep",
  "opt_penalty_sep",
  "penalties_team_sep",
  "penalties",
  "penalty",
  "opt_formation",
  "lineup",
  "lineup_sep",
  "opt_lineup_sep",
  "lineup_name",
  "opt_captain",
  "opt_inline_cards",
  "opt_lineup_sub",
  "lineup_sub_props",
  "inline_cards",
  "lineup_sub",
  "lineup_sub_contents",
  "inline_yellow",
  "inline_yellow_red",
  "inline_red" ]
Ractor.make_shareable(Racc_token_to_s_table) if defined?(Ractor)

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'parser.y', 9)
  def _reduce_1(val, _values, result)
     result = []
    result
  end
.,.,

# reduce 2 omitted

# reduce 3 omitted

# reduce 4 omitted

# reduce 5 omitted

# reduce 6 omitted

# reduce 7 omitted

# reduce 8 omitted

# reduce 9 omitted

# reduce 10 omitted

# reduce 11 omitted

# reduce 12 omitted

# reduce 13 omitted

# reduce 14 omitted

# reduce 15 omitted

# reduce 16 omitted

# reduce 17 omitted

# reduce 18 omitted

# reduce 19 omitted

# reduce 20 omitted

# reduce 21 omitted

# reduce 22 omitted

# reduce 23 omitted

# reduce 24 omitted

# reduce 25 omitted

# reduce 26 omitted

# reduce 27 omitted

module_eval(<<'.,.,', 'parser.y', 55)
  def _reduce_28(val, _values, result)
                   ## _trace( "REDUCE BLANK" )
               @tree << BlankLine.new

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 61)
  def _reduce_29(val, _values, result)
     puts "!! skipping invalid content (trying to recover from parse error):"
                pp val[0]
                ##  note - do NOT report recover errors for now
                ##  @errors << "parser error (recover) - skipping #{val[0].pretty_inspect}"

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 72)
  def _reduce_30(val, _values, result)
      @tree << Heading1.new( text: val[0].as_str)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 73)
  def _reduce_31(val, _values, result)
      @tree << Heading2.new( text: val[0].as_str)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 74)
  def _reduce_32(val, _values, result)
      @tree << Heading3.new( text: val[0].as_str)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 79)
  def _reduce_33(val, _values, result)
     @tree << NotaBene.new( text: val[0].as_str)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 86)
  def _reduce_34(val, _values, result)
     @tree << NoteLine.new( text: val[0].as_str)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 93)
  def _reduce_35(val, _values, result)

    result
  end
.,.,

# reduce 36 omitted

# reduce 37 omitted

# reduce 38 omitted

# reduce 39 omitted

# reduce 40 omitted

module_eval(<<'.,.,', 'parser.y', 109)
  def _reduce_41(val, _values, result)
                          @tree << GroupDef.new( name:  val[0].as_str,
                                             teams: val[2] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 114)
  def _reduce_42(val, _values, result)
     result = [val[0].as_str]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 115)
  def _reduce_43(val, _values, result)
     result.push( val[1].as_str )
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 116)
  def _reduce_44(val, _values, result)
     result.push( val[2].as_str )
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 132)
  def _reduce_45(val, _values, result)
                                      @tree << RoundOutline.new( **val[0].as_hash )

    result
  end
.,.,

# reduce 46 omitted

# reduce 47 omitted

module_eval(<<'.,.,', 'parser.y', 147)
  def _reduce_48(val, _values, result)
                          kwargs = { name: val[0].as_str }.merge( val[2] )
                      @tree << RoundDef.new( **kwargs )

                      ## auto-add RoundOutline here - why? why not?
                      ##    or handle "implicit" round_outline
                      ##     in tree walker?
                      @tree << RoundOutline.new( outline: val[0].as_str, level: 1 )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 160)
  def _reduce_49(val, _values, result)
     result = { date: val[0].as_hash }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 161)
  def _reduce_50(val, _values, result)
     result = { duration: val[0].as_hash }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 171)
  def _reduce_51(val, _values, result)
     result = { date: val[0].as_hash }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 172)
  def _reduce_52(val, _values, result)
     result = { year: val[0].as_int }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 177)
  def _reduce_53(val, _values, result)
     result = val[0].as_hash
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 180)
  def _reduce_54(val, _values, result)
     result = val[0].as_hash
    result
  end
.,.,

# reduce 55 omitted

# reduce 56 omitted

module_eval(<<'.,.,', 'parser.y', 211)
  def _reduce_57(val, _values, result)
                         @tree <<  DateHeader.new( **val[0] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 218)
  def _reduce_58(val, _values, result)
                         @tree <<  DateHeaderLegs.new( **val[0].as_hash )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 229)
  def _reduce_59(val, _values, result)
     result = { geo: val[1] }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 232)
  def _reduce_60(val, _values, result)
      result = [val[0].as_str]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 233)
  def _reduce_61(val, _values, result)
      result.push( val[2].as_str )
    result
  end
.,.,

# reduce 62 omitted

# reduce 63 omitted

module_eval(<<'.,.,', 'parser.y', 259)
  def _reduce_64(val, _values, result)
                                   _trace( "RECUDE match_fixture" )
                               result = { team1: val[0].as_str,
                                          team2: val[2].as_str }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 271)
  def _reduce_65(val, _values, result)
                                   ## note - auto-add (match) status canceled - why? why not?
                               ##   A n/p B   short (inline) form of =>
                               ##   A v B [canceled]

                               result = { team1: val[0].as_str,
                                          team2: val[2].as_str,
                                          status_inline: 'canceled' }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 281)
  def _reduce_66(val, _values, result)
                                   result = { team1: val[0].as_str,
                                          team2: val[2].as_str,
                                          status_inline: 'canceled' }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 289)
  def _reduce_67(val, _values, result)
                                   result = { team1: val[0].as_str,
                                          team2: val[2].as_str,
                                          status_inline: 'walkover' }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 297)
  def _reduce_68(val, _values, result)
                                   result = { team1: val[0].as_str,
                                          team2: val[2].as_str,
                                          status_inline: 'postponed' }

    result
  end
.,.,

# reduce 69 omitted

# reduce 70 omitted

module_eval(<<'.,.,', 'parser.y', 315)
  def _reduce_71(val, _values, result)
                               _trace( "REDUCE => match_result : TEAM SCORE TEAM" )

                          ## note - use/keep generic score (as array!! NOT hash!!!)
                          ##      - as array e.g. [1,1] !!
                           result = { team1: val[0].as_str, team2: val[2].as_str,
                                      score: val[1].as_ary
                                    }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 325)
  def _reduce_72(val, _values, result)
                               result = { team1: val[0].as_str, team2: val[2].as_str,
                                      score: val[1].as_ary,
                                      status_inline: 'awarded'
                                    }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 332)
  def _reduce_73(val, _values, result)
                               result = { team1: val[0].as_str, team2: val[2].as_str,
                                      score: val[1].as_ary,
                                      status_inline: 'abandoned'
                                    }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 339)
  def _reduce_74(val, _values, result)
                                _trace( "REDUCE => match_result : TEAM SCORE TEAM SCORE_FULLER_MORE" )
                            score =  if val[3].as_hash[:score] &&
                                        val[3].as_hash[:score]=='et'   ## check aet flag present?
                                         val[3].as_hash.delete( :score )  ## note - remove/delete  flag
                                           { et: val[1].as_ary }
                                     elsif val[3].as_hash[:score] &&
                                           val[3].as_hash[:score]=='ht' ## check ht flag present?
                                         val[3].as_hash.delete( :score ) ## note - remove/delete flag
                                           { ht: val[1].as_ary }
                                     elsif val[3].as_hash[:score] &&
                                           val[3].as_hash[:score]=='ft'  ## check ft flag present?
                                         val[3].as_hash.delete( :score )  ## note - remove/delete flag
                                           { ft: val[1].as_ary }
                                     else   ## assume full-time (ft)
                                            { ft: val[1].as_ary }
                                     end

                           result = {  team1: val[0].as_str,
                                      team2: val[2].as_str,
                                      score: score.merge( val[3].as_hash )
                                    }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 363)
  def _reduce_75(val, _values, result)
                               result = { team1: val[0].as_str,
                                      team2: val[2].as_str,
                                      score: val[1].as_hash
                                    }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 377)
  def _reduce_76(val, _values, result)
                              _trace( "REDUCE  => match_result : match_fixture SCORE" )
                          ## note - use/keep generic score (as array!! NOT hash!!!)
                          ##      - as array e.g. [1,1] !!
                          result = { score: val[1].as_ary }.merge( val[0] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 384)
  def _reduce_77(val, _values, result)
                              _trace( "REDUCE  => match_result : match_fixture SCORE_FULL_OR_FULLER" )
                          result = { score: val[1].as_hash }.merge( val[0] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 396)
  def _reduce_78(val, _values, result)
                               result = { team1: val[0].as_str, team2: val[2].as_str,
                                      status_inline: 'awarded'
                                    }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 402)
  def _reduce_79(val, _values, result)
                               result = { team1: val[0].as_str, team2: val[2].as_str,
                                      status_inline: 'abandoned'
                                    }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 408)
  def _reduce_80(val, _values, result)
                               result = { team1: val[0].as_str, team2: val[2].as_str,
                                      status_inline: 'annulled'
                                    }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 414)
  def _reduce_81(val, _values, result)
                               result = { team1: val[0].as_str, team2: val[2].as_str,
                                      status_inline: 'suspended'
                                    }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 428)
  def _reduce_82(val, _values, result)
     result = { team1: '_', team2: val[1].as_str }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 429)
  def _reduce_83(val, _values, result)
     result = { team1: val[1].as_str, team2: '_' }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 430)
  def _reduce_84(val, _values, result)
     result = { team1: '_', team2: val[1].as_str,
                                                       neutral: true }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 437)
  def _reduce_85(val, _values, result)
                              _trace( "REDUCE  => match_result_base : match_fixture_base SCORE" )
                          ## note - use/keep generic score (as array!! NOT hash!!!)
                          ##      - as array e.g. [1,1] !!
                          result = { score: val[1].as_ary }.merge( val[0] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 444)
  def _reduce_86(val, _values, result)
                              _trace( "REDUCE  => match_result_base : match_fixture_base SCORE_FULL_OR_FULLER" )
                          result = { score: val[1].as_hash }.merge( val[0] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 454)
  def _reduce_87(val, _values, result)
      result = { num: val[0].as_int }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 457)
  def _reduce_88(val, _values, result)
      result = {}
    result
  end
.,.,

# reduce 89 omitted

module_eval(<<'.,.,', 'parser.y', 466)
  def _reduce_90(val, _values, result)
      result = val[0].as_hash
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 468)
  def _reduce_91(val, _values, result)
     result = { note: val[0].as_str }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 471)
  def _reduce_92(val, _values, result)
      result = {}
    result
  end
.,.,

# reduce 93 omitted

module_eval(<<'.,.,', 'parser.y', 475)
  def _reduce_94(val, _values, result)
     result = { round_inline_short: val[0].as_str }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 476)
  def _reduce_95(val, _values, result)
     result = { round_inline_big: val[0].as_str }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 489)
  def _reduce_96(val, _values, result)
                           result = { att: val[0].as_hash[:value] }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 493)
  def _reduce_97(val, _values, result)
                           result = { att: val[1].as_hash[:value] }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 497)
  def _reduce_98(val, _values, result)
      result = {}
    result
  end
.,.,

# reduce 99 omitted

module_eval(<<'.,.,', 'parser.y', 514)
  def _reduce_100(val, _values, result)
                         ## note - header flag (header: true)
                     ##    used downstream for scope / e.g. DateHeader merge/inheritance or such
                      kwargs = { header: true }.merge( val[0], val[2] )
                      @tree << MatchLine.new( **kwargs )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 529)
  def _reduce_101(val, _values, result)
                          result = {}.merge( val[0], val[1], val[2] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 535)
  def _reduce_102(val, _values, result)
                          result = {}.merge( val[0], val[1], val[2] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 541)
  def _reduce_103(val, _values, result)
                          result = {}.merge( val[0], val[1] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 551)
  def _reduce_104(val, _values, result)
                          result = {}.merge( val[0], val[1], val[2] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 559)
  def _reduce_105(val, _values, result)
      result = {}
    result
  end
.,.,

# reduce 106 omitted

# reduce 107 omitted

module_eval(<<'.,.,', 'parser.y', 572)
  def _reduce_108(val, _values, result)
                           kwargs = {}.merge( val[0], val[1], val[2] )
                       @tree << MatchLine.new( **kwargs )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 577)
  def _reduce_109(val, _values, result)
                           kwargs = {}.merge( val[0], val[1] )
                       @tree << MatchLine.new( **kwargs )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 584)
  def _reduce_110(val, _values, result)
                             kwargs = {}.merge( val[0], val[1] )
                         @tree << MatchLineBye.new( **kwargs )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 597)
  def _reduce_111(val, _values, result)
                          @tree << MatchLine.new( **val[0] )

                      @tree << GoalLine.new( goals: val[2] )

    result
  end
.,.,

# reduce 112 omitted

module_eval(<<'.,.,', 'parser.y', 618)
  def _reduce_113(val, _values, result)
     result = {}.merge( val[0], val[1])
    result
  end
.,.,

# reduce 114 omitted

# reduce 115 omitted

module_eval(<<'.,.,', 'parser.y', 623)
  def _reduce_116(val, _values, result)
     result = {}.merge( val[0], val[1])
    result
  end
.,.,

# reduce 117 omitted

module_eval(<<'.,.,', 'parser.y', 625)
  def _reduce_118(val, _values, result)
     result = {}.merge( val[0], val[1])
    result
  end
.,.,

# reduce 119 omitted

# reduce 120 omitted

module_eval(<<'.,.,', 'parser.y', 630)
  def _reduce_121(val, _values, result)
     result = {}.merge( val[0], val[1])
    result
  end
.,.,

# reduce 122 omitted

module_eval(<<'.,.,', 'parser.y', 641)
  def _reduce_123(val, _values, result)
     result = {}
    result
  end
.,.,

# reduce 124 omitted

module_eval(<<'.,.,', 'parser.y', 645)
  def _reduce_125(val, _values, result)
                         result = {}.merge( val[0], val[1], val[2] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 649)
  def _reduce_126(val, _values, result)
                       result = {}.merge( val[0], val[1], val[2] )

    result
  end
.,.,

# reduce 127 omitted

# reduce 128 omitted

# reduce 129 omitted

# reduce 130 omitted

# reduce 131 omitted

# reduce 132 omitted

# reduce 133 omitted

# reduce 134 omitted

module_eval(<<'.,.,', 'parser.y', 678)
  def _reduce_135(val, _values, result)
                          result = { team: val[0].as_str }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 695)
  def _reduce_136(val, _values, result)
                          kwargs = { score: val[1].as_hash }.merge( val[0] )
                      @tree << MatchLineLegs.new( **kwargs )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 736)
  def _reduce_137(val, _values, result)
                             @tree << GoalLine.new( goals: val[1] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 747)
  def _reduce_138(val, _values, result)
      result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 748)
  def _reduce_139(val, _values, result)
      result = [val[0],val[2]]
    result
  end
.,.,

# reduce 140 omitted

# reduce 141 omitted

# reduce 142 omitted

# reduce 143 omitted

module_eval(<<'.,.,', 'parser.y', 759)
  def _reduce_144(val, _values, result)
     result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 760)
  def _reduce_145(val, _values, result)
     result.push( val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 771)
  def _reduce_146(val, _values, result)
                           result = Goal.new( player:  val[0].as_str,
                                          minutes: val[1] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 776)
  def _reduce_147(val, _values, result)
                            ### todo/check:
                        ##    auto convert/expand
                        ##    count to minutes - why? why not?
                        ##  todo/fix - pass in empty minutes ary [] - why? why not?
                        result = Goal.new( player: val[0].as_str,
                                           count:  val[1].as_hash )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 785)
  def _reduce_148(val, _values, result)
                            result = Goal.new( player: val[0].as_str,
                                           minutes: [] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 792)
  def _reduce_149(val, _values, result)

    result
  end
.,.,

# reduce 150 omitted

module_eval(<<'.,.,', 'parser.y', 795)
  def _reduce_151(val, _values, result)
      result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 796)
  def _reduce_152(val, _values, result)
      result.push( val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 800)
  def _reduce_153(val, _values, result)
                                 result = GoalMinute.new( **val[0].as_hash )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 821)
  def _reduce_154(val, _values, result)
                                 @tree << GoalLineAlt.new( goals: val[1] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 829)
  def _reduce_155(val, _values, result)
     result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 831)
  def _reduce_156(val, _values, result)
     result.push( val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 839)
  def _reduce_157(val, _values, result)
                               result = GoalAlt.new( score:   val[0].as_ary,
                                                 player:  val[1].as_str )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 844)
  def _reduce_158(val, _values, result)
                               goal_minute = GoalMinute.new( **val[2].as_hash )

                           result = GoalAlt.new( score:     val[0].as_ary,
                                                 player:    val[1].as_str,
                                                 minute:    goal_minute.to_minute,
                                                 goal_type: goal_minute.to_goal_type )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 853)
  def _reduce_159(val, _values, result)
                               result = GoalAlt.new( score:     val[0].as_ary,
                                                 player:    val[1].as_str,
                                                 goal_type: GoalType.new( **val[2].as_hash ))

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 863)
  def _reduce_160(val, _values, result)
                               result = GoalAlt.new( player:  val[0].as_str,
                                                 score:   val[1].as_ary )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 868)
  def _reduce_161(val, _values, result)
                               goal_minute = GoalMinute.new( **val[1].as_hash )

                           result = GoalAlt.new( player:    val[0].as_str,
                                                 minute:    goal_minute.to_minute,
                                                 goal_type: goal_minute.to_goal_type,
                                                 score:     val[2].as_ary )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 877)
  def _reduce_162(val, _values, result)
                               result = GoalAlt.new( player:    val[0].as_str,
                                                 goal_type: GoalType.new( **val[1].as_hash ),
                                                 score:     val[2].as_ary )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 891)
  def _reduce_163(val, _values, result)
                                 @tree << GoalLineCompat.new( goals: val[1] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 895)
  def _reduce_164(val, _values, result)
     result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 897)
  def _reduce_165(val, _values, result)
     result.push( val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 905)
  def _reduce_166(val, _values, result)
                               result = GoalCompat.new( minute:  Minute.new(**val[0].as_hash),
                                                    player:  val[1].as_str,
                                                    score:  val[2].as_ary )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 911)
  def _reduce_167(val, _values, result)
                               result = GoalCompat.new( minute: Minute.new(**val[0].as_hash),
                                                    player: val[1].as_str,
                                                    goal_type: GoalType.new( **val[2].as_hash ),
                                                    score:  val[3].as_ary )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 918)
  def _reduce_168(val, _values, result)
                               result = GoalCompat.new( minute:  Minute.new(**val[0].as_hash),
                                                    score:  val[1].as_ary,
                                                    player:  val[2].as_str )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 924)
  def _reduce_169(val, _values, result)
                               result = GoalCompat.new( minute: Minute.new(**val[0].as_hash),
                                                    score:  val[1].as_ary,
                                                    player: val[2].as_str,
                                                    goal_type: GoalType.new( **val[3].as_hash ))

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 961)
  def _reduce_170(val, _values, result)
                                     @tree << AttendanceLine.new( att: val[1].as_int )

    result
  end
.,.,

# reduce 171 omitted

module_eval(<<'.,.,', 'parser.y', 970)
  def _reduce_172(val, _values, result)
                                     @tree << AttendanceLine.new( att: val[2].as_int )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 979)
  def _reduce_173(val, _values, result)
                                   @tree << RefereeLine.new( referees: val[1] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 982)
  def _reduce_174(val, _values, result)
      result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 983)
  def _reduce_175(val, _values, result)
      result.push( val[2] )
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 986)
  def _reduce_176(val, _values, result)
      result = Referee.new( name: val[0].as_str )
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 988)
  def _reduce_177(val, _values, result)
      result = Referee.new( name: val[0].as_str, country: val[1].as_str )
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 997)
  def _reduce_178(val, _values, result)
                                   @tree << CoachLine.new( coaches: val[1] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1000)
  def _reduce_179(val, _values, result)
      result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1001)
  def _reduce_180(val, _values, result)
      result.push( val[2] )
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1004)
  def _reduce_181(val, _values, result)
      result = Coach.new( name: val[0].as_str )
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1006)
  def _reduce_182(val, _values, result)
      result = Coach.new( name: val[0].as_str, country: val[1].as_str )
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1013)
  def _reduce_183(val, _values, result)
                                   @tree << CardsLine.new( type: 'Y', bookings: val[1] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1017)
  def _reduce_184(val, _values, result)
                                   @tree << CardsLine.new( type: 'R', bookings: val[1] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1021)
  def _reduce_185(val, _values, result)
                                   @tree << CardsLine.new( type: 'Y/R', bookings: val[1] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1027)
  def _reduce_186(val, _values, result)
                                   @tree << CardsLine.new( type: 'SENTOFF', bookings: val[1] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1036)
  def _reduce_187(val, _values, result)
     result =  val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1037)
  def _reduce_188(val, _values, result)
     result = [val[0], []]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1038)
  def _reduce_189(val, _values, result)
     result = [[],     val[1]]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1039)
  def _reduce_190(val, _values, result)
     result = [val[0], val[2]]
    result
  end
.,.,

# reduce 191 omitted

# reduce 192 omitted

module_eval(<<'.,.,', 'parser.y', 1051)
  def _reduce_193(val, _values, result)
      result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1054)
  def _reduce_194(val, _values, result)
                                result.push( val[2] )

    result
  end
.,.,

# reduce 195 omitted

# reduce 196 omitted

module_eval(<<'.,.,', 'parser.y', 1062)
  def _reduce_197(val, _values, result)
     result = Booking.new( name: val[0].as_str )
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1064)
  def _reduce_198(val, _values, result)
     result = Booking.new( name:   val[0].as_str,
                                                      minute: Minute.new(**val[1].as_hash) )
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1071)
  def _reduce_199(val, _values, result)
                                   @tree << PenaltiesLine.new( penalties: val[1] )

    result
  end
.,.,

# reduce 200 omitted

module_eval(<<'.,.,', 'parser.y', 1078)
  def _reduce_201(val, _values, result)

    result
  end
.,.,

# reduce 202 omitted

# reduce 203 omitted

# reduce 204 omitted

module_eval(<<'.,.,', 'parser.y', 1092)
  def _reduce_205(val, _values, result)
     result =  val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1093)
  def _reduce_206(val, _values, result)
     result = [val[0], val[2]]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1097)
  def _reduce_207(val, _values, result)
      result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1098)
  def _reduce_208(val, _values, result)
      result.push( val[2] )
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1103)
  def _reduce_209(val, _values, result)
                                     result = Penalty.new( score: val[0].as_ary,
                                                       name:  val[1].as_str )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1108)
  def _reduce_210(val, _values, result)
                                     result = Penalty.new( score: val[0].as_ary,
                                                       name:  val[1].as_str,
                                                       note:  val[2].as_str )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1114)
  def _reduce_211(val, _values, result)
                                     result = Penalty.new( name: val[0].as_str )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1118)
  def _reduce_212(val, _values, result)
                                     result = Penalty.new( name: val[0].as_str,
                                                       note: val[1].as_str )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1130)
  def _reduce_213(val, _values, result)
                              kwargs = { team:    val[0].as_str,
                                     lineup:  val[2]  }.merge( val[1] )
                          @tree << LineupLine.new( **kwargs )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1136)
  def _reduce_214(val, _values, result)
     result = {}
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1137)
  def _reduce_215(val, _values, result)
     result = { formation: val[0].as_str }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1147)
  def _reduce_216(val, _values, result)
     result = ','
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1148)
  def _reduce_217(val, _values, result)
     result = ';'
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1149)
  def _reduce_218(val, _values, result)
     result = '-'
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1151)
  def _reduce_219(val, _values, result)
     result = ''
    result
  end
.,.,

# reduce 220 omitted

module_eval(<<'.,.,', 'parser.y', 1157)
  def _reduce_221(val, _values, result)
                           ## note - value must be DOUBLE [[]] nested in array
                       ##    allows formations (e.g. 4-3-3 or such)
                       ##   via dash (-) separator, see below!
                       result = [[val[0]]]

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1164)
  def _reduce_222(val, _values, result)
                           ## note - if lineup_sep is dash (-) or
                       ##                         semicolor (;) start a new sub array!!
                       if val[1] == '-' || val[1] == ';'
                          result << [val[2]]
                       else
                          result[-1] << val[2]
                       end

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1176)
  def _reduce_223(val, _values, result)
                                  kwargs = { name: val[0].as_str }.merge( val[1], val[2], val[3] )
                              result = Lineup.new( **kwargs )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1183)
  def _reduce_224(val, _values, result)
     result = {}
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1184)
  def _reduce_225(val, _values, result)
     result = { captain: true }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1207)
  def _reduce_226(val, _values, result)
                                 _trace( "REDUCE => lineup_sub_props : PROP_NAME  opt_cards" )
                             result = { name: val[0].as_str }.merge( val[1] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1214)
  def _reduce_227(val, _values, result)
                                 _trace( "REDUCE => lineup_sub_props : PROP_NAME  MINUTE  opt_cards" )
                              result = { name:   val[0].as_str,
                                         minute: Minute.new( **val[1].as_hash )
                                       }.merge( val[2])

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1224)
  def _reduce_228(val, _values, result)
                                 _trace( "REDUCE => lineup_sub_props : PROP_NAME  cards  MINUTE" )
                              result = { name:   val[0].as_str,
                                         minute: Minute.new( **val[2].as_hash ),
                                         cards:  val[1]
                                       }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1235)
  def _reduce_229(val, _values, result)
                                 _trace( "REDUCE => lineup_sub_props : MINUTE  PROP_NAME  opt_cards" )

                               result = { name:   val[1].as_str,
                                          minute: Minute.new( **val[0].as_hash )
                                        }.merge( val[2])

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1247)
  def _reduce_230(val, _values, result)
      result = {}
    result
  end
.,.,

# reduce 231 omitted

module_eval(<<'.,.,', 'parser.y', 1255)
  def _reduce_232(val, _values, result)
      result = val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1259)
  def _reduce_233(val, _values, result)
                                       _trace( "REDUCE => lineup_sub_contents : line_sub_props" )
                                   kwargs  = {}.merge( val[0] )
                                   minute  = kwargs.delete( :minute )
                                   sub = Sub.new(  sub:     Lineup.new( **kwargs ),
                                                   minute:  minute )
                                   result = { sub: sub }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1268)
  def _reduce_234(val, _values, result)
                                        _trace( "REDUCE => lineup_sub_contents : line_sub_props lineup_sub" )
                                   kwargs  = {}.merge( val[0] ).merge( val[1] )
                                   minute  = kwargs.delete( :minute )
                                   sub = Sub.new(  sub:     Lineup.new( **kwargs ),
                                                   minute:  minute )
                                   result = { sub: sub }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1278)
  def _reduce_235(val, _values, result)
     result = {}
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1279)
  def _reduce_236(val, _values, result)
     result = { cards: val[0] }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1289)
  def _reduce_237(val, _values, result)
      result =  [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1290)
  def _reduce_238(val, _values, result)
      result =  [val[0],val[1]]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1291)
  def _reduce_239(val, _values, result)
      result =  [val[0],val[1]]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1292)
  def _reduce_240(val, _values, result)
      result =  [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1293)
  def _reduce_241(val, _values, result)
      result =  [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1299)
  def _reduce_242(val, _values, result)
                    minute = val[0].as_hash.empty? ? nil : Minute.new( **val[0].as_hash )
                result = Card.new( name: 'Y',  minute: minute )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1305)
  def _reduce_243(val, _values, result)
                    minute = val[0].as_hash.empty? ? nil : Minute.new( **val[0].as_hash )
                result = Card.new( name: 'Y/R',  minute: minute )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1311)
  def _reduce_244(val, _values, result)
                    minute = val[0].as_hash.empty? ? nil : Minute.new( **val[0].as_hash )
                result = Card.new( name: 'R',  minute: minute )

    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

  end   # class Parser
end   # module Fbtxt
