#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.8.1
# from Racc grammar file "parser.y".
#

require 'racc/parser.rb'
module Fbtxt
  class Parser < Racc::Parser
##### State transition tables begin ###

racc_action_table = [
    27,    26,    28,    29,    30,    31,    32,   243,   216,   243,
    33,    44,   243,    34,    35,    36,   250,    37,    38,    39,
    42,    43,   216,   216,   152,   165,   126,   234,   165,   165,
   165,    78,   219,   163,   221,    80,   163,   163,   163,    46,
    47,    48,    50,   281,    51,   282,   257,    84,   153,   214,
   215,  -141,    67,   240,    46,    47,    48,   256,   216,    68,
   222,    69,  -189,    70,  -189,  -141,    71,  -189,   235,   249,
    72,    73,    74,    75,   238,   -97,   241,    76,    77,    27,
    26,    28,    29,    30,    31,    32,   171,   255,   131,    33,
    44,   131,    34,    35,    36,   228,    37,    38,    39,    42,
    43,  -207,   131,    43,   126,   171,    43,   287,   225,   108,
   109,   116,   261,   132,   121,   122,   262,   263,    46,    47,
    48,    50,   172,    51,   231,   130,    88,   132,   130,   152,
   132,    67,    46,    47,    48,   226,   288,   227,    68,   130,
    69,   172,    70,    81,    82,    71,    86,    85,   230,    72,
    73,    74,    75,   153,   180,   181,    76,    77,    36,    43,
    37,    38,    39,    43,    43,    92,    93,    95,    96,    97,
    98,   102,    43,    99,   100,   101,   331,   103,   104,   105,
   106,    89,    51,    91,   121,   122,    51,    51,   108,   109,
   110,   327,   107,   121,   122,    51,   326,   306,   307,   308,
   108,   109,   110,    92,    93,    95,    96,    97,    98,   102,
   112,    99,   100,   101,   113,   103,   104,   105,   106,   306,
   307,   308,   306,   307,   308,   306,   307,   308,   121,   122,
   277,  -148,   307,   308,   114,   115,   119,   131,   140,    43,
   149,   156,   157,   160,   175,   176,   178,   182,   183,   184,
   185,   186,   187,   188,   189,   190,   191,   192,   193,   194,
   195,   196,   197,    50,   201,   205,   207,    43,   210,   149,
   212,   224,   232,   236,   237,   165,   245,   246,   247,   248,
   252,   253,   260,   264,   265,   266,   268,   269,   270,   131,
   273,   274,   149,   149,   279,   283,   284,   285,   156,   289,
   290,   160,   292,   165,   165,   296,   297,   298,   299,   175,
   309,   313,   221,   315,   316,   317,   318,   319,   322,   325,
   333,   334,   322,   337 ]

racc_action_check = [
     0,     0,     0,     0,     0,     0,     0,   244,   147,   293,
     0,     0,   162,     0,     0,     0,   169,     0,     0,     0,
     0,     0,   275,   150,    68,    72,    54,   158,    73,    74,
    75,     1,   149,    72,   149,    32,    73,    74,    75,     0,
     0,     0,     0,   224,     0,   224,   173,    34,    68,   147,
   147,   147,     0,   162,    54,    54,    54,   173,   154,     0,
   150,     0,   244,     0,   293,   275,     0,   162,   158,   169,
     0,     0,     0,     0,   162,   123,   162,     0,     0,     2,
     2,     2,     2,     2,     2,     2,    76,   173,    55,     2,
     2,   128,     2,     2,     2,   154,     2,     2,     2,     2,
     2,   173,   267,    55,   200,   251,   128,   230,   153,    49,
    49,    49,   177,   123,   123,   123,   177,   177,     2,     2,
     2,     2,    76,     2,   156,    55,    40,    55,   128,   223,
   128,     2,   200,   200,   200,   153,   230,   153,     2,   267,
     2,   251,     2,    33,    33,     2,    35,    35,   156,     2,
     2,     2,     2,   223,    87,    87,     2,     2,    58,    53,
    58,    58,    58,    60,    58,    44,    44,    44,    44,    44,
    44,    44,   143,    44,    44,    44,   326,    44,    44,    44,
    44,    42,    53,    43,    53,    53,    60,    58,    45,    45,
    45,   322,    44,   135,   135,   143,   322,   326,   326,   326,
   127,   127,   127,   126,   126,   126,   126,   126,   126,   126,
    45,   126,   126,   126,    46,   126,   126,   126,   126,   259,
   259,   259,   331,   331,   331,   333,   333,   333,   208,   208,
   218,   218,   303,   303,    47,    48,    52,    56,    57,    62,
    67,    69,    70,    71,    77,    78,    83,    90,    94,    95,
    96,    97,    98,    99,   100,   101,   102,   103,   104,   105,
   106,   112,   118,   120,   122,   124,   133,   134,   139,   140,
   146,   152,   157,   160,   161,   163,   165,   166,   167,   168,
   171,   172,   175,   179,   182,   188,   203,   204,   206,   209,
   211,   212,   213,   217,   222,   226,   227,   228,   229,   231,
   233,   234,   235,   239,   242,   252,   254,   255,   256,   258,
   263,   273,   278,   288,   289,   292,   298,   299,   301,   310,
   327,   328,   329,   332 ]

racc_action_pointer = [
    -1,    31,    78,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    27,   134,    39,   137,   nil,   nil,   nil,   nil,
   118,   nil,   173,   160,   141,   158,   202,   222,   223,    79,
   nil,   nil,   234,   137,    14,    81,   230,   189,   142,   nil,
   141,   nil,   217,   nil,   nil,   nil,   nil,   184,    -8,   178,
   177,   175,   -43,   -40,   -39,   -38,    54,   176,   245,   nil,
   nil,   nil,   nil,   234,   nil,   nil,   nil,   138,   nil,   nil,
   234,   nil,   nil,   nil,   236,   237,   238,   239,   240,   241,
   242,   243,   244,   245,   246,   247,   248,   nil,   nil,   nil,
   nil,   nil,   253,   nil,   nil,   nil,   nil,   nil,   260,   nil,
   220,   nil,   217,    67,   257,   nil,   179,   170,    84,   nil,
   nil,   nil,   nil,   258,   245,   146,   nil,   nil,   nil,   260,
   213,   nil,   nil,   150,   nil,   nil,   220,    -5,   nil,   -25,
    10,   nil,   215,    76,    45,   nil,    92,   206,    14,   nil,
   204,   208,    -1,   207,   nil,   213,   211,   212,   213,     3,
   nil,   212,   212,    33,   nil,   201,   nil,   104,   nil,   275,
   nil,   nil,   261,   nil,   nil,   nil,   nil,   nil,   250,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
    92,   nil,   nil,   278,   279,   nil,   280,   nil,   181,   282,
   nil,   240,   283,   236,   nil,   nil,   nil,   237,   172,   nil,
   nil,   nil,   286,    97,   -16,   nil,   263,   264,   289,   235,
    75,   243,   nil,   234,   233,   232,   nil,   nil,   nil,   235,
   nil,   nil,   236,   nil,    -6,   nil,   nil,   nil,   nil,   nil,
   nil,    73,   236,   nil,   240,   227,   228,   nil,   241,   135,
   nil,   nil,   nil,   298,   nil,   nil,   nil,    95,   nil,   nil,
   nil,   nil,   nil,   303,   nil,     9,   nil,   nil,   253,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   281,   253,
   nil,   nil,   250,    -4,   nil,   nil,   nil,   nil,   248,   249,
   nil,   236,   nil,   147,   nil,   nil,   nil,   nil,   nil,   nil,
   311,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   128,   nil,   nil,   nil,   113,   252,   238,   240,
   nil,   138,   260,   141,   nil,   nil,   nil,   nil,   nil ]

racc_action_default = [
    -1,  -234,    -2,    -3,    -5,    -6,    -7,    -8,    -9,   -10,
   -11,   -12,   -13,   -14,   -15,   -16,   -17,   -18,   -19,   -20,
   -21,   -22,   -23,   -24,   -25,   -26,   -27,   -28,   -29,   -30,
   -31,   -32,  -234,  -234,  -234,  -234,   -50,   -51,   -52,   -53,
   -54,   -55,  -234,  -234,  -234,  -129,  -234,  -234,  -234,  -132,
   -86,   -93,   -34,  -114,  -234,  -122,   -91,  -128,  -111,  -113,
  -116,  -118,  -119,  -121,  -130,  -131,  -133,  -234,  -234,  -234,
  -234,  -234,  -234,  -234,  -234,  -234,  -234,  -234,  -234,    -4,
   -33,   -38,   -39,  -234,   -44,   -45,   -46,  -234,   -56,   -57,
   -58,   -59,   -61,   -62,  -234,  -234,  -234,  -234,  -234,  -234,
  -234,  -234,  -234,  -234,  -234,  -234,  -234,  -134,   -68,   -69,
   -75,   -76,  -234,   -81,   -82,   -83,   -84,   -85,   -35,   -36,
   -87,   -95,  -234,  -121,  -234,  -115,  -234,  -129,  -122,  -128,
   -89,   -90,   -94,  -234,  -123,   -97,  -126,  -127,   -92,  -234,
  -234,   -54,  -112,  -114,  -117,  -120,  -234,  -137,  -143,  -147,
  -141,  -154,  -234,  -234,  -141,  -163,  -234,  -234,  -175,  -171,
  -173,  -234,  -181,  -234,  -187,  -191,  -234,  -234,  -234,  -234,
  -195,  -234,  -199,  -202,  -210,  -213,   339,  -234,   -41,  -234,
   -48,   -49,  -234,   -63,   -64,   -65,   -66,   -67,   -70,   -71,
   -72,   -74,   -77,   -78,   -79,   -80,  -135,   -37,   -88,   -99,
  -234,   -96,   -98,  -234,  -234,  -102,  -234,  -108,   -97,   -91,
  -109,  -234,  -234,  -234,  -139,  -140,  -142,  -234,  -145,  -146,
  -150,  -152,  -234,  -234,  -156,  -159,  -234,  -234,  -234,  -234,
  -234,  -234,  -169,  -234,  -234,  -234,  -174,  -177,  -182,  -234,
  -185,  -186,  -234,  -190,  -183,  -192,  -178,  -179,  -180,  -193,
  -194,  -234,  -197,  -200,  -234,  -234,  -209,  -208,  -234,  -224,
  -214,   -40,   -42,  -234,   -47,   -60,   -73,  -104,  -100,  -101,
  -107,  -124,  -125,  -234,  -136,  -138,  -144,  -149,  -234,  -153,
  -155,  -157,  -158,  -160,  -161,  -162,  -164,  -165,  -234,  -167,
  -170,  -172,  -234,  -184,  -188,  -196,  -198,  -201,  -234,  -234,
  -211,  -219,  -225,  -226,  -229,  -230,  -231,  -232,  -233,   -43,
  -234,  -105,  -106,  -110,  -151,  -166,  -168,  -176,  -203,  -204,
  -212,  -220,  -234,  -227,  -228,  -103,  -224,  -234,  -234,  -222,
  -215,  -224,  -225,  -224,  -221,  -223,  -216,  -217,  -218 ]

racc_goto_table = [
   138,   174,   170,   159,   155,   151,   139,   220,   127,   129,
   128,   125,   203,   123,   244,   135,   321,   301,   144,   133,
   146,   223,   145,     1,   209,   229,   161,   166,   167,   168,
     3,     2,    79,   120,   118,    83,   177,    87,   179,   141,
   143,    90,   117,   198,   335,   200,   311,   204,   124,   199,
   310,   142,   275,   213,   276,   218,   278,   150,   154,   158,
   233,   239,   294,   169,   251,   173,   254,   258,   259,   320,
   329,   332,   328,   323,   324,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   330,   nil,   nil,   nil,   135,   336,
   293,   338,   206,   211,   208,   nil,   nil,   271,   nil,   nil,
   nil,   125,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   314,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   138,   127,   129,   267,   nil,   nil,   272,
   280,   nil,   nil,   nil,   286,   nil,   291,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   295,   nil,   nil,
   nil,   nil,   300,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   312 ]

racc_goto_check = [
    49,    91,    86,    78,    75,    73,    50,    71,    39,    43,
    57,    64,    54,    36,    80,    36,    97,    93,    64,    60,
    62,    67,    36,     1,    54,    67,    79,    79,    79,    79,
     3,     2,     3,    26,    27,    28,    29,    30,    31,    32,
    35,    37,    42,    46,    97,    47,    48,    52,    53,    56,
    58,    63,    65,    66,    68,    69,    70,    72,    74,    76,
    77,    81,    82,    84,    85,    87,    88,    90,    92,    94,
    95,    96,    98,   100,   101,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,    93,   nil,   nil,   nil,    36,    93,
    80,    93,    60,    62,    36,   nil,   nil,    54,   nil,   nil,
   nil,    64,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,    71,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,    49,    39,    43,    57,   nil,   nil,    50,
    73,   nil,   nil,   nil,    75,   nil,    78,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    86,   nil,   nil,
   nil,   nil,    91,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,    49 ]

racc_goto_pointer = [
   nil,    23,    31,    30,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   -19,   -18,     2,   -47,
     2,   -49,   -19,   nil,   nil,   -18,   -40,    -2,   nil,   -46,
   nil,   nil,    -7,   -45,   nil,   nil,   -77,   -75,  -221,   -56,
   -50,   nil,   -76,    -5,  -111,   nil,   -71,   -44,  -217,   nil,
   -36,   nil,   -47,    -7,   -42,  -161,   -94,  -129,  -163,   -94,
  -162,  -142,   -11,   -63,   -11,   -65,   -12,   -98,   -68,   -46,
  -149,  -101,  -180,   nil,   -13,  -105,   -74,   -12,  -107,   nil,
  -106,   -76,  -107,  -242,  -232,  -252,  -255,  -285,  -250,   nil,
  -230,  -229 ]

racc_goto_default = [
   nil,   nil,   nil,   nil,     4,     5,     6,     7,     8,     9,
    10,    11,    12,    13,    14,    15,    16,    17,    18,    19,
    20,    21,    22,    23,    24,    25,   nil,   nil,   nil,   nil,
   nil,   nil,    40,    41,    60,    53,    63,   nil,    94,    45,
    64,    65,   111,    57,    49,    66,    58,   nil,   134,   136,
   nil,    62,   137,   202,   nil,    52,   nil,    55,   nil,    54,
   nil,    56,   nil,    59,    61,   147,   nil,   217,   148,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   162,   nil,   164,   242,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   302,   nil,   nil,   303,
   305,   304 ]

racc_reduce_table = [
  0, 0, :racc_error,
  0, 88, :_reduce_1,
  1, 88, :_reduce_none,
  1, 89, :_reduce_none,
  2, 89, :_reduce_none,
  1, 90, :_reduce_none,
  1, 90, :_reduce_none,
  1, 90, :_reduce_none,
  1, 90, :_reduce_none,
  1, 90, :_reduce_none,
  1, 90, :_reduce_none,
  1, 90, :_reduce_none,
  1, 90, :_reduce_none,
  1, 90, :_reduce_none,
  1, 90, :_reduce_none,
  1, 90, :_reduce_none,
  1, 90, :_reduce_none,
  1, 90, :_reduce_none,
  1, 90, :_reduce_none,
  1, 90, :_reduce_none,
  1, 90, :_reduce_none,
  1, 90, :_reduce_none,
  1, 90, :_reduce_none,
  1, 90, :_reduce_none,
  1, 90, :_reduce_none,
  1, 90, :_reduce_none,
  1, 90, :_reduce_none,
  1, 90, :_reduce_27,
  1, 90, :_reduce_28,
  1, 91, :_reduce_29,
  1, 91, :_reduce_30,
  1, 91, :_reduce_31,
  1, 101, :_reduce_32,
  2, 100, :_reduce_33,
  0, 113, :_reduce_34,
  1, 113, :_reduce_none,
  1, 114, :_reduce_none,
  2, 114, :_reduce_none,
  1, 115, :_reduce_none,
  1, 115, :_reduce_none,
  4, 92, :_reduce_40,
  1, 116, :_reduce_41,
  2, 116, :_reduce_42,
  3, 116, :_reduce_43,
  2, 94, :_reduce_44,
  1, 117, :_reduce_none,
  1, 117, :_reduce_none,
  4, 93, :_reduce_47,
  1, 118, :_reduce_48,
  1, 118, :_reduce_49,
  1, 119, :_reduce_50,
  1, 119, :_reduce_51,
  1, 120, :_reduce_52,
  1, 121, :_reduce_53,
  1, 122, :_reduce_none,
  1, 122, :_reduce_none,
  2, 95, :_reduce_56,
  2, 98, :_reduce_57,
  2, 123, :_reduce_58,
  1, 124, :_reduce_59,
  3, 124, :_reduce_60,
  1, 125, :_reduce_none,
  1, 125, :_reduce_none,
  3, 126, :_reduce_63,
  3, 127, :_reduce_64,
  3, 127, :_reduce_65,
  3, 127, :_reduce_66,
  3, 128, :_reduce_67,
  1, 129, :_reduce_none,
  1, 129, :_reduce_none,
  3, 130, :_reduce_70,
  3, 130, :_reduce_71,
  3, 130, :_reduce_72,
  4, 130, :_reduce_73,
  3, 130, :_reduce_74,
  2, 130, :_reduce_75,
  2, 130, :_reduce_76,
  3, 130, :_reduce_77,
  3, 130, :_reduce_78,
  3, 130, :_reduce_79,
  3, 130, :_reduce_80,
  2, 131, :_reduce_81,
  2, 131, :_reduce_82,
  2, 131, :_reduce_83,
  2, 132, :_reduce_84,
  2, 132, :_reduce_85,
  1, 133, :_reduce_86,
  0, 134, :_reduce_87,
  1, 134, :_reduce_none,
  1, 135, :_reduce_89,
  1, 136, :_reduce_90,
  0, 137, :_reduce_91,
  1, 137, :_reduce_none,
  1, 138, :_reduce_93,
  1, 139, :_reduce_94,
  1, 140, :_reduce_95,
  2, 140, :_reduce_96,
  0, 141, :_reduce_97,
  1, 141, :_reduce_none,
  3, 96, :_reduce_99,
  4, 142, :_reduce_100,
  4, 142, :_reduce_101,
  3, 142, :_reduce_102,
  4, 143, :_reduce_103,
  0, 145, :_reduce_104,
  1, 145, :_reduce_none,
  1, 145, :_reduce_none,
  4, 97, :_reduce_107,
  3, 97, :_reduce_108,
  3, 97, :_reduce_109,
  5, 97, :_reduce_110,
  1, 146, :_reduce_none,
  2, 146, :_reduce_112,
  1, 146, :_reduce_none,
  1, 150, :_reduce_none,
  2, 150, :_reduce_115,
  1, 150, :_reduce_none,
  2, 150, :_reduce_117,
  1, 150, :_reduce_none,
  1, 151, :_reduce_none,
  2, 151, :_reduce_120,
  1, 151, :_reduce_none,
  0, 147, :_reduce_122,
  1, 147, :_reduce_none,
  3, 147, :_reduce_124,
  3, 147, :_reduce_125,
  1, 147, :_reduce_none,
  1, 147, :_reduce_none,
  1, 144, :_reduce_none,
  1, 144, :_reduce_none,
  1, 144, :_reduce_none,
  1, 144, :_reduce_none,
  1, 144, :_reduce_none,
  1, 144, :_reduce_none,
  2, 148, :_reduce_134,
  3, 99, :_reduce_135,
  4, 102, :_reduce_136,
  1, 149, :_reduce_137,
  3, 149, :_reduce_138,
  1, 153, :_reduce_none,
  1, 153, :_reduce_none,
  0, 154, :_reduce_none,
  1, 154, :_reduce_none,
  1, 152, :_reduce_143,
  3, 152, :_reduce_144,
  2, 155, :_reduce_145,
  2, 155, :_reduce_146,
  1, 155, :_reduce_147,
  0, 157, :_reduce_148,
  1, 157, :_reduce_none,
  1, 156, :_reduce_150,
  3, 156, :_reduce_151,
  1, 158, :_reduce_152,
  4, 103, :_reduce_153,
  1, 159, :_reduce_154,
  3, 159, :_reduce_155,
  2, 160, :_reduce_156,
  3, 160, :_reduce_157,
  3, 160, :_reduce_158,
  2, 160, :_reduce_159,
  3, 160, :_reduce_160,
  3, 160, :_reduce_161,
  4, 104, :_reduce_162,
  1, 161, :_reduce_163,
  3, 161, :_reduce_164,
  3, 162, :_reduce_165,
  4, 162, :_reduce_166,
  3, 162, :_reduce_167,
  4, 162, :_reduce_168,
  3, 108, :_reduce_169,
  4, 107, :_reduce_170,
  1, 163, :_reduce_171,
  3, 163, :_reduce_172,
  1, 165, :_reduce_173,
  2, 165, :_reduce_174,
  0, 164, :_reduce_none,
  3, 164, :_reduce_176,
  3, 109, :_reduce_177,
  3, 110, :_reduce_178,
  3, 111, :_reduce_179,
  3, 112, :_reduce_180,
  1, 166, :_reduce_181,
  2, 166, :_reduce_182,
  2, 166, :_reduce_183,
  3, 166, :_reduce_184,
  1, 168, :_reduce_none,
  1, 168, :_reduce_none,
  1, 167, :_reduce_187,
  3, 167, :_reduce_188,
  0, 170, :_reduce_none,
  1, 170, :_reduce_none,
  1, 169, :_reduce_191,
  2, 169, :_reduce_192,
  3, 106, :_reduce_193,
  1, 172, :_reduce_none,
  1, 171, :_reduce_195,
  3, 171, :_reduce_196,
  2, 173, :_reduce_197,
  3, 173, :_reduce_198,
  1, 173, :_reduce_199,
  2, 173, :_reduce_200,
  4, 105, :_reduce_201,
  0, 175, :_reduce_202,
  3, 175, :_reduce_203,
  3, 175, :_reduce_204,
  1, 176, :_reduce_205,
  1, 176, :_reduce_206,
  0, 177, :_reduce_207,
  1, 177, :_reduce_208,
  1, 177, :_reduce_209,
  1, 174, :_reduce_210,
  3, 174, :_reduce_211,
  4, 178, :_reduce_212,
  0, 179, :_reduce_213,
  1, 179, :_reduce_214,
  2, 182, :_reduce_215,
  3, 182, :_reduce_216,
  3, 182, :_reduce_217,
  3, 182, :_reduce_218,
  0, 181, :_reduce_219,
  1, 181, :_reduce_none,
  3, 184, :_reduce_221,
  1, 185, :_reduce_222,
  2, 185, :_reduce_223,
  0, 180, :_reduce_224,
  1, 180, :_reduce_225,
  1, 183, :_reduce_226,
  2, 183, :_reduce_227,
  2, 183, :_reduce_228,
  1, 183, :_reduce_229,
  1, 183, :_reduce_230,
  1, 186, :_reduce_231,
  1, 187, :_reduce_232,
  1, 188, :_reduce_233 ]

racc_reduce_n = 234

racc_shift_n = 339

racc_token_table = {
  false => 0,
  :error => 1,
  :BLANK => 2,
  :H1 => 3,
  :H2 => 4,
  :H3 => 5,
  :NOTA_BENE => 6,
  :NOTE => 7,
  :END => 8,
  "|" => 9,
  ":" => 10,
  :GROUP_DEF => 11,
  :TEAM => 12,
  "," => 13,
  :ROUND_OUTLINE => 14,
  :ROUND_DEF => 15,
  :DATE => 16,
  :DURATION => 17,
  :YEAR => 18,
  :DATETIME => 19,
  :TIME => 20,
  :DATE_LEGS => 21,
  "@" => 22,
  :GEO => 23,
  "-" => 24,
  :VS => 25,
  :INLINE_NP => 26,
  :INLINE_CANC => 27,
  :INLINE_WO => 28,
  :INLINE_PPD => 29,
  :SCORE_FULL => 30,
  :SCORE_FULLER => 31,
  :SCORE => 32,
  :SCORE_AWD => 33,
  :SCORE_ABD => 34,
  :SCORE_FULLER_MORE => 35,
  :INLINE_AWD => 36,
  :INLINE_ABD => 37,
  :INLINE_VOID => 38,
  :INLINE_SUSP => 39,
  :TEAM_HOME => 40,
  :TEAM_AWAY => 41,
  :TEAM_NEUTRAL => 42,
  :ORD => 43,
  :STATUS => 44,
  :INLINE_ROUND_SHORT => 45,
  :INLINE_ROUND_BIG => 46,
  :INLINE_ATTENDANCE => 47,
  :INLINE_ATTENDANCE_SEP => 48,
  :INLINE_GOALS => 49,
  :GOALS_END => 50,
  :INLINE_BYE => 51,
  :SCORE_LEGS => 52,
  :GOALS => 53,
  ";" => 54,
  :GOAL_SEP_ALT => 55,
  :PLAYER => 56,
  :GOAL_COUNT => 57,
  :GOAL_MINUTE_SEP => 58,
  :GOAL_MINUTE => 59,
  :GOALS_ALT => 60,
  :GOAL_TYPE => 61,
  :GOALS_COMPAT => 62,
  :MINUTE => 63,
  :PROP_ATTENDANCE => 64,
  :PROP_NUM => 65,
  :PROP_END => 66,
  :PROP_REFEREE => 67,
  :PROP_NAME => 68,
  :ENCLOSED_NAME => 69,
  :ATTENDANCE => 70,
  :PROP_YELLOWCARDS => 71,
  :PROP_REDCARDS => 72,
  :PROP_YELLOWREDCARDS => 73,
  :PROP_SENTOFF => 74,
  :CARDS_NONE_RIGHT => 75,
  :CARDS_NONE_LEFT => 76,
  :CARDS_SEP_ALT => 77,
  :PROP_PENALTIES => 78,
  :PROP => 79,
  :COACH => 80,
  :INLINE_CAPTAIN => 81,
  "(" => 82,
  ")" => 83,
  :INLINE_YELLOW => 84,
  :INLINE_YELLOW_RED => 85,
  :INLINE_RED => 86 }

racc_nt_base = 87

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]
Ractor.make_shareable(Racc_arg) if defined?(Ractor)

Racc_token_to_s_table = [
  "$end",
  "error",
  "BLANK",
  "H1",
  "H2",
  "H3",
  "NOTA_BENE",
  "NOTE",
  "END",
  "\"|\"",
  "\":\"",
  "GROUP_DEF",
  "TEAM",
  "\",\"",
  "ROUND_OUTLINE",
  "ROUND_DEF",
  "DATE",
  "DURATION",
  "YEAR",
  "DATETIME",
  "TIME",
  "DATE_LEGS",
  "\"@\"",
  "GEO",
  "\"-\"",
  "VS",
  "INLINE_NP",
  "INLINE_CANC",
  "INLINE_WO",
  "INLINE_PPD",
  "SCORE_FULL",
  "SCORE_FULLER",
  "SCORE",
  "SCORE_AWD",
  "SCORE_ABD",
  "SCORE_FULLER_MORE",
  "INLINE_AWD",
  "INLINE_ABD",
  "INLINE_VOID",
  "INLINE_SUSP",
  "TEAM_HOME",
  "TEAM_AWAY",
  "TEAM_NEUTRAL",
  "ORD",
  "STATUS",
  "INLINE_ROUND_SHORT",
  "INLINE_ROUND_BIG",
  "INLINE_ATTENDANCE",
  "INLINE_ATTENDANCE_SEP",
  "INLINE_GOALS",
  "GOALS_END",
  "INLINE_BYE",
  "SCORE_LEGS",
  "GOALS",
  "\";\"",
  "GOAL_SEP_ALT",
  "PLAYER",
  "GOAL_COUNT",
  "GOAL_MINUTE_SEP",
  "GOAL_MINUTE",
  "GOALS_ALT",
  "GOAL_TYPE",
  "GOALS_COMPAT",
  "MINUTE",
  "PROP_ATTENDANCE",
  "PROP_NUM",
  "PROP_END",
  "PROP_REFEREE",
  "PROP_NAME",
  "ENCLOSED_NAME",
  "ATTENDANCE",
  "PROP_YELLOWCARDS",
  "PROP_REDCARDS",
  "PROP_YELLOWREDCARDS",
  "PROP_SENTOFF",
  "CARDS_NONE_RIGHT",
  "CARDS_NONE_LEFT",
  "CARDS_SEP_ALT",
  "PROP_PENALTIES",
  "PROP",
  "COACH",
  "INLINE_CAPTAIN",
  "\"(\"",
  "\")\"",
  "INLINE_YELLOW",
  "INLINE_YELLOW_RED",
  "INLINE_RED",
  "$start",
  "document",
  "elements",
  "element",
  "heading",
  "group_def",
  "round_def",
  "round_outline",
  "date_header",
  "match_line_with_header",
  "match_line",
  "date_header_legs",
  "match_line_legs",
  "note_line",
  "nota_bene",
  "goal_lines",
  "goal_lines_alt",
  "goal_lines_compat",
  "lineup_lines",
  "penalties_lines",
  "referee_line",
  "attendance_line",
  "yellowcard_line",
  "redcard_line",
  "yellowredcard_line",
  "sentoff_line",
  "opt_blank_lines",
  "blank_lines",
  "group_def_sep",
  "team_values",
  "round_def_sep",
  "round_date_opts",
  "date",
  "datetime",
  "time",
  "date_datetime",
  "geo",
  "geo_names",
  "match_sep",
  "match_fixture",
  "match_fixture_not_played",
  "match_fixture_postponed",
  "SCORE_FULL_OR_FULLER",
  "match_result",
  "match_fixture_base",
  "match_result_base",
  "ord",
  "opt_ord",
  "status",
  "note",
  "opt_inline_note",
  "inline_round_short",
  "inline_round_big",
  "inline_attendance",
  "opt_inline_attendance",
  "match_header",
  "match_line_header",
  "match",
  "more_match_header_opts",
  "pre_match_opts",
  "more_match_opts",
  "match_bye",
  "goal_lines_body",
  "pre_match1",
  "pre_match2",
  "goals",
  "goals_sep",
  "opt_goal_sep",
  "goal",
  "goal_minutes",
  "opt_goal_minute_sep",
  "goal_minute",
  "goals_alt",
  "goal_alt",
  "goals_compat",
  "goal_compat",
  "referees",
  "attendance_opt",
  "referee",
  "card_body",
  "cards",
  "cards_sep",
  "player_w_minute",
  "opt_card_sep",
  "penalties_body",
  "penalty_sep",
  "penalty",
  "lineup",
  "opt_coach",
  "lineup_sep",
  "opt_lineup_sep",
  "lineup_name",
  "opt_captain",
  "opt_inline_cards",
  "opt_lineup_sub",
  "lineup_sub_props",
  "inline_cards",
  "lineup_sub",
  "lineup_sub_contents",
  "inline_yellow",
  "inline_yellow_red",
  "inline_red" ]
Ractor.make_shareable(Racc_token_to_s_table) if defined?(Ractor)

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'parser.y', 9)
  def _reduce_1(val, _values, result)
     result = []
    result
  end
.,.,

# reduce 2 omitted

# reduce 3 omitted

# reduce 4 omitted

# reduce 5 omitted

# reduce 6 omitted

# reduce 7 omitted

# reduce 8 omitted

# reduce 9 omitted

# reduce 10 omitted

# reduce 11 omitted

# reduce 12 omitted

# reduce 13 omitted

# reduce 14 omitted

# reduce 15 omitted

# reduce 16 omitted

# reduce 17 omitted

# reduce 18 omitted

# reduce 19 omitted

# reduce 20 omitted

# reduce 21 omitted

# reduce 22 omitted

# reduce 23 omitted

# reduce 24 omitted

# reduce 25 omitted

# reduce 26 omitted

module_eval(<<'.,.,', 'parser.y', 54)
  def _reduce_27(val, _values, result)
                   ## _trace( "REDUCE BLANK" )
               @tree << BlankLine.new

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 60)
  def _reduce_28(val, _values, result)
     puts "!! skipping invalid content (trying to recover from parse error):"
                pp val[0]
                ##  note - do NOT report recover errors for now
                ##  @errors << "parser error (recover) - skipping #{val[0].pretty_inspect}"

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 71)
  def _reduce_29(val, _values, result)
      @tree << Heading1.new( text: val[0].as_str)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 72)
  def _reduce_30(val, _values, result)
      @tree << Heading2.new( text: val[0].as_str)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 73)
  def _reduce_31(val, _values, result)
      @tree << Heading3.new( text: val[0].as_str)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 78)
  def _reduce_32(val, _values, result)
     @tree << NotaBene.new( text: val[0].as_str)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 85)
  def _reduce_33(val, _values, result)
     @tree << NoteLine.new( text: val[0].as_str)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 92)
  def _reduce_34(val, _values, result)
    
    result
  end
.,.,

# reduce 35 omitted

# reduce 36 omitted

# reduce 37 omitted

# reduce 38 omitted

# reduce 39 omitted

module_eval(<<'.,.,', 'parser.y', 108)
  def _reduce_40(val, _values, result)
                          @tree << GroupDef.new( name:  val[0].as_str,
                                             teams: val[2] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 113)
  def _reduce_41(val, _values, result)
     result = [val[0].as_str]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 114)
  def _reduce_42(val, _values, result)
     result.push( val[1].as_str )
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 115)
  def _reduce_43(val, _values, result)
     result.push( val[2].as_str )
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 131)
  def _reduce_44(val, _values, result)
                                      @tree << RoundOutline.new( **val[0].as_hash )

    result
  end
.,.,

# reduce 45 omitted

# reduce 46 omitted

module_eval(<<'.,.,', 'parser.y', 146)
  def _reduce_47(val, _values, result)
                          kwargs = { name: val[0].as_str }.merge( val[2] )
                      @tree << RoundDef.new( **kwargs )

                      ## auto-add RoundOutline here - why? why not?
                      ##    or handle "implicit" round_outline
                      ##     in tree walker?
                      @tree << RoundOutline.new( outline: val[0].as_str, level: 1 )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 159)
  def _reduce_48(val, _values, result)
     result = { date: val[0].as_hash }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 160)
  def _reduce_49(val, _values, result)
     result = { duration: val[0].as_hash }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 170)
  def _reduce_50(val, _values, result)
     result = { date: val[0].as_hash }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 171)
  def _reduce_51(val, _values, result)
     result = { year: val[0].as_int }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 176)
  def _reduce_52(val, _values, result)
     result = val[0].as_hash
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 179)
  def _reduce_53(val, _values, result)
     result = val[0].as_hash
    result
  end
.,.,

# reduce 54 omitted

# reduce 55 omitted

module_eval(<<'.,.,', 'parser.y', 210)
  def _reduce_56(val, _values, result)
                         @tree <<  DateHeader.new( **val[0] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 217)
  def _reduce_57(val, _values, result)
                         @tree <<  DateHeaderLegs.new( **val[0].as_hash )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 228)
  def _reduce_58(val, _values, result)
     result = { geo: val[1] }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 231)
  def _reduce_59(val, _values, result)
      result = [val[0].as_str]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 232)
  def _reduce_60(val, _values, result)
      result.push( val[2].as_str )
    result
  end
.,.,

# reduce 61 omitted

# reduce 62 omitted

module_eval(<<'.,.,', 'parser.y', 258)
  def _reduce_63(val, _values, result)
                                   _trace( "RECUDE match_fixture" )
                               result = { team1: val[0].as_str,
                                          team2: val[2].as_str }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 270)
  def _reduce_64(val, _values, result)
                                   ## note - auto-add (match) status canceled - why? why not?
                               ##   A n/p B   short (inline) form of =>
                               ##   A v B [canceled]

                               result = { team1: val[0].as_str,
                                          team2: val[2].as_str,
                                          status_inline: 'canceled' }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 280)
  def _reduce_65(val, _values, result)
                                   result = { team1: val[0].as_str,
                                          team2: val[2].as_str,
                                          status_inline: 'canceled' }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 288)
  def _reduce_66(val, _values, result)
                                   result = { team1: val[0].as_str,
                                          team2: val[2].as_str,
                                          status_inline: 'walkover' }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 296)
  def _reduce_67(val, _values, result)
                                   result = { team1: val[0].as_str,
                                          team2: val[2].as_str,
                                          status_inline: 'postponed' }

    result
  end
.,.,

# reduce 68 omitted

# reduce 69 omitted

module_eval(<<'.,.,', 'parser.y', 314)
  def _reduce_70(val, _values, result)
                               _trace( "REDUCE => match_result : TEAM SCORE TEAM" )

                          ## note - use/keep generic score (as array!! NOT hash!!!)
                          ##      - as array e.g. [1,1] !!
                           result = { team1: val[0].as_str, team2: val[2].as_str,
                                      score: val[1].as_ary
                                    }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 324)
  def _reduce_71(val, _values, result)
                               result = { team1: val[0].as_str, team2: val[2].as_str,
                                      score: val[1].as_ary,
                                      status_inline: 'awarded'
                                    }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 331)
  def _reduce_72(val, _values, result)
                               result = { team1: val[0].as_str, team2: val[2].as_str,
                                      score: val[1].as_ary,
                                      status_inline: 'abandoned'
                                    }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 338)
  def _reduce_73(val, _values, result)
                                _trace( "REDUCE => match_result : TEAM SCORE TEAM SCORE_FULLER_MORE" )
                            score =  if val[3].as_hash[:score] &&
                                        val[3].as_hash[:score]=='et'   ## check aet flag present?
                                         val[3].as_hash.delete( :score )  ## note - remove/delete  flag
                                           { et: val[1].as_ary }
                                     elsif val[3].as_hash[:score] &&
                                           val[3].as_hash[:score]=='ht' ## check ht flag present?
                                         val[3].as_hash.delete( :score ) ## note - remove/delete flag
                                           { ht: val[1].as_ary }
                                     elsif val[3].as_hash[:score] &&
                                           val[3].as_hash[:score]=='ft'  ## check ft flag present?
                                         val[3].as_hash.delete( :score )  ## note - remove/delete flag
                                           { ft: val[1].as_ary }
                                     else   ## assume full-time (ft)
                                            { ft: val[1].as_ary }
                                     end

                           result = {  team1: val[0].as_str,
                                      team2: val[2].as_str,
                                      score: score.merge( val[3].as_hash )
                                    }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 362)
  def _reduce_74(val, _values, result)
                               result = { team1: val[0].as_str,
                                      team2: val[2].as_str,
                                      score: val[1].as_hash
                                    }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 376)
  def _reduce_75(val, _values, result)
                              _trace( "REDUCE  => match_result : match_fixture SCORE" )
                          ## note - use/keep generic score (as array!! NOT hash!!!)
                          ##      - as array e.g. [1,1] !!
                          result = { score: val[1].as_ary }.merge( val[0] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 383)
  def _reduce_76(val, _values, result)
                              _trace( "REDUCE  => match_result : match_fixture SCORE_FULL_OR_FULLER" )
                          result = { score: val[1].as_hash }.merge( val[0] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 395)
  def _reduce_77(val, _values, result)
                               result = { team1: val[0].as_str, team2: val[2].as_str,
                                      status_inline: 'awarded'
                                    }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 401)
  def _reduce_78(val, _values, result)
                               result = { team1: val[0].as_str, team2: val[2].as_str,
                                      status_inline: 'abandoned'
                                    }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 407)
  def _reduce_79(val, _values, result)
                               result = { team1: val[0].as_str, team2: val[2].as_str,
                                      status_inline: 'annulled'
                                    }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 413)
  def _reduce_80(val, _values, result)
                               result = { team1: val[0].as_str, team2: val[2].as_str,
                                      status_inline: 'suspended'
                                    }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 427)
  def _reduce_81(val, _values, result)
     result = { team1: '_', team2: val[1].as_str }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 428)
  def _reduce_82(val, _values, result)
     result = { team1: val[1].as_str, team2: '_' }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 429)
  def _reduce_83(val, _values, result)
     result = { team1: '_', team2: val[1].as_str,
                                                       neutral: true }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 436)
  def _reduce_84(val, _values, result)
                              _trace( "REDUCE  => match_result_base : match_fixture_base SCORE" )
                          ## note - use/keep generic score (as array!! NOT hash!!!)
                          ##      - as array e.g. [1,1] !!
                          result = { score: val[1].as_ary }.merge( val[0] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 443)
  def _reduce_85(val, _values, result)
                              _trace( "REDUCE  => match_result_base : match_fixture_base SCORE_FULL_OR_FULLER" )
                          result = { score: val[1].as_hash }.merge( val[0] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 453)
  def _reduce_86(val, _values, result)
      result = { num: val[0].as_int }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 456)
  def _reduce_87(val, _values, result)
      result = {}
    result
  end
.,.,

# reduce 88 omitted

module_eval(<<'.,.,', 'parser.y', 465)
  def _reduce_89(val, _values, result)
      result = val[0].as_hash
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 467)
  def _reduce_90(val, _values, result)
     result = { note: val[0].as_str }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 470)
  def _reduce_91(val, _values, result)
      result = {}
    result
  end
.,.,

# reduce 92 omitted

module_eval(<<'.,.,', 'parser.y', 474)
  def _reduce_93(val, _values, result)
     result = { round_inline_short: val[0].as_str }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 475)
  def _reduce_94(val, _values, result)
     result = { round_inline_big: val[0].as_str }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 488)
  def _reduce_95(val, _values, result)
                           result = { att: val[0].as_hash[:value] }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 492)
  def _reduce_96(val, _values, result)
                           result = { att: val[1].as_hash[:value] }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 496)
  def _reduce_97(val, _values, result)
      result = {}
    result
  end
.,.,

# reduce 98 omitted

module_eval(<<'.,.,', 'parser.y', 513)
  def _reduce_99(val, _values, result)
                         ## note - header flag (header: true)
                     ##    used downstream for scope / e.g. DateHeader merge/inheritance or such
                      kwargs = { header: true }.merge( val[0], val[2] )
                      @tree << MatchLine.new( **kwargs )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 528)
  def _reduce_100(val, _values, result)
                          result = {}.merge( val[0], val[1], val[2] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 534)
  def _reduce_101(val, _values, result)
                          result = {}.merge( val[0], val[1], val[2] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 540)
  def _reduce_102(val, _values, result)
                          result = {}.merge( val[0], val[1] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 550)
  def _reduce_103(val, _values, result)
                          result = {}.merge( val[0], val[1], val[2] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 558)
  def _reduce_104(val, _values, result)
      result = {}
    result
  end
.,.,

# reduce 105 omitted

# reduce 106 omitted

module_eval(<<'.,.,', 'parser.y', 571)
  def _reduce_107(val, _values, result)
                           kwargs = {}.merge( val[0], val[1], val[2] )
                       @tree << MatchLine.new( **kwargs )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 576)
  def _reduce_108(val, _values, result)
                           kwargs = {}.merge( val[0], val[1] )
                       @tree << MatchLine.new( **kwargs )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 583)
  def _reduce_109(val, _values, result)
                             kwargs = {}.merge( val[0], val[1] )
                         @tree << MatchLineBye.new( **kwargs )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 596)
  def _reduce_110(val, _values, result)
                          @tree << MatchLine.new( **val[0] )

                      @tree << GoalLine.new( goals: val[2] )

    result
  end
.,.,

# reduce 111 omitted

module_eval(<<'.,.,', 'parser.y', 617)
  def _reduce_112(val, _values, result)
     result = {}.merge( val[0], val[1])
    result
  end
.,.,

# reduce 113 omitted

# reduce 114 omitted

module_eval(<<'.,.,', 'parser.y', 622)
  def _reduce_115(val, _values, result)
     result = {}.merge( val[0], val[1])
    result
  end
.,.,

# reduce 116 omitted

module_eval(<<'.,.,', 'parser.y', 624)
  def _reduce_117(val, _values, result)
     result = {}.merge( val[0], val[1])
    result
  end
.,.,

# reduce 118 omitted

# reduce 119 omitted

module_eval(<<'.,.,', 'parser.y', 629)
  def _reduce_120(val, _values, result)
     result = {}.merge( val[0], val[1])
    result
  end
.,.,

# reduce 121 omitted

module_eval(<<'.,.,', 'parser.y', 640)
  def _reduce_122(val, _values, result)
     result = {}
    result
  end
.,.,

# reduce 123 omitted

module_eval(<<'.,.,', 'parser.y', 644)
  def _reduce_124(val, _values, result)
                         result = {}.merge( val[0], val[1], val[2] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 648)
  def _reduce_125(val, _values, result)
                       result = {}.merge( val[0], val[1], val[2] )

    result
  end
.,.,

# reduce 126 omitted

# reduce 127 omitted

# reduce 128 omitted

# reduce 129 omitted

# reduce 130 omitted

# reduce 131 omitted

# reduce 132 omitted

# reduce 133 omitted

module_eval(<<'.,.,', 'parser.y', 677)
  def _reduce_134(val, _values, result)
                          result = { team: val[0].as_str }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 694)
  def _reduce_135(val, _values, result)
                          kwargs = { score: val[1].as_hash }.merge( val[0] )
                      @tree << MatchLineLegs.new( **kwargs )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 735)
  def _reduce_136(val, _values, result)
                             @tree << GoalLine.new( goals: val[1] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 746)
  def _reduce_137(val, _values, result)
      result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 747)
  def _reduce_138(val, _values, result)
      result = [val[0],val[2]]
    result
  end
.,.,

# reduce 139 omitted

# reduce 140 omitted

# reduce 141 omitted

# reduce 142 omitted

module_eval(<<'.,.,', 'parser.y', 758)
  def _reduce_143(val, _values, result)
     result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 759)
  def _reduce_144(val, _values, result)
     result.push( val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 770)
  def _reduce_145(val, _values, result)
                           result = Goal.new( player:  val[0].as_str,
                                          minutes: val[1] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 775)
  def _reduce_146(val, _values, result)
                            ### todo/check:
                        ##    auto convert/expand
                        ##    count to minutes - why? why not?
                        ##  todo/fix - pass in empty minutes ary [] - why? why not?
                        result = Goal.new( player: val[0].as_str,
                                           count:  val[1].as_hash )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 784)
  def _reduce_147(val, _values, result)
                            result = Goal.new( player: val[0].as_str,
                                           minutes: [] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 791)
  def _reduce_148(val, _values, result)
    
    result
  end
.,.,

# reduce 149 omitted

module_eval(<<'.,.,', 'parser.y', 794)
  def _reduce_150(val, _values, result)
      result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 795)
  def _reduce_151(val, _values, result)
      result.push( val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 799)
  def _reduce_152(val, _values, result)
                                 result = GoalMinute.new( **val[0].as_hash )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 820)
  def _reduce_153(val, _values, result)
                                 @tree << GoalLineAlt.new( goals: val[1] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 828)
  def _reduce_154(val, _values, result)
     result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 830)
  def _reduce_155(val, _values, result)
     result.push( val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 838)
  def _reduce_156(val, _values, result)
                               result = GoalAlt.new( score:   val[0].as_ary,
                                                 player:  val[1].as_str )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 843)
  def _reduce_157(val, _values, result)
                               goal_minute = GoalMinute.new( **val[2].as_hash )

                           result = GoalAlt.new( score:     val[0].as_ary,
                                                 player:    val[1].as_str,
                                                 minute:    goal_minute.to_minute,
                                                 goal_type: goal_minute.to_goal_type )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 852)
  def _reduce_158(val, _values, result)
                               result = GoalAlt.new( score:     val[0].as_ary,
                                                 player:    val[1].as_str,
                                                 goal_type: GoalType.new( **val[2].as_hash ))

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 862)
  def _reduce_159(val, _values, result)
                               result = GoalAlt.new( player:  val[0].as_str,
                                                 score:   val[1].as_ary )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 867)
  def _reduce_160(val, _values, result)
                               goal_minute = GoalMinute.new( **val[1].as_hash )

                           result = GoalAlt.new( player:    val[0].as_str,
                                                 minute:    goal_minute.to_minute,
                                                 goal_type: goal_minute.to_goal_type,
                                                 score:     val[2].as_ary )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 876)
  def _reduce_161(val, _values, result)
                               result = GoalAlt.new( player:    val[0].as_str,
                                                 goal_type: GoalType.new( **val[1].as_hash ),
                                                 score:     val[2].as_ary )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 890)
  def _reduce_162(val, _values, result)
                                 @tree << GoalLineCompat.new( goals: val[1] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 894)
  def _reduce_163(val, _values, result)
     result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 896)
  def _reduce_164(val, _values, result)
     result.push( val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 904)
  def _reduce_165(val, _values, result)
                               result = GoalCompat.new( minute:  Minute.new(**val[0].as_hash),
                                                    player:  val[1].as_str,
                                                    score:  val[2].as_ary )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 910)
  def _reduce_166(val, _values, result)
                               result = GoalCompat.new( minute: Minute.new(**val[0].as_hash),
                                                    player: val[1].as_str,
                                                    goal_type: GoalType.new( **val[2].as_hash ),
                                                    score:  val[3].as_ary )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 917)
  def _reduce_167(val, _values, result)
                               result = GoalCompat.new( minute:  Minute.new(**val[0].as_hash),
                                                    score:  val[1].as_ary,
                                                    player:  val[2].as_str )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 923)
  def _reduce_168(val, _values, result)
                               result = GoalCompat.new( minute: Minute.new(**val[0].as_hash),
                                                    score:  val[1].as_ary,
                                                    player: val[2].as_str,
                                                    goal_type: GoalType.new( **val[3].as_hash ))

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 960)
  def _reduce_169(val, _values, result)
                                     @tree << AttendanceLine.new( att: val[1].as_int )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 970)
  def _reduce_170(val, _values, result)
                                   @tree << RefereeLine.new( referees: val[1] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 973)
  def _reduce_171(val, _values, result)
      result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 974)
  def _reduce_172(val, _values, result)
      result.push( val[2] )
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 977)
  def _reduce_173(val, _values, result)
      result = Referee.new( name: val[0].as_str )
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 979)
  def _reduce_174(val, _values, result)
      result = Referee.new( name: val[0].as_str, country: val[1].as_str )
    result
  end
.,.,

# reduce 175 omitted

module_eval(<<'.,.,', 'parser.y', 985)
  def _reduce_176(val, _values, result)
                                     @tree << AttendanceLine.new( att: val[2].as_int )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 993)
  def _reduce_177(val, _values, result)
                                   @tree << CardsLine.new( type: 'Y', bookings: val[1] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 997)
  def _reduce_178(val, _values, result)
                                   @tree << CardsLine.new( type: 'R', bookings: val[1] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1001)
  def _reduce_179(val, _values, result)
                                   @tree << CardsLine.new( type: 'Y/R', bookings: val[1] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1007)
  def _reduce_180(val, _values, result)
                                   @tree << CardsLine.new( type: 'SENTOFF', bookings: val[1] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1016)
  def _reduce_181(val, _values, result)
     result =  val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1017)
  def _reduce_182(val, _values, result)
     result = [val[0], []]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1018)
  def _reduce_183(val, _values, result)
     result = [[],     val[1]]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1019)
  def _reduce_184(val, _values, result)
     result = [val[0], val[2]]
    result
  end
.,.,

# reduce 185 omitted

# reduce 186 omitted

module_eval(<<'.,.,', 'parser.y', 1028)
  def _reduce_187(val, _values, result)
      result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1031)
  def _reduce_188(val, _values, result)
                                result.push( val[2] )

    result
  end
.,.,

# reduce 189 omitted

# reduce 190 omitted

module_eval(<<'.,.,', 'parser.y', 1039)
  def _reduce_191(val, _values, result)
     result = Booking.new( name: val[0].as_str )
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1041)
  def _reduce_192(val, _values, result)
     result = Booking.new( name:   val[0].as_str,
                                                      minute: Minute.new(**val[1].as_hash) )
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1048)
  def _reduce_193(val, _values, result)
                                   @tree << PenaltiesLine.new( penalties: val[1] )

    result
  end
.,.,

# reduce 194 omitted

module_eval(<<'.,.,', 'parser.y', 1055)
  def _reduce_195(val, _values, result)
      result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1056)
  def _reduce_196(val, _values, result)
      result.push( val[2] )
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1062)
  def _reduce_197(val, _values, result)
                                     result = Penalty.new( score: val[0].as_ary,
                                                       name:  val[1].as_str )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1067)
  def _reduce_198(val, _values, result)
                                     result = Penalty.new( score: val[0].as_ary,
                                                       name:  val[1].as_str,
                                                       note:  val[2].as_str )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1073)
  def _reduce_199(val, _values, result)
                                     result = Penalty.new( name: val[0].as_str )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1077)
  def _reduce_200(val, _values, result)
                                     result = Penalty.new( name: val[0].as_str,
                                                       note: val[1].as_str )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1089)
  def _reduce_201(val, _values, result)
                              kwargs = { team:    val[0].as_str,
                                     lineup:  val[1]  }.merge( val[2] )
                          @tree << LineupLine.new( **kwargs )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1104)
  def _reduce_202(val, _values, result)
     result = {}
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1106)
  def _reduce_203(val, _values, result)
      result = { coach: val[2].as_str }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1108)
  def _reduce_204(val, _values, result)
      result = { coach: val[2].as_str }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1112)
  def _reduce_205(val, _values, result)
     result = ','
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1113)
  def _reduce_206(val, _values, result)
     result = '-'
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1115)
  def _reduce_207(val, _values, result)
     result = ''
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1116)
  def _reduce_208(val, _values, result)
     result = ','
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1117)
  def _reduce_209(val, _values, result)
     result = '-'
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1122)
  def _reduce_210(val, _values, result)
                           ## note - value must be DOUBLE [[]] nested in array
                       ##    allows formations (e.g. 4-3-3 or such)
                       ##   via dash (-) separator, see below!
                       result = [[val[0]]]

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1129)
  def _reduce_211(val, _values, result)
                           ## note - if lineup_sep is dash (-) start a new sub array!!
                       if val[1] == '-'
                          result << [val[2]]
                       else
                          result[-1] << val[2]
                       end

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1140)
  def _reduce_212(val, _values, result)
                                  kwargs = { name: val[0].as_str }.merge( val[1], val[2], val[3] )
                              result = Lineup.new( **kwargs )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1147)
  def _reduce_213(val, _values, result)
     result = {}
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1148)
  def _reduce_214(val, _values, result)
     result = { captain: true }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1171)
  def _reduce_215(val, _values, result)
                                 _trace( "REDUCE => lineup_sub_props : PROP_NAME  opt_cards" )
                             result = { name: val[0].as_str }.merge( val[1] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1178)
  def _reduce_216(val, _values, result)
                                 _trace( "REDUCE => lineup_sub_props : PROP_NAME  MINUTE  opt_cards" )
                              result = { name:   val[0].as_str,
                                         minute: Minute.new( **val[1].as_hash )
                                       }.merge( val[2])

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1188)
  def _reduce_217(val, _values, result)
                                 _trace( "REDUCE => lineup_sub_props : PROP_NAME  cards  MINUTE" )
                              result = { name:   val[0].as_str,
                                         minute: Minute.new( **val[2].as_hash ),
                                         cards:  val[1]
                                       }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1199)
  def _reduce_218(val, _values, result)
                                 _trace( "REDUCE => lineup_sub_props : MINUTE  PROP_NAME  opt_cards" )

                               result = { name:   val[1].as_str,
                                          minute: Minute.new( **val[0].as_hash )
                                        }.merge( val[2])

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1211)
  def _reduce_219(val, _values, result)
      result = {}
    result
  end
.,.,

# reduce 220 omitted

module_eval(<<'.,.,', 'parser.y', 1219)
  def _reduce_221(val, _values, result)
      result = val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1223)
  def _reduce_222(val, _values, result)
                                       _trace( "REDUCE => lineup_sub_contents : line_sub_props" )
                                   kwargs  = {}.merge( val[0] )
                                   minute  = kwargs.delete( :minute )
                                   sub = Sub.new(  sub:     Lineup.new( **kwargs ),
                                                   minute:  minute )
                                   result = { sub: sub }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1232)
  def _reduce_223(val, _values, result)
                                        _trace( "REDUCE => lineup_sub_contents : line_sub_props lineup_sub" )
                                   kwargs  = {}.merge( val[0] ).merge( val[1] )
                                   minute  = kwargs.delete( :minute )
                                   sub = Sub.new(  sub:     Lineup.new( **kwargs ),
                                                   minute:  minute )
                                   result = { sub: sub }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1242)
  def _reduce_224(val, _values, result)
     result = {}
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1243)
  def _reduce_225(val, _values, result)
     result = { cards: val[0] }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1253)
  def _reduce_226(val, _values, result)
      result =  [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1254)
  def _reduce_227(val, _values, result)
      result =  [val[0],val[1]]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1255)
  def _reduce_228(val, _values, result)
      result =  [val[0],val[1]]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1256)
  def _reduce_229(val, _values, result)
      result =  [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1257)
  def _reduce_230(val, _values, result)
      result =  [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1263)
  def _reduce_231(val, _values, result)
                    minute = val[0].as_hash.empty? ? nil : Minute.new( **val[0].as_hash )
                result = Card.new( name: 'Y',  minute: minute )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1269)
  def _reduce_232(val, _values, result)
                    minute = val[0].as_hash.empty? ? nil : Minute.new( **val[0].as_hash )
                result = Card.new( name: 'Y/R',  minute: minute )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 1275)
  def _reduce_233(val, _values, result)
                    minute = val[0].as_hash.empty? ? nil : Minute.new( **val[0].as_hash )
                result = Card.new( name: 'R',  minute: minute )

    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

  end   # class Parser
end   # module Fbtxt
